### ISSUE TITLE
IdentityServer4 v4.1 to Duende IdentityServer v6

### ISSUE THREAD

**Issue by JPTIG** [DuendeSoftware/Support#1017]
Hello, I am having issue on the upgrade.

I did follow the instructions here. 
https://docs.duendesoftware.com/identityserver/v6/upgrades/is4_v4_to_dis_v6/

But when I execute the following commands no migration files are being generated and it just say "Build Succeeded". I made sure that the value of -o parameter is correct as well. 

dotnet ef migrations add UpdateToDuende_v6_0 -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb

dotnet ef migrations add UpdateToDuende_v6_0 -c ConfigurationDbContext -o Data/Migrations/IdentityServer/ConfigurationDb

Thanks!

**Comment by josephdecock** [comment]
From our conversation before you opened the issue, I understand you are upgrading from identity server 4 v3. Are you taking an incremental approach - did you upgrade from identity server 4 v3 to v4 before doing this step? Did that create migrations? What all we migrations do you have? What version of the identity server ef package do you have in your project file when you run those commands?

**Comment by JPTIG** [comment]
> From our conversation before you opened the issue, I understand you are upgrading from identity server 4 v3. Are you taking an incremental approach - did you upgrade from identity server 4 v3 to v4 before doing this step? Did that create migrations? What all migrations do you have? What version of the identity server ef package do you have in your project file when you run those commands?

@josephdecock , I went ahead and redo the v3.1.4 to 4.1.2 migration to see if the add-migration works but IT DID NOT WORK as well. 

I did tried this command below but nothing happens. 

dotnet ef migrations add Grants_v4 -c PersistedGrantDbContext -o Migrations/PersistedGrantDb

I did follow your procedure here (https://docs.duendesoftware.com/identityserver/v6/upgrades/is4_v3_to_dis_v6/) so reference packages are already updated to IdentityServer4 v4.1.2 before I execute dotnet ef migration add above. 

Also, I am using EntityFrameworkCore 6.0.20 in my application. I am not sure what is wrong with it but I have been doing my research including trial and error for a week now. Do you have SQL script instead that I can use to update the DB schemas?

**Comment by JPTIG** [comment]
> > From our conversation before you opened the issue, I understand you are upgrading from identity server 4 v3. Are you taking an incremental approach - did you upgrade from identity server 4 v3 to v4 before doing this step? Did that create migrations? What all migrations do you have? What version of the identity server ef package do you have in your project file when you run those commands?
> 
> @josephdecock , I went ahead and redo the v3.1.4 to 4.1.2 migration to see if the add-migration works but IT DID NOT WORK as well.
> 
> I did tried this command below but nothing happens.
> 
> dotnet ef migrations add Grants_v4 -c PersistedGrantDbContext -o Migrations/PersistedGrantDb
> 
> I did follow your procedure here (https://docs.duendesoftware.com/identityserver/v6/upgrades/is4_v3_to_dis_v6/) so reference packages are already updated to IdentityServer4 v4.1.2 before I execute dotnet ef migration add above.
> 
> Also, I am using EntityFrameworkCore 6.0.20 in my application. I am not sure what is wrong with it but I have been doing my research including trial and error for a week now. Do you have SQL script instead that I can use to update the DB schemas?

@josephdecock  any recommendations on how to update the DB schema manually? We have a existing data that we need to keep from version 3.1. 

I am now going through each "Migration" files of different versions of Duende Identity Server to see what are the changes of the DB schema for each version and creating a manual SQL script to update our DB. This is a manual work but this is the only option that I can think of, I would appreciate if you have any inputs. Thanks!

**Comment by josephdecock** [comment]
We don't publish officially sanctioned database migration scripts, because IdentityServer is a framework that is abstracted from the database. The core engine is written entirely in terms of the store abstractions, and even if you are using our implementations of those abstractions, they're deliberately written in a database agnostic fashion using EntityFramework. Any database that has an EF provider could be underneath that. Different databases - and sometimes even different versions of the same vendors database - have different type systems and dialects of the sql language, so the right sql to run to migrate your data will vary a lot from implementation to implementation. Assuming you are using our EF based implementation of the stores, EF can usually generate migrations that make incremental changes relatively straightforward. But if your EF migrations aren't in a good state, some manual intervention is necessary. 

My usual approach, when EF migrations are broken, is to create a local dev environment using the same sql engine as prod, create a fresh install of IdentityServer using our templates and targeting the old version. Use EF migrations to generate a starting schema, then upgrade and use EF migrations to generate an upgrade script. Then you can use that upgrade script to upgrade your environment. 

Finally, I would "squash" the EF migrations in production so that future upgrades are easier, following microsoft's guidelines for resetting migrations: https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#resetting-all-migrations

**Comment by AndersAbel** [comment]
@JPTIG Have you been able to complete the upgrade? Do you need any further assistance or can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
