### ISSUE TITLE
Multiple portals using common identity server issue

### ISSUE THREAD

**Issue by shankarshyam** [DuendeSoftware/Support#1029]
**Which version of Duende IdentityServer are you using?**
6.1.4
**Which version of .NET are you using?**
.NET 6.0
**Describe the bug**
When multiple websites are using one identity server, getting error for second website once we logout of first website.

We have 2 websites using duende identity server. if we open both in the browser at a time, assume login screens for both websites are opened. once we login and log out from first website, and then if we click login on second website, it is throwing error (going to home/error without hitting post method).
**To Reproduce**
1. open 2 websites which are using common identity server. (login screens of identity server should be opened in both websites, but don't login).
2. Now login into first website and immediately logout.
3. Now try to login to second website.
4. We are seeing an error page stating "Sorry, there was an error. Close the page and try again."

**Expected behavior**

It should login to second website as well without any issue

**Log output/exception with stacktrace**

NO stacktrace found. just redirected to home/error and nothing is found.

**Additional context**

**Comment by shankarshyam** [comment]
Thanks Andres for the response. 
You gave the advice that "Try to avoid user flows where the user is left at the login prompt.".
I didn't get it. You mean to say that 'don't do any other action while second website is left at login page'?
Can you suggest if we can overcome and avoid the error in this scenario?

**Comment by AndersAbel** [comment]
It is a common pattern to have a user flow where a logout leads back to the login page, indicating that the user can log back in if they want or close the browser if they want.

When using a single sign on protocol such as OpenID Connect things become more complicated though. Please note that this is not specific to Duende IdentityServer, nor specific to the OpenID Connect protocol. Other products and other protocols such as SAML2 has the same issues. It's just a limitation based on how single sign on protocols work.

When a client application signs on through an external provider it redirects the user's browser to the identity provider. When doing the redirect, the client application also saves some state about the request. Once the identity provider redirects back that state is used to validate the response from the identity provider. In Microsoft's external sign in implementations the state by default has a life time of 15 minutes. After those 15 minutes, any response from the identity provider will be rejected.

There is also the case where two different applications are opened and redirect to the login page, leaving the user with two login pages open. The user could log in using any of the two pages. But the question is - what should be the logical next step in the login page the user didn't use? Should it now automatically detect that there is a session and single sign on the user back to the second application? Should it allow login to be done, possibly with different credentials over-writing the session that the first application created? Note that if the session is over written it means that single logout will not sign the user out of the first application.

I think that the best to do is to be careful with any automatic redirects to the IdentityServer. If the user opens the application and is immediately redirected they might chose to not complete the login sequence at that time. If the user instead is shown a page in the application where they need to click a login button to be redirected, they probably won't initiate the login until they actually intend to complete it. The same is relevant after logout, it's better to leave the user on a "you are logged out" with a button to log back in rather than redirecting to the identity provider.

**Comment by AndersAbel** [comment]
@shankarshyam Do you have any more questions about this or can we close this issue?

**Comment by shankarshyam** [comment]
Sorry @AndersAbel , Thanks a lot for the support on the query, We can close this
