### ISSUE TITLE
Is DPoP token supported for the `/userinfo` HTTP endpoint?

### ISSUE THREAD

**Issue by ciprian-radu-visma** [DuendeSoftware/Support#1031]
**Which version of Duende IdentityServer are you using?**
We are using Duende IdentityServer version [6.3.3](https://github.com/DuendeSoftware/IdentityServer/releases/tag/6.3.3).

**Which version of .NET are you using?**
We are using .NET version 6.0.19.

**Describe the bug**

While I am able to get a DPoP token (using Authorization Code grant type), I cannot use it to call HTTP `GET /userinfo` with it, unless I send it as a Bearer token.
HTTP 401 is returned when I use the DPoP access token as `--header "Authorization: DPoP $TOKEN"`.
HTTP 200 is returned when I use the DPoP access token as `--header "Authorization: Bearer $TOKEN"`.

**To Reproduce**

To reproduce the problem I did some manual steps using Bash and curl.

1. Use the following online service to generate a code verifier and its corresponding code challenge: https://tonyxu-io.github.io/pkce-generator
2. Put the values into variables CODE_CHALLENGE and CODE_VERIFIER.
3.
```
CODE_CHALLENGE=...
CODE_VERIFIER=...
BASE_URL=...
CLIENT_ID=...
SCOPE=openid+email+profile
REDIRECT_URI=...

AUTHORIZE_URL="$BASE_URL/authorize?client_id=$CLIENT_ID&response_type=code&scope=$SCOPE&redirect_uri=$REDIRECT_URI&code_challenge=$CODE_CHALLENGE&code_challenge_method=S256"

curl $AUTHORIZE_URL -i
```

4. Open in the browser the obtained URL from the `Location` response header of the previous HTTP request.
5. After you authenticate in the browser, copy the value of the code query parameter.
6. Put the copied value in the CODE variable.

```
CODE=...
```

7. Use https://mkjwk.org/ to generate a JSON Web Key. See https://developer.okta.com/docs/guides/dpop/main/#create-a-json-web-key
8. Use https://jwt.io/ to create the JSON Web Token. See https://developer.okta.com/docs/guides/dpop/main/#create-the-json-web-token
9. Use https://www.unixtimestamp.com/ to get a value for the `iat` key from the payload of the JWT. The current time can be used.
10.
```
JWT="...."

curl --request POST --url "$BASE_URL/token" --header "DPoP: $JWT" --header 'Content-Type: application/x-www-form-urlencoded' --data 'grant_type=authorization_code' --data "redirect_uri=$REDIRECT_URI" --data "code=$CODE" --data "code_verifier=$CODE_VERIFIER" --data "client_id=$CLIENT_ID" | pp_json
```

11. Copy the access token in the TOKEN variable.

```
TOKEN=....
```

12.1. The following curl will return HTTP 401.
```
curl --request GET --url "$BASE_URL/userinfo" --header "Authorization: DPoP $TOKEN" --header "DPoP: $JWT" -i
```

12.2. The following curl will return HTTP 200.
```
curl --request GET --url "$BASE_URL/userinfo" --header "Authorization: Bearer $TOKEN" -i
```

If I get a DPoP token and then call `/userinfo` with it, but label it as `Bearer` token, it works. And I don't even have to put the `DPoP header`! This is quite confusing. I consider this behaviour wrong. In my current understanding, the DPoP header is necessary, to proof that the device having the token is the device entitled to have it.

**Expected behavior**

Since I can get a DPoP token, I am expecting to be able to use it as such (DPoP not Bearer).
https://docs.duendesoftware.com/identityserver/v6/reference/endpoints/userinfo/ might suggest that only Bearer tokens are supported for this endpoint. Is that true?

From https://docs.duendesoftware.com/identityserver/v6/tokens/pop/dpop/ I understood that DPoP is supported. For what kind of HTTP endpoints could I use a DPoP token, instead of a Bearer token?
Is there any kind of documentation on how to do this, from a client application, that communicates with a backend system which uses Duende Identity Server?

**Log output/exception with stacktrace**

Here is a screenshot that shows what I described in the steps to reproduce.
![image](https://github.com/DuendeSoftware/Support/assets/71488657/90da9eff-b2db-4866-8a75-3e40ec498c7a)

**Additional context**

- I am trying to implement a flow like the one from https://developer.okta.com/docs/guides/dpop/main/#overview for a mobile application that communicates with a backend system which uses Duende Identity Server.

- keycloak allows DPoP for the `/userinfo` HTTP endpoint. See https://github.com/keycloak/keycloak/issues/22215

**Comment by josephdecock** [comment]
We don't currently support DPoP at the userinfo endpoint, and it seems like a gap in the standards. The DPoP spec is an OAuth spec and thus doesn't discuss OIDC at all, and the OIDC spec doesn't know about DPoP. OIDC core spec says:

> The Access Token obtained from an OpenID Connect Authentication Request MUST be sent as a Bearer Token, per Section 2 of [OAuth 2.0 Bearer Token Usage](https://openid.net/specs/openid-connect-core-1_0.html#RFC6750) [RFC6750].

It definitely seems like a gap in the specs, since if you want to secure your other resources with DPoP, presumably you want to secure your Identity Resources as well. 

We'll discuss this internally and update here soon.

**Comment by josephdecock** [comment]
Oh, and to answer your other questions about DPoP, basically you need to add support for DPoP to the apis that you are passing the dpop token to. We have documentation for how to do that [here](https://docs.duendesoftware.com/identityserver/v6/apis/aspnetcore/confirmation/#validating-dpop-proof-of-possession), and a full sample including IdentityServer, client application, and backend api [here](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/DPoP).

**Comment by ciprian-radu-visma** [comment]
Indeed, we would like to have our mobile app use only DPoP tokens (instead of Bearer) for all the communication with the backend system.
Thank you for your comments @josephdecock! I'm looking forward for your update, once you'll discuss this issue internally.

**Comment by josephdecock** [comment]
Since there isn't a specification to rely on here, we aren't currently planning on adding DPoP support to the UserInfo endpoint. We'll definitely be watching what the OpenId Connect working group does, and if some day they add that to their spec we would look at implementing that. 

In the short term, there are a couple of alternatives to the userinfo endpoint
1. Create your own custom endpoint that returns identity information related to the user. IdentityServer v7 (in preview now, final release coming early next month) [includes support](https://github.com/DuendeSoftware/IdentityServer/pull/1338) for DPoP in [local apis ](https://docs.duendesoftware.com/identityserver/v7/apis/add_apis/).
2. Set `Client.AlwaysIncludeUserClaimsInIdToken = true` to force the id token to contain the user info claims. With all the user info claims in the id token, there's no need to invoke the user info endpoint at all.

Option 2 is simpler to implement, but would make your id tokens larger. In web applications, those tokens are typically stored in the session cookie, so this would bloat the cookie. In your case (native apps), the larger token is probably not a big deal.

In any event, you can disable the user info endpoint using `IdentityServerOptions.Endpoints.EnableUserInfoEndpoint = false`.

**Comment by ciprian-radu-visma** [comment]
We will consider the two alternatives that you provided @josephdecock. Thank you!
