### ISSUE TITLE
invalid signature error

### ISSUE THREAD

**Issue by NimaAiryana** [DuendeSoftware/Support#1033]
Hi, unfortunately, we have a bad problem in our case

we have 5 instances of identity server and in all these instances have 3 temp keys, the keys are the same and we are using the offline mode (self-signed) version of authorizing I know when client projects are starting up they get a signing key for self-validating 

and I have a question

whenever client projects are starting up, do they get all these keys or just get one of them for self-validating?

**Comment by josephdecock** [comment]
IdentityServer issues id tokens and access tokens that are cryptographically signed using public key cryptography. The private key is kept secret within identity server, and the public key is used to verify those signatures. In this way, applications and apis can validate the signatures of tokens to know that it was issued by a particular identity server implementation. 

The public keys are published by identity server using the jwks (json web key set) endpoint in discovery. Clients and APIs will retrieve that public key material when they start up. For example, our public demo of identity server publishes its public keys here: https://demo.duendesoftware.com/.well-known/openid-configuration/jwks. You can see there that (as of this writing), there are 2 public keys being published. This is actually common, because cryptographic keys are routinely rotated. When clients and APIs retrieve this key material, they will retrieve all of it at once as a single json response. It is then cached - .NET's apis cache for 24 hours by default. Long lived caches are appropriate, because key rotation is rare, but it does mean that the process of rotating keys needs to be done carefully. 

IdentityServer has an automatic key management feature that will create and rotate keys for you, or you can manage them yourself. We describe this in considerable detail in our documentation on [key management](https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/).

**Comment by NimaAiryana** [comment]
So, I understand that we don't know which Client project is getting which one of those keys (3 temp keys that I have mentioned before) and caching in themselves 

and because of this reason, maybe a user get a JWT from one of the identity projects and whenever that JWT is validating in a client project the signature is deferent and get an invalid signature error unfortunately!

**Comment by NimaAiryana** [comment]
maybe client project can't get jwks from identity server at that time , how can I prevent to start up the project?

**Comment by josephdecock** [comment]
JWTs contain a kid (key identifier) claim which identifies which key was used to sign it. Signature validation finds the right key from the JWKS response by kid. 

You can change options in the client applications and APIs to change cache behavior, but that's not the approach I would take. 

Can you back up and describe the symptoms of the problem? From the title of the post, It sounds like you're getting signature validation errors, but how often does it happen/is it intermittent? Is it affecting every api and client application that validates your jwts? When did this start happening? Did something change? Can you share a log or stack trace from when it occurs?


Also can you please share how you are configuring signing keys in your identity server?

**Comment by NimaAiryana** [comment]
Thanks sir

we have 5 identity servers projects in 5 instances (servers) and we have 5 client api project again in 5 instances

whenever we publish our features in client apis maybe one of them will get the "invalid signature error", I think when the client project is starting up it can't get jwks and so it can't check the signature

unfortunately I don't have any log now but I have talked to my team and we wanna set logs for our issue

we are using AddSigningCredential in our Identity server projects

**Comment by josephdecock** [comment]
Do you really have 5 different identity server projects, or do you mean it just 1 with 5 load balanced instances? 

In addition to the AddSigningCredential call, are you disabling automatic key management in the identity server options?

When you publish the client apis, are you also publishing an update to IdentityServer?

**Comment by NimaAiryana** [comment]
Thanks for answering sir

No, we have 1 Identity server but it has activated on 5 instances but anything in all instances are the same


we are using AddSigningCredential by default options and I think , we have disabled the automatic key management

No we never update our IdentityServer project, just our client apis will be updated

**Comment by josephdecock** [comment]
This sounds like a problem with your client application, or possibly an environmental problem with your network, but not an issue with IdentityServer itself. I recommend that your next troubleshooting steps should be:
Verify that automatic token management is disabled and that each instance of identity server is using the same signing key
Verify that the signing keys that identity server is publishing in its jwks endpoint are not changing, and are consistent even when different instances reply
In your client application, get logs and stack traces from when the problem occurs
Investigate the networking infrastructure that the client application is using to communicate with IdentityServer (is there a firewall or similar in between, and is it allowing the JWKS request through?)

You could also consider enabling the debug and trace log messages in your identity server. This might produce an extremely large amount of logs, but you could filter that to only enable those logs for the Duende.IdentityServer.ResponseHandling.DiscoveryResponseGenerator. Depending on your log provider there are different ways to do that. In serilog, you would do something like 
```cs
.MinimumLevel.Override("Duende.IdentityServer.ResponseHandling.DiscoveryResponseGenerato", LogEventLevel.Debug)
```
The purpose of this logging would be to observe the discovery requests that come to your IdentityServer, and try to understand if the JWKS request is getting there from the API.

**Comment by AndersAbel** [comment]
@NimaAiryana Did you have any success with the suggestions from Joe? Do you have any further questions or can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
