### ISSUE TITLE
Dynamic return url for logout action

### ISSUE THREAD

**Issue by 3rgb** [DuendeSoftware/Support#1034]
Hi.
I’m using .Net 7 and BFF 2.1.1. According to the documentation I setup return url as a query for logout url in react application. This url is properly handled by BFF. In ‘DefaultLogoutService’ value of the url is properly extracted, assigned to AuthenticationProperties and pass to ‘SignOutAsync’ method.

The problem starts in Logout method in Identity Server controller. I can get logout context by logout id, but this context holds static value of PostLogoutRedirectUri which I setup during the configuration. I’ve expected that my dynamic return logout uri which was accessible in BFF will be also accessible here. Unfortunately AuthenticationProperties received for Features of HttpContext also doesn’t contain RedirectUri. The filed is null.

The question is how to return from logout identity server method to page which I setup in my react application. This page url is created in react dynamically. The page uri is in the same app (domain) so this mechanism should works fine.

I appreciate any help or explanation what I could possibly misunderstood.

**Comment by josephdecock** [comment]
All of the redirect uris in the protocols are highly constrained because of the possibility of open redirect attacks, which are one of the leading causes of phishing attacks against OAuth and OpenID Connect providers. The defense against open redirector attacks is to only allow pre-arranged urls as the redirect parameters. This would be somewhat inconvenient though - you want to be able to redirect within the application. But trying to use some sort of pattern matching has historically allowed open redirector attacks (see section 4.1.1 of [OAuth 2.0 Security Best Current Practice](https://datatracker.ietf.org/doc/draft-ietf-oauth-security-topics/)).

Authentication properties are how we get around this problem. The return url is added to the authentication properties, which are then data protected and sent back and forth as the state parameter during the redirection in the protocol. The OIDC provider only gets the data protected state, so it just redirects back to the static return url. But the auth handler listening on that url can unprotect the state, read the return url, and redirect once more.

That's why at IdentityServer you only see a static redirect url. The ultimate return url is being passed around in the encrypted state parameter, and it isn't IdentityServer's job to try to redirect to the final destination.

The BFF includes a query parameter that will set the auth props for you during logout. See https://docs.duendesoftware.com/identityserver/v6/bff/session/management/logout/#return-url.

**Comment by 3rgb** [comment]
Thanks for the answer. I’ve configured the setup of react application with BFF and IDS. Now, when I’m logging out the final redirection is made on the page mydomain.com/signout-callback-oidc?state=… If I understand correctly this state contains redirect url which I put in the logout url. My question is how I can decode this state? Should I implement controller with this route and tries to decode the state somehow or there is a specific handler in asp or identity server when I can decode this value and make another redirection in a way you described?

**Comment by josephdecock** [comment]
The state parameter processing and final redirect are all implemented for you by the OpenId Connect handler that your BFF is already using. The handler both initiates the protocol flow by redirecting to your identity provider and listens for the response on a callback url. When it handles such a response, it implements the checks mandated by the OIDC protocol, starts a session (that is, issues your session cookie), and redirects based on the url passed via the state parameter.

**Comment by 3rgb** [comment]
Work like a charm. Thank you a for the detailed explanation.
