### ISSUE TITLE
Identity setup requirements

### ISSUE THREAD

**Issue by nejulia** [DuendeSoftware/Support#1037]
Hello.

Could you please share a system requirements for the Identity server?
Cannot find the information about recommended min CPU, Memory level?

I know that it depends on expected concurrency & performance but still would like to know some minimal values.
Thank you.

**Comment by josephdecock** [comment]
We don't actually publish system requirements because we think of IdentityServer as a framework that you use with many other tools and components to build a token service. There are just too many options and protocol flows supported by our framework, and the performance of the implementation depends on too many outside factors (e.g., your custom code, dependencies outside IdentityServer, hosting architecture, load balancing, choice of data store, data store implementation, etc, etc, etc) for us to give useful guidance. 

The way that I would approach this is to perform load tests of your IdentityServer implementation. Your load tests can both take into account the traffic that you are expecting AND can exercise all the code that you have in your token service, beyond what IdentityServer itself provides. The good news here is that from the point of view of deployment, scaling, and load testing, an IdentityServer implementation is just another .Net application, so all the experience, expertise, tools, and processes that you may already have developed to operate your other services applies directly to your IdentityServer implementation.

**Comment by AndersAbel** [comment]
@nejulia Do you have any more questions on this or can we close the issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
