### ISSUE TITLE
How to keep the access token renewed ?

### ISSUE THREAD

**Issue by greg-signi** [DuendeSoftware/Support#1040]
**Which version of Duende BFF are you using?**
2.1.1
**Which version of .NET are you using?**
6.0

My use case is that our access_tokens expire always in 5 minutes.. And despite sliding the cookie and extending her lifetime, the accesstoken is never renewed, how is it supossed to happen now ?

**Comment by josephdecock** [comment]
The BFF will automatically refresh the access token using the Duende.AccessTokenManagment library. In order to do that, it needs a refresh token. Are you requesting the offline_access scope in your BFF's OpenIdConnect authentication handler options? And, assuming you're using IdentityServer as the authority, have your set the AllowOfflineAccess flag on the client?

**Comment by greg-signi** [comment]
Yep that sure worked.. thanks @josephdecock
