### ISSUE TITLE
IdentityServer 6/PostgreSQL - table naming

### ISSUE THREAD

**Issue by paultobey** [DuendeSoftware/Support#1041]
Hi,

We license IS6 for several different delivery scenarios and are switching some of those to PostgreSQL from SQL Server. We use EF Core 6 and everything works fine with SQL Server, but need direction adjusting the IS6 table names using PostgreSQL snake-case naming.

We already use a naming convention library, successfully setting the column names correctly but unlike the normal AddDbContext() operations (for all of our other contexts), is not renaming the IS6 tables (ApiResource, PersistedGrants, etc.):

```
		identityServerBuilder
			.AddConfigurationStore(options =>
			{
				options.ConfigureDbContext = builder =>
					builder
						.UseSnakeCaseNamingConvention()
						.UseNpgsql(connectionString,
							sql => sql.MigrationsAssembly(configurationMigrationsAssembly));
			})
			.AddOperationalStore(options =>
			{
				options.ConfigureDbContext = builder =>
					builder
						.UseSnakeCaseNamingConvention()
						.UseNpgsql(connectionString,
							sql => sql.MigrationsAssembly(configurationMigrationsAssembly));

				options.EnableTokenCleanup = true;
				options.TokenCleanupInterval = 3600;
			})
			.AddAppAuthRedirectUriValidator();
```

Of course, we could enumerate all the TableConfiguration items in `options`, setting the table name to snake-case but that seems less than ideal when a new version is accepted potentially adding new tables, etc. Or we could use reflection enumerating the properties of options, converting any that are TableConfigurations to snake-case.

Can you give a more-general (or less reflection-based) solution?

**Comment by josephdecock** [comment]
The two approaches that you're considering are really the only two that are possible. 

If a future version introduced a new table, that would be a breaking change that we would highlight in our release notes prominently, and you'd need a database migration for the new table anyway. Recent releases have added 0 or 1 new tables - we added the server side sessions table in 6.1, but no new tables in 6.0, 6.2, or 6.3. So hopefully needing to add new table name config isn't too painful because it is rare and can be done at the same as your database migrations.

**Comment by paultobey** [comment]
Excellent. I’ll follow that path, then.

Thanks and regards,
Paul T.

----------------------------------------------------------

Paul Tobey
Principal Engineer

Rain Bird Corporation
Golf SBU
6991 East Southpoint Road
Tucson, AZ 85756
(520) 741-6151
***@***.******@***.***>

www.rainbird.com<http://www.rainbird.com/>
