### ISSUE TITLE
[Question] When/where is the Pages/Account/AccessDenied used?

### ISSUE THREAD

**Issue by turbostackapp** [DuendeSoftware/Support#1055]
Sorry if this isn't the right place to ask, but it seemed very specific for the IdentityServer repo.

I can't seem to find any reference in the project when using the quickstart UI to the `Pages\Account\AccessDenied` page.

In which situation does it get called? And is it possible to change it to a different location (looking at translating the name of the view, for example).

**Comment by brockallen** [comment]
Sorry, we didn't see this when it was opened in one of the template repos. I moved it to our support forum [here] to get answered. Sorry for the delay.

**Comment by josephdecock** [comment]
When a request is authenticated (the user is logged in) but not authorized (the user is not allowed to access the resource, usually because the authorization policy's requirements weren't fulfilled), the cookie authentication handler will redirect to the access denied page. More generally, anytime the ForbidAsync method on the authentication service is called, you'll get this redirect. You aren't seeing code that explicitly does that in the sample because the authorization middleware makes the call for you.

You can change the access denied path by setting it in the cookie handler's options: https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationoptions.accessdeniedpath?view=aspnetcore-7.0#microsoft-aspnetcore-authentication-cookies-cookieauthenticationoptions-accessdeniedpath.

**Comment by AndersAbel** [comment]
@turbostackapp Does Joe's response answer your questions? Can we close the issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
