### ISSUE TITLE
Unable to access SignedOutRedirectUri when the GetLogoutContextAsync is called

### ISSUE THREAD

**Issue by SangeetAgarwal** [DuendeSoftware/Support#1059]
**Which version of Duende IdentityServer are you using?**
6.3.4
**Which version of .NET are you using?**
6
**Describe the bug**
I can't read the `SignedOutRedirectUri` and can only read `PostLogoutRedirectUri` when the `_interactionService.GetLogoutContextAsync(logoutId)` is called at [this place](https://github.com/DuendeSoftware/IdentityServer/blob/40a5967e80dddca2777777f2360983c59b726958/hosts/main/Pages/Account/Logout/LoggedOut.cshtml.cs#L26).

**Expected behavior**

I should be able to read the `SignedOutRedirectUri ` when the `GetLogoutContextAsync` is called. 

**Additional context**

This issue existed in Identity 4 and we have yet to migrate to Duende Identity so hoping you can suggest a way of accessing `SignedOutRedirectUri` both in Identity 4 and the newer version(s)

**Comment by SangeetAgarwal** [comment]
The reason we need this populated is that based on whether 'PostLogoutRedirectUri' is populated we shown a link as so
in the `LoggedOut.cshtml`

```
   @if (Model.PostLogoutRedirectUri != null)
   {
       <div>
           Click <a class="PostLogoutRedirectUri" href="@Model.PostLogoutRedirectUri">here</a> to return to the
           <span>@Model.ClientName</span> application.
       </div>
   }
```

**Comment by SangeetAgarwal** [comment]
I was under the impression that `SignedOutRedirectUri` was renamed from `PostLogoutRedirectUri` per [this](https://github.com/dotnet/AspNetCore.Docs/issues/12499)

If you see [here](https://github.com/DuendeSoftware/IdentityServer.Templates/blob/1ea8f9bbdcb320be0b422508a3c9aa8611abf240/src/IdentityServerInMem/Pages/Account/Logout/LoggedOut.cshtml.cs), `logout?.PostLogoutRedirectUri` will always be null since it _doesn't exist_ in `.AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>` i.e. I can't set  `options.PostLogoutRedirectUri` within the handler. 

> you are federating with external identity providers
But it seems `SignedOutRedirectUri` exists only when one is federating with external identity provider which we are not doing. 

So, now the question is: 

1. Why even read ` PostLogoutRedirectUri = logout?.PostLogoutRedirectUri` [here](https://github.com/DuendeSoftware/IdentityServer/blob/40a5967e80dddca2777777f2360983c59b726958/hosts/main/Pages/Account/Logout/LoggedOut.cshtml.cs#L31) when it cannot even be set in the `.AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>` handler

2. Is there any other way for me to pass a value from my handler i.e. `.AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>` that will be available [here](https://github.com/DuendeSoftware/IdentityServer/blob/40a5967e80dddca2777777f2360983c59b726958/hosts/main/Pages/Account/Logout/LoggedOut.cshtml.cs#L23)

Thanks!

**Comment by josephdecock** [comment]
The `PostLogoutRedirectUri` in `logout?.PostLogoutRedirectUri` is set to the validated redirect_uri parameter sent by the client during signout. That parameter is validated by identity server to make sure that it is one of the client's `PostLogoutRedirectUris` (this defends against open redirector attacks).

In other words, when the client application initiates the logout process, it sends a uri along to tell identity server "after we're done logging out, send the user back (to me) here". IdentityServer has to make sure that the uri is one it has pre-arranged for that client, otherwise attackers could abuse the system and redirect you to unexpected places which is highly dangerous. Once identity server has done that validation, it makes that parameter available in the ui as the logout context's `PostLogoutRedirectUri` value.

The `SignedOutRedirectUri` property is part of the OIDC handler, so it will be set within the client application or within IdentityServer but only if IdentityServer is federating with another OIDC provider (and is therefore a client of that provider). That URI is not a protocol parameter, it is merely controlling the behavior of the OIDC handler within a particular application. When you sign out of the OIDC handler, you get redirected to the end session endpoint at your OIDC provider, which ends its own session and notifies other clients before sending you back to the client application's signout callback path. After that whole process is finished, the 
`SignedOutRedirectUri` is used to send the user to a final destination within the client application. But, this is not something that you normally ever send to IdentityServer. 

Normally, at the protocol level you always redirect back to the same place. You can also set the `AuthenticationProperties.RedirectUri` during the logout process. That uri is then where you are ultimately redirected to instead of the `SignedOutRedirectUri`.

Finally, if you do want to send additional non-standard parameters from your client application to the IdentityServer during logout, you can do that, and they will be available in the `LogoutRequest.Parameters` dictionary (the `LogoutRequest` is the result type from calling `GetLogoutContextAsync`).

**Comment by SangeetAgarwal** [comment]
I finally figured out that to have `PostLogoutRedirectUri = logout?.PostLogoutRedirectUri` populated [here](https://github.com/DuendeSoftware/IdentityServer/blob/40a5967e80dddca2777777f2360983c59b726958/hosts/main/Pages/Account/Logout/LoggedOut.cshtml.cs#L31), the `options.SignedOutCallbackPath` must be set as so

```
.AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
{
    ...
    options.SignedOutCallbackPath = @"/authentication/SignedOutCallback";
});
```
And of course must match correspond to an entry in `ClientPostLogoutRedirectUris` table for that client id

The code we trigger on logout looks like so

```
public async Task<SignOutResult> Logout()
{
   
    return SignOut(
            new AuthenticationProperties
            {
                RedirectUri = "url_where_we_must_go"
            },
            OpenIdConnectDefaults.AuthenticationScheme,
            CookieAuthenticationDefaults.AuthenticationScheme);
}
```
In the image below, you'll see that [here](https://github.com/DuendeSoftware/IdentityServer/blob/40a5967e80dddca2777777f2360983c59b726958/hosts/main/Pages/Account/Logout/LoggedOut.cshtml#L13)  points to `https://localhost:7123/authentication/SignedOutCallback` (so the `@Model.View.PostLogoutRedirectUri` is set to `https://localhost:7123/authentication/SignedOutCallback`)  _but_ when one clicks on the link then one is routed to `url_where_we_must_go`. Essentially, the Identity framework intercepts this call and routes you to `url_where_we_must_go` which is being set in the `AuthenticationProperties` above.

I'm just glad I was able to get to the bottom of this through tens of dozens of trial and errors over the past 4 to 5 days!

![temp](https://github.com/DuendeSoftware/Support/assets/2169707/d097a2d3-6d49-4193-9e1f-5c6bd1c4af19)

**Comment by SangeetAgarwal** [comment]
@josephdecock I did want to thank you for taking the time to look at this issue. Your comments helped me quite a bit in gaining a firmer understanding of how Duende Identity works.

**Comment by josephdecock** [comment]
You are welcome! So glad this helped.
