### ISSUE TITLE
V7 Token request failed

### ISSUE THREAD

**Issue by MertGuney** [DuendeSoftware/Support#1065]
**Which version of Duende IdentityServer are you using?**
7.0.0-rc.1

**Which version of .NET are you using?**
.Net8

**Describe the bug**
When I try to get a token of type ClientCredentials or Password, a syntax error occurs.
Microsoft.Data.SqlClient.SqlException (0x80131904):  The syntax near '$' is incorrect.

SELECT [i].[Id], [i].[Created], [i].[Description], [i].[DisplayName], [i].[Emphasize], [i].[Enabled], [i].[Name], [i].[NonEditable], [i].[Required], [i].[ShowInDiscoveryDocument], [i].[Updated], [i0].[Id], [i0].[IdentityResourceId], [i0].[Type], [i1].[Id], [i1].[IdentityResourceId], [i1].[Key], [i1].[Value]
FROM [IdentityResources] AS [i]
LEFT JOIN [IdentityResourceClaims] AS [i0] ON [i].[Id] = [i0].[IdentityResourceId]
LEFT JOIN [IdentityResourceProperties] AS [i1] ON [i].[Id] = [i1].[IdentityResourceId]
WHERE [i].[Name] IN (
    SELECT [s].[value]
    FROM OPENJSON(@__scopes_0) WITH ([value] nvarchar(200) '$') AS [s]
)
ORDER BY [i].[Id], [i0].[Id]

**Comment by AndersAbel** [comment]
This is caused by a performance improvement in the query generation of Entity Framework Core 8.0. It relies on database features that requires a database compatibility level of at least 130. Please see https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#mitigations for more information.

**Comment by josephdecock** [comment]
@AndersAbel, let's add pointers to that microsoft doc to our upgrade guide?
