### ISSUE TITLE
Working with multiple authentication schemes

### ISSUE THREAD

**Issue by tom-crayon** [DuendeSoftware/Support#1075]
**Which version of Duende BFF are you using?**
2.2.0

**Which version of .NET are you using?**
7.0

**Question**

When triggering a sign in via `GET /bff/login`, is there any reason only the default authentication scheme is supported?

**Additional context**

To support a user migration scenario I'm looking at how we can support sign in from multiple IdPs for an application. One option is for the application with BFF to support sign in from either of two IdPs. From an ASP.NET WebAPI perspective that is supported. From a BFF perspective I've needed to override the [DefaultLoginService](https://github.com/DuendeSoftware/BFF/blob/7c799aad736ce145dc445a9165230bc0e61aed7e/src/Duende.Bff/EndpointServices/Login/DefaultLoginService.cs#L83) so the authentication scheme can be passed, validated and used in the `Challenge()` call.

With this change the scheme can be requested like so:
```
GET /bff/login?scheme=myScheme
```

With this working, I'm now looking at other BFF management endpoints to see if further changes are needed.

Is there any technical or security reason to avoid this approach? Are there any pitfalls in the current implementation which may block this approach?

**Comment by AndersAbel** [comment]
Our recommended architecture is to keep the client applications as simple as possible. They should only communicate and trust one single OpenID Provider. If the client can work with multiple providers it means will also get access tokens issued by different providers and then the APIs called would need to know about the different token issuers. I would recommend to first explore any possibilities to deal with the user migration at the OIDC Provider/IdentityServer level rather than in the client application.

But I cannot tell you what is right or wrong in your environment. If you need to configure the BFF to trust multiple OpenID Providers that is certainly possible. I do not see any security issues with doing so. Overriding the DefaultLoginService is the right extensibility point to use to add support for multiple providers.

The automatic refreshing of access tokens through refresh tokens also need to be adapted. By default it assumes that the `DefaultSignInScheme` is set to the open id connect scheme that the user signed in with. It then extracts the configuration information from that scheme. If the user signed in using another scheme than the default challenge scheme this automatic configuration discovery will not work.

**Comment by tom-crayon** [comment]
Thanks for the response and advice on this. Looking at the token renewal process, trying to introduce authentication scheme awareness would require replicating code that we don't want to have to maintain. Based on this, we'll take a different approach where we can use a vanilla BFF setup. Thanks again!

**Comment by caboodal** [comment]
Is it possible to force a specific request to use a different scheme e.g. JwtBearer when API's are being accessed by a trusted third party when they use client credentials to authenticate?

**Comment by AndersAbel** [comment]
@caboodal please open a new issue.
