### ISSUE TITLE
[Question] Enriching eventlog

### ISSUE THREAD

**Issue by vanwinkelseppe** [DuendeSoftware/Support#1077]
**Which version of Duende IdentityServer are you using?**
6.3.5

**Which version of .NET are you using?**
NET 7.0

**Describe the question**
We would like to extend the properties of the event's. With the current ACR_VALUES of the tenant.

This would then be logged in additional info, as in the example underneath.

The most prominent event this would need to be added to is 'Token Issued Success' or 'Failed' but I'm unsure where these are called and if it is possible to add them to it.

```
{
  "ClientId": "Example",
  "RedirectUri": "https://example.com/signin-oidc",
  "Endpoint": "Authorize",
  "SubjectId": "****",
  "Scopes": "openid email",
  "GrantType": "authorization_code",
  "Tokens": [
    {
      "TokenType": "code",
      "TokenValue": "*******"
    }
  ],
  "Category": "Token",
  "Name": "Token Issued Success",
  "EventType": "Success",
  "Id": 2000,
  "ActivityId": "*****",
  "TimeStamp": "2023-10-06T14:52:32.8366902Z",
  "ProcessId": 1,
  "LocalIpAddress": "****",
  "RemoteIpAddress": "****",
  "Tenant": "example-tenant"
}
```

Thanks in advance

**Comment by AndersAbel** [comment]
We are actually looking into deprecating the eventing system in favour of Open Telemetry compatible diagnostics.

So instead of adding anything to the events system I would like to explore possibilities to get this information as structured information attached to log messages. Would that work for you?

**Comment by vanwinkelseppe** [comment]
Hi @AndersAbel 

That would work. But we would like some audit logging on when tokens have been issues and were using a custom event sink to save these events. 

Is it possible to hook into the code that either gives or denies the token to write some kind of audit log to a db?

I've been looking in the documentations but I could only find the CustomTokenRequestValidator

https://docs.duendesoftware.com/identityserver/v7/reference/validators/custom_token_request_validator/

Thanks in advance

**Comment by josephdecock** [comment]
The custom validator is probably not the right thing for you. Most of the failures you want to audit are validation errors that occur before the custom validator runs, and those validation errors return their failure immediately. So your custom auditing validator would never be invoked in the failure case.

In general, failures could occur at any point in the validation process, so you can't really rely on the input parameters in your auditing of failures. e.g., if you wanted to log which client made the request, that's not in general possible for a failure because the client may not have even authenticated. That's why we don't have a simple api that operates on incoming failed requests.

What I would do instead in the short term is add a piece of middleware that checks outgoing response codes of requests to the /connect/token endpoint. If you see a 400, then you can create your failure audit log using the acr_values etc from the query parameters. 

For successful requests, you could do the same thing in your middleware, or you could add logic to a customized [TokenResponseGenerator](https://docs.duendesoftware.com/identityserver/v7/reference/response_handling/token_response_generator/). From the generator, you get a validated object model describing the token request, which might include info that is useful in your logging. 

Response generators in identity server are classes that encapsulate the "business logic" of the protocol endpoints. I think it would make sense to do success auditing code after it runs by extending the class, overloading the ProcessAsync method, calling the base method, and then writing your audit success message. At that point in the pipeline, the only thing left to do is to actually write the outgoing http response. (The response generator creates a response model, it doesn't write to the http response.)

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?
