### ISSUE TITLE
Optional override of Audience / Resource indicator validation

### ISSUE THREAD

**Issue by teepe-ABN** [DuendeSoftware/Support#1079]
**Which version of Duende IdentityServer are you using?**
6.3.8

**Which version of .NET are you using?**
6

**Describe the bug**
When a token is requested, some validations are done by an `IAuthorizeRequestValidator`. Currently, the [default AuthorizeRequestValidator](https://github.com/DuendeSoftware/IdentityServer/blob/2f7360ca39ed849ea5ca7c501edf404be7286722/src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs#L468) checks the format of the request's `Resource` indicator and checks whether it's a valid URI. As our audience and thus Resource indicator don't have a protocol, it fails this check, resulting in a 400:

```
dbug: Duende.IdentityServer.Validation.AuthorizeRequestValidator[0]
    Resource indicator foo.bar is not a valid URI.
fail: Duende.IdentityServer.Endpoints.AuthorizeEndpoint[0]
    Request validation failed
```

I am aware that the audience / resource is an URI in most cases and that this is recommended, but in our case it isn't and it seems it doesn't have to be according to [the JWT standard](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3).
I surely would like to change the audiences we use, but this would require changes in many clients requesting tokens. Thus, this is currently blocking us from migrating from IdentityServer4 to Duende IdentityServer.

**To Reproduce**
Try to request a token with a non-URI `Resource` indicator.

**Expected behavior**
Allow an easy way to override this check, mimicking the behaviour of IdentityServer4

**Log output/exception with stacktrace**
See above.

**Comment by AndersAbel** [comment]
RFC 8707, Resource Indicators for OAuth 2.0, [requires](https://datatracker.ietf.org/doc/html/rfc8707#name-resource-parameter) the resource parameter to be a URI.

Support for resource isolation was added in Duende.IdentityServer v5, there was no built in support for resource parameters in IdentityServer4.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by marcelvwe** [comment]
This issue can be closed. We were using IdentityServer4 before, but some clients inadvertently sent the resource parameter with the authorize request.

This value was ignored with IdentityServer4 due to lacking the support for it, but as a result of our migration to Duende 6, the value was being used and validated, which resulted in the error because it was not a valid URI.

We've implemented a solution to ignore this parameter in case it is not a valid URI (which effectively is the same as the implementation in Idsrv4), to prevent existing clients from breaking. That will allow us to migrate to well formed resources in the future.
