### ISSUE TITLE
Allow overriding the BFF Yarp default timeout

### ISSUE THREAD

**Issue by robbaman** [DuendeSoftware/Support#1088]
**Which version of Duende BFF are you using?**
2.1.1

**Which version of .NET are you using?**
7.0

**Describe the bug**
When using the BFF to forward requests to a remote API endpoint the request timeout used is fixed to 100 seconds. While this is usually ok, we have a few legacy downloads that are hard to migrate and often take longer than 100 seconds to generate a response. 

In the RemoteApiEndpoint class the `ForwarderRequestConfig.Empty` is used (which uses a default ActivityTimeOut) which currently cannot be overridden in any practical way.

https://github.com/DuendeSoftware/BFF/blob/7c799aad736ce145dc445a9165230bc0e61aed7e/src/Duende.Bff.Yarp/RemoteApiEndpoint.cs#L77

**To Reproduce**

After 100 seconds, before the document that needs to be downloaded is generated, a 504 Gateway Timeout is returned.

**Expected behavior**

When registering the `MapRemoteBffApiEndpoint`, or otherwise as a global setting, the default timeout should be a setting.

**Comment by josephdecock** [comment]
The BFF has two different APIs for configuring external routes. The MapRemoteBffApiEndpoint that you're using is intended as a very simple forwarder, with minimal options. For more complex scenarios, we generally encourage users to use our full YARP integration, which allows you to describe your requirements using the power and flexibility of YARP, while adding in our BFF support. We want to keep the simple api, well, simple, so we probably won't add an option for controlling its timeouts since this is a fairly interesting/unusual requirement.

So, please take a look at our [YARP extensions](https://docs.duendesoftware.com/identityserver/v7/bff/apis/yarp/). You can use them in combination with standard yarp configuration for http requests, like the [activity timeout](https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#httprequest).
