### ISSUE TITLE
Docker container IdentityServer

### ISSUE THREAD

**Issue by dmitriyZa** [DuendeSoftware/Support#1096]
**Which version of Duende IdentityServer are you using?**
I am using "Duende.IdentityServer.AspNetIdentity" Version="6.3.2

**Which version of .NET are you using?**
net6.0

**Describe the bug**
I have 2 applications. The first one runs on Blazor server and uses port 5004, the second application IdentityServer uses port 5001. To work with the authentication service, I use BFF(). My task is to containerize these 2 applications in Docker and establish communication between them. If I set the machine to listen to localhost, I can access the Blazor client at localhost:5004, and IdentityServer at localhost:5001 respectively. However, in Docker, I can't use localhost as each container has its own IP. I decided to use environment variables that are specified in the Docker files.

Here web client blazor Startup.cs
![client](https://github.com/DuendeSoftware/Support/assets/89663743/1fa6509e-c441-4c2b-8420-1f421227aec1)

web client blazor dockerfile
![dock blazor](https://github.com/DuendeSoftware/Support/assets/89663743/9334b806-4425-40c4-b441-c8c128f5587c)

IdentityServer Config.cs
![server](https://github.com/DuendeSoftware/Support/assets/89663743/9e02bc0d-9729-4175-bbe7-22f1328a6090)

IdentityServer dockerfile
![dock server](https://github.com/DuendeSoftware/Support/assets/89663743/ff0fd9be-600a-4beb-90b5-a3cb9d1a1d78)

i've built 2 Docker images and launched 2 containers. I added both containers to a single network called "my-network," as indicated by the inspect command.

docker run -d --name web-client --network my-network -p 5004:80 webclient
docker run -d --name auth-server --network my-network -p 5001:80 auth-server-image

I tried to log in from blazor, but for some reason I was getting the page not found. Help me figure out the settings.

**Comment by josephdecock** [comment]
Hi, thanks for this question. Before I begin to answer, a caveat: we aren't docker experts here. We're here to support IdentityServer itself, but we aren't able to answer all questions about all of the many, many ways that it could be hosted. That being the case, I can point out some things that I notice, but I would encourage you to look into the docker documentation and community for better support of docker itself.

It's not clear to me why you're putting both the bff and identity server hosts into the same docker network. Each one needs to expose its ports to allow users to make requests to them in the browser. Communication needs to happen in the web browser, which will not be able to use container names to resolve your hosts. I see a bunch of environment variables that look like they are referring to the containers by name within the network to create front-channel urls. You should not be doing that, because those are urls that are used by a web browser in the end users computer that doesn't know the docker container names.

It also seems wrong to be EXPOSEing ports 5001, 80, and 8080. The way that you have it now, the aspnetcore urls cause asp.net to listen for http requests on port 80 in the container and for https requests on port 5001 in the container. Then you expose both of those ports, along with port 8080 for some reason. But then, you're mapping port 5001 in your host to port 80 in the container. 

I would set up the identityserver host and the bff host to both listen on port 443 (since 443 is the default for https traffic), and EXPOSE just that port 443. Then when you run the container, you can publish port 443 in the container to whatever port you like in your host system. so instead of -p 5004:80, do -p 5004:443 in the bff, and map 5001 in the host to 443 in the identity server container.

I hope this gives you something to work with, and if you need more help I would 
- Try to get two vanilla dotnet hosts running in containers, and make basic <a> links between the two of them
- Look for more docker-specific help in the docker docs/community/etc.

**Comment by dmitriyZa** [comment]
Thank you for the response! It's not quite clear why it's necessary to create separate 2 containers and a separate subnet for each, instead of combining the data services into one subnet (Docker recommends using a common network for data exchange, in this case we access the bff() service, which essentially programmatically accesses the address auth)? And what address should be used in this case for the Enviroment auth and web-client?

**Comment by josephdecock** [comment]
The BFF and IdentityServer are fundamentally two different hosts that are normally each separately available with distinct hostnames. E.g., you could have the BFF available at app1.example.com, and your identityserver implemntation at identity.example.com. When the BFF communicates with IdentityServer, it does so both in the front channel (as a redirect in the end user's web browser) and in the back channel (as a direct server to server call). The front channel needs to use the publicly available host names - the browser can't resolve https://web-client or https://auth-server. And the back channel should use the same names as the front channel so that the issuer and audience can be understood.

**Comment by tnc1997** [comment]
> I tried to log in from blazor, but for some reason I was getting the page not found. Help me figure out the settings.

As @josephdecock mentions in their reply, I expect that the issue is being caused by the authority being set to https://auth-server:5001 in the BBF, which will resolve for container -> container (back channel) requests (because Docker is able to resolve the hostname), but not for host -> container (front channel) requests (because Windows doesn't know the hostname). Adding an entry to the [hosts file](https://en.wikiversity.org/wiki/Hosts_file) that maps the domain `auth-server` to the IP address `127.0.0.1` should allow Windows to be able to correctly route front channel requests from the host to the container.

**Comment by dmitriyZa** [comment]
The issue is resolved. @tnc1997 helped me figure it out. The application was deployed in production, so I needed nginx to redirect routes from http to https. On the localhost machine, https requests were generated by Kestrel; for production, Microsoft recommends using the nginx provider and generating a certificate using certbot. I guess I'll leave my settings in the hope that it will be useful to someone.

File DockerCompose:

version: '3'

services:
  auth-server:
    build: 
      context: ./ServerAuth     
      dockerfile: Dockerfile     
    ports:      
      - "5001:5001"     
    environment: 
      - TZ=Europe/Moscow
      - ASPNETCORE_ENVIRONMENT=Development 
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true      
      - ASPNETCORE_URLS=http://+:5001
      - WEB_ClIENT_IP=https://is-desk.ru    
      - WEB_ClIENT_REDIRECT=https://desk.ru/signin-oidc
      - WEB_ClIENT_REDIRECT_LOGOUT=https://desk.ru/signout-callback-oidc
    volumes:   
         -  auth-db:/path/to/db/directory/in/container
         - /etc/letsencrypt/:/etc/letsencrypt/   
         - /etc/localtime:/etc/localtime:ro
         - /etc/timezone:/etc/timezone:ro
  web-client:
    build: 
      context: ./Desk     
      dockerfile: Dockerfile     
    ports:
      - "5004:5004"   
    environment:
      - TZ=Europe/Moscow
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true          
      - ASPNETCORE_URLS=http://+:5004      
      - AUTHORITY_URL=https://auth.desk.ru
      - CLIENT_ID=web
      - CLIENT_SECRET=secret
      - SIGNED_OUT_REDIRECT_URI=https://desk.ru/signin-oidc
    depends_on:
       - auth-server
    volumes:        
      - desk-db:/path/to/db/directory/in/container
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro  
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:      
      - auth-server
      - web-client   
volumes:
  desk-db:
  auth-db: 

File nginx:

worker_processes 4;

events {
    worker_connections 1024;
}

http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    sendfile on;

    proxy_buffer_size 128k;
    proxy_buffers 4 256k;

    upstream web_client {
        server web-client:5004;
    }

    upstream auth_server {
        server auth-server:5001;
    }  

    server {
        listen 80;
        server_name desk.ru www.desk.ru;

        if ($scheme = 'http') {
            return 301 https://$host$request_uri;
        }

        location / {
            return 404;
        }
    }

    server {
        listen 443 ssl;
        server_name is-desk.ru www.desk.ru;

        ssl_certificate /etc/letsencrypt/live/desk.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/desk.ru/privkey.pem;

        location / {
            proxy_pass http://web_client;
            proxy_redirect off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_cache off;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_read_timeout 100s;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Accept-Encoding "";
        }
    }

    server {
        listen 80;
        server_name auth.desk.ru;
	add_header Content-Type "text/html; charset=utf-8";

        if ($scheme = 'http') {
            return 301 https://$host$request_uri;
        }

        location / {
            return 404;
        }
    }

    server {
        listen 443 ssl;
        server_name auth.desk.ru;

        ssl_certificate /etc/letsencrypt/live/auth.desk.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/auth.desk.ru/privkey.pem;

        location / {
            proxy_pass http://auth_server;
            proxy_redirect off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_cache off;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_read_timeout 100s;
            proxy_set_header Host $host;		
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Accept-Encoding "";
        }
    }
}

Thanks for help!
