### ISSUE TITLE
Why was 7.0.1 not considered a breaking change in regards to the metrics?

### ISSUE THREAD

**Issue by dale-smith-citrix** [DuendeSoftware/Support#1109]
**Which version of Duende IdentityServer are you using?**
7.0.0 upgraded to 7.0.1

**Which version of .NET are you using?**
.NET 8

**Describe the bug**

We had several dashboards built off the existing metrics in our APM vendor. 7.0.1 contained not only changes to the names of the metrics, but also marked several of the metrics under the experimental service name from the original service name. Since we didn't have it configured to emit the experimental service name meter in our OTEL configuration, we're now missing several metrics that we had previously. This seems like it should have been mentioned a s a breaking change in the notes, rather than just listed as a fix.    

**To Reproduce**

Upgrade from 7.0.0 to 7.0.1. The majority of the metrics are no longer emitted by configuring the Duende.IdentityServer.Telemetry.ServiceName meter and now are emitted under the experimental meter service name.

**Expected behavior**

These changes should have been called out as breaking to prevent upgrading until dashboards/alerts relying on these could be modified.

**Log output/exception with stacktrace**

N/A

**Additional context**

**Comment by josephdecock** [comment]
You're quite right that these metric changes were a breaking change that should have been flagged as such in the release notes. We apologize for the inconvenience, and also thank you for pointing it out - we've now updated our release notes and documentation to explain the situation better.

I want to stress that a breaking change in a patch release is an extraordinary exception for us, and we are really committed to the stability of IdentityServer going forward. 

We discovered immediately post launch that many reporting tools that consume otel metrics don't include the meter name when differentiating instruments. Our counters had names that didn't make sense without the meter name, and would easily cause naming conflicts. Given that, it seemed that many of the counters were unusable in at least some environments, so we decided to make an emergency breaking change. We were hopeful that, given the combination of this coming so soon after the release of 7.0.0, this being a new feature, and the usability problems we found, we wouldn't end up breaking anyone. Clearly that wasn't the case, and in any event, we definitely should have done a better job of communicating these changes. 

Going forward, we regard the instruments created by the Duende.IdentitySever meter to be very stable, while the instruments created by the Duende.IdentityServer.Experimental meter may change in a major release. As the metrics stablize, they will migrate out of the Experimental meter. And any change to the metrics is definitely considered a breaking change.

**Comment by dale-smith-citrix** [comment]
Thanks @josephdecock! That makes a lot of sense for the reasoning behind the change. Also good to know about the Experimental meter versus the normal meter as it means we can use experimental in dashboards but will only use the normal meter for alerting.

**Comment by AndersAbel** [comment]
@dale-smith-citrix As Joe pointed out it is an extraordinary exception to make a breaking change in a patch release. One way to see this is that the counter names were so bad that we could consider the naming to be a bug. And bugs can be fixed in patch releases. I agree with Joe that we should have handled the communication better.

Open Telemetry is still young and from what we learned after the first set of counters it is still not clear what the best way is to group different events into counters. We decided that we wanted to keep the detailed metrics exposed even though we are not sure yet if we have found the right way to present them. Exposing them under an "Experimental" name is a way to provide the metrics, while still giving us some room to make changes in the future to how we present them.

We would love to get feedback from our users on how the counters are used, which ones are useful and if there is any information lacking that should be added/removed as tags. If you have any thoughts, please feel free to comment on this issue or open a new one with suggestions.
