### ISSUE TITLE
Identity server login page cancel button 

### ISSUE THREAD

**Issue by hddhagai** [DuendeSoftware/Support#1117]
**Which version of Duende IdentityServer are you using?** 

6

**Which version of .NET are you using?**
6

**Describe the bug**

Pressing the cacel button on the login page does not redirect to thebcalling page but goes to signin-oidc. 

How to get that to work

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

Should redirect to the calling page or the root

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by RolandGuijt** [comment]
Assuming you've used IdentityServer's templates to create your identity provider, the POST request handler that fires denies authorization with the line:

`await _interaction.DenyAuthorizationAsync(context, AuthorizationError.AccessDenied);`

This will post the access_denied error back to the client which is correct behavior.
The problem is that Microsoft's OpenIdConnect middleware doesn't handle that error so instead an unhandled exception is thrown and that is likely what you're seeing.

A way to solve this is to handle the [OnAuthenticationFailed event](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnectevents.onauthenticationfailed?view=aspnetcore-8.0#microsoft-aspnetcore-authentication-openidconnect-openidconnectevents-onauthenticationfailed) on the middleware and write code that does the handling.
Be careful with sending back the browser where it came from however because that location is probably requiring an authenticated user which will redirect to the login page again.

**Comment by hddhagai** [comment]
Is setting OpenIdConnectOptions.AccessDenied to a access denied page good enough? this would redirect to an url

**Comment by brockallen** [comment]
@RolandGuijt Can you check to see if we show this in our samples? If not, it might be a good idea to add (IOW, let's open an issue in ~/Samples).

**Comment by hddhagai** [comment]
**In the Identity Server template**

The senario is when we access a protected resource and we are not authenticated we are redirected to the login page.

On the login page when we click on the cancel button the post action is hit  here first we get the context as below

`var context = await _interaction.GetAuthorizationContextAsync(Input.ReturnUrl);`

Why is the context not null? 

**In the Demo server**

Source code of the demo site that is up on github  

https://github.com/DuendeSoftware/demo.duendesoftware.com

In the same senario as above when we get the context it is null. Why is that so? Am I missing something?

@RolandGuijt

**Comment by hddhagai** [comment]
@RolandGuijt 

This is the URL when we are redirected 

https://demo.duendesoftware.com/Account/Login?ReturnUrl=%2Fdiagnostics

**Comment by RolandGuijt** [comment]
It looks like you're trying to access the diagnostics endpoint on the IdP without being authenticated. Standard behavior for [ASP.NET](http://asp.net/) cookie middleware is to redirect to the account/login endpoint passing in the returnURL which is the URL the user initially tried to access.

That is not a URL GetAuthorizationContextAsync can validate, so it returns null.

In the non-demoserver scenario the login endpoint was probably triggered by a client. In that case the return URL looks more like this:

/connect/authorize/callback?client_id=interactive.mvc.sample&redirect_uri=https://lo/..

That is a URL GetAuthorizationContextAsync validates so then it returns the object.

**Comment by RolandGuijt** [comment]
@hddhagai Is there anything else you would like to add to this issue or can we close?

**Comment by hddhagai** [comment]
@RolandGuijt Sorry have been preoccupied with personal stuff so haven't been able to get back to work and hence not been checking. We can close it. I will get back to looking at your suggestions.
