### ISSUE TITLE
Table names don't allow for convention based naming.

### ISSUE THREAD

**Issue by profet23** [DuendeSoftware/Support#113]
**Which version of Duende IdentityServer are you using?**

6.1.1

**Which version of .NET are you using?**

.net6

**Describe the bug**

Unable to use convention based naming for IdentityServer table names (columns work fine).

**To Reproduce**

Setup https://github.com/efcore/EFCore.NamingConventions and call:

`DbContextOptionsBuilder.UseSnakeCaseNamingConvention()` 

or any other convention from within the `ConfigureDbContext` callback.

**Expected behavior**

The table names to be named based on the convention chosen.

Instead, the tables are named the hard coded values within `ConfigurationStoreOptions` and `OperationalStoreOptions`.

**Additional context**

The `ToTable()` method stomps on EFCore convention based naming.

**Comment by brockallen** [comment]
We have used those options to set the table names so that a variety of DB products will work. For example, Oracle or MySql (I forget which) have certain column name size limits, so this is intended to allow for a way to handle it. This approach was done quite a long while ago (and before many of EF's newer features), so we're hesitant to change it given breaking changes. Perhaps if we were implementing this from scratch now it'd be done differently.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
