### ISSUE TITLE
Question: How do I setup an external client to obtain the userinfo of a logged in user?

### ISSUE THREAD

**Issue by billcunnien** [DuendeSoftware/Support#1136]
Duende v6
.NET 6

I am trying to consider how I would give an external client access to a user's userinfo data from the IS. Our external client suggests that we use the authorization code flow with OIDC. It is a bit baffling to me how a client would be able to get to the userinfo endpoint and pull that specific logged in user's profile data. I am looking through the documentation but do not see how I would connect these dots. Can someone give me an overview of how this might work?

Thanks,
Bill

**Comment by josephdecock** [comment]
At the protocol level, your external client's recommendation is sensible: the userinfo endpoint is protected by an access token with the profile scope, so so the client should use oidc to obtain id and access tokens, and then invoke the userinfo endpoint, passing the access token.

Inside IdentityServer, the IProfileService is used to construct the response to the userinfo request. By default, the profile service looks at the incoming request's scopes to filter which claims to emit. 

The source of the claim data can come from two places: 
1. If you're using server side sessions, then the access token's subject id and session id (sub and sid claims) are used to look up the user's session, and the claims from the session are used.
2. If not, then the claims within the access token are used.

So, if your claims are already being put into the sessions, and server side sessions are enabled, there's nothing more to do. If not, then you can extend the `ProfileService` to load claim data from your user store (or anywhere else).

See [here](https://docs.duendesoftware.com/identityserver/v7/fundamentals/claims/) for more docs, and [here ](https://docs.duendesoftware.com/identityserver/v7/samples/ui/#custom-profile-service) for a sample.

**Comment by billcunnien** [comment]
Thanks, I will take a look at this today and see if I can work things out.

**Comment by billcunnien** [comment]
A user is logged into application A (which does not use IS for authentication) and wants a vendor's application B to have access via IS to their data (exposed via API). The idea is to post a code of some kind from application A to B which then uses that code in some kind of post to IS. IS would then validate the code and start the authorization process (code exchange for token). We have the login with code exchange working, but I would need another landing page to manage this special auth code for the vendor to use, right? This just seems a little outside of the natural process to me. It is as if we are bypassing the login/authentication process and replacing it with a code. Possible?

**Comment by billcunnien** [comment]
Perhaps application A can produce a single-use code (via API) to send to the IS. IS would have a special endpoint to merely validate the code (also via the same API) and start the authorization code flow for the vendor. Is that feasible?

**Comment by josephdecock** [comment]
What you're describing is pretty non-standard. A much simpler approach would be to simply use the OIDC flow as it is designed. In other words, you'd give this external client a client id and give that client access to the identity resources that you want them to have access to. Then, when this external client needs userinfo, they would authenticate. So their application would redirect to identity server, the user would enter their credentials, and then the user would be redirected back to the external client. From there, the client application would exchange the code for tokens and make the userinfo request.

Now, this might be an inconvenient user experience, because they'll have to enter their credentials after they have already logged in at the external provider. You could potentially solve that problem by [federating](https://docs.duendesoftware.com/identityserver/v7/ui/federation/) with this external client's identity provider (assuming they have something that you can federate with).

**Comment by billcunnien** [comment]
Thanks, Joe - we will do our best to stick to the standards. We will eventually integrate the authentication in our application A with IS - then the user experience will slim down a bit. Appreciate the explanation!
