### ISSUE TITLE
Alternatives to 'oidc-client.js/ts' for Using POST Method with connect/authorize and connect/endession APIs?

### ISSUE THREAD

**Issue by abdrizalf12** [DuendeSoftware/Support#1141]
Hello,

I'm exploring options for implementing POST requests for the connect/authorize and connect/endsession APIs with Duende IdentityServer. I understand that these APIs support POST methods on Duende's side

- https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Endpoints/AuthorizeEndpoint.cs#L49
- https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Endpoints/EndSessionEndpoint.cs#L62

Could you advise if there are alternatives to using oidc-client.js or oidc-client.ts that facilitate making POST requests for these particular endpoints? 

Additionally, I'm curious: Is 'oidc-client.js' or 'oidc-client.ts' considered the standard client library for interfacing with Duende IdentityServer ?

Thank you.

**Comment by josephdecock** [comment]
Our recommended approach for browser based appliations is to create a backend host that is paired with the frontend. This backend is called the Backend For Frontend (BFF) host, and is responsible for all of the OAuth and OIDC protocol interactions. Moving the protocol handling out of JavaScript provides important security benefits and works around changes in browser privacy rules that increasingly disrupt OAuth and OIDC protocol flows in browser based applications. 

We discuss these issues in depth [here](https://docs.duendesoftware.com/identityserver/v7/bff/overview/), and show how to use  our BFF library to implement this pattern.

We feel so strongly about the security problems and fundamental architecture problems associated with browser based oidc clients, that oidc-client.js is no longer maintained. My understanding is that oidc-client.ts began as a typescript fork of oidc-client.js, but we aren't involved in that project. 

Finally, yes, using the BFF library would definitely support the response mode of form_post.

**Comment by abdrizalf12** [comment]
When we use a BFF (Backend for Frontend) architecture, and the frontend performs a login operation by calling an API endpoint ('bff/login'), does this involve a request using 'connect/authorize' with a GET method, similar with oidc-client.ts ?
![gambar](https://github.com/DuendeSoftware/Support/assets/46621225/f743aab1-4055-474f-b832-23e18ce874b0)

If so, is it possible to configure this to use the POST method instead?

**Comment by abdrizalf12** [comment]
Could you please confirm if these statements are correct?

When a user is redirected to /bff/login?returnUrl='targeturl' and then submits their username and password to 'Authenticate User', the response from the BFF is a redirect to the returnUrl along with a BFF cookie.
![gambar](https://github.com/DuendeSoftware/Support/assets/46621225/bab0d31b-d489-4bdc-b46a-ec3383e5103a)


This BFF cookie is utilized to obtain user information when fetching from /bff/user, and due to the 'same-origin policy', this BFF cookie is automatically included when fetching from the BFF or any protected APIs.

For the UI to access protected APIs, those APIs must be registered/mapped in the BFF (using MapRemoteBffApiEndpoint or MapGet)

**Comment by josephdecock** [comment]
> When a user is redirected to /bff/login?returnUrl='targeturl' and then submits their username and password to 'Authenticate User', the response from the BFF is a redirect to the returnUrl along with a BFF cookie.

Correct.

> ![gambar](https://github.com/DuendeSoftware/Support/assets/46621225/17642bd2-8d5b-4b42-b46e-a122f1aba7b1)

This diagram has some problems. When it says that the tokens are returned in the url, this is using the implicit flow, which has significant security risks and should not ever be used. Instead of returning the tokens directly, you should use the authorization code flow, which only returns a code in the url. Then the client application makes a second http request directly to the OIDC provider without using the browser. On this call, the code is exchanged for tokens. This prevents many attack vectors, because the tokens are never exposed to the browser, and the code is bound to the client that it was issued to - it can only be used with the client's secret. This exchange is further protected with PKCE. The label above all of this, saying that calling the authorize endpoint is not exposed to the browser is not really accurate - you do go to the authorize endpoint in the browser, and the response with the authorization code also flows through the browser. As discussed above, it is the backchannel call and tokens that are kept out of the browser. 



> This BFF cookie is utilized to obtain user information when fetching from /bff/user, 

Correct, the bff cookie authorizes all calls to the bff.

> and due to the 'same-origin policy', this BFF cookie is automatically included when fetching from the BFF or any protected APIs.

The same origin policy would make the bff cookie automatically get included in requests to the bff that are same origin. That's one reason why our default template hosts the UI and bff together in the same project. But, that's not the only way to host the UI and BFF - they could be on separate origins within the same site and you could use CORS to allow requests from the UI to the BFF and to allow those requests to include "credentials" (the bff cookie).

> For the UI to access protected APIs, those APIs must be registered/mapped in the BFF (using MapRemoteBffApiEndpoint or MapGet)
> 

Yes, this registration sets up the bff to act as a proxy to the protected APIs. It essentially acts as a translation layer, converting from the BFF authorization cookie to the access token required by the API.

> and also, how about silentrenew token in BFF Duende ?

Instead of silent renew, use refresh tokens with the bff. The bff library will automatically refresh tokens as needed, as long as you request a refresh token with the offline_access scope.

**Comment by abdrizalf12** [comment]
Ah, I misunderstood earlier. 
So, essentially, the BFF acts as an OIDC-client but in the backend form not js, 
Everything, including /connect/authorize step, is exposed to the browser, except for when making the /connect/token request, 
This means the client's redirect URI is pointed towards bff/signin-oidc ?

So, if using the implicit flow, where the connect/authorize directly provides the id_token and access token, it means Duende BFF cannot conceal the id token and access token ?

**Comment by josephdecock** [comment]
> Ah, I misunderstood earlier. So, essentially, the BFF acts as an OIDC-client but in the backend form not js, Everything, including /connect/authorize step, is exposed to the browser, except for when making the /connect/token request, This means the client's redirect URI is pointed towards bff/signin-oidc ?

The bff will have a redirect to signin-oidc, where the oidc handler will start a session, and then it redirects again back to the UI. You can control exactly where you go by passing the return url.
 
> So, if using the implicit flow, where the connect/authorize directly provides the id_token and access token, it means Duende BFF cannot conceal the id token and access token ?

Yes. You should never use implicit flow.

**Comment by abdrizalf12** [comment]
Ok,
Could you please confirm if the SSD diagram accurately represents Login process using Duende BFF ?

![gambar](https://github.com/DuendeSoftware/Support/assets/46621225/614bc619-a86a-4627-a6c8-538b875d8828)

**Comment by josephdecock** [comment]
This is substantially correct. One bit of complexity here that is hard to capture in this kind of uml diagram is the distinction that the login page is a UI component of IdentityServer, in the sense that it is a page rendered by the IdentityServer host and then sent to the browser. You've got arrows going through the BFF and back out to the "UI Internet". If we think of the "UI" part as "Anything that is running in the browser", that is fine, but the main SPA application is actually hosted separately from the IdentityServer Login UI (and there is no hop through the BFF to prompt for credentials). But cluttering the diagram with another activitation line specifically for the browser may not actually make it clearer. In any case, it seems like you're understanding the BFF flow. The best way to understand the flow in my opinion is to try it - take a look at our quickstart (https://docs.duendesoftware.com/identityserver/v7/quickstarts/js_clients/js_with_backend/) and watch the network traffic.

**Comment by abdrizalf12** [comment]
Hi @josephdecock , we have already tested the example from BFF (JsBffRunning), but I still have some lingering questions.

Our audit team highlighted that using the query parameter **id_token_hint** when calling the **connect/endsession** API could be considered a vulnerability. If we do not switch to a GET method, it might allow for session fixation or hijacking attacks. A successful attack could enable the attacker to impersonate a victim and gain unauthorized access to the web application.
![gambar](https://github.com/DuendeSoftware/Support/assets/46621225/3798f05d-eca1-44d7-b684-f774b23c1107)

The quickest solution to avoid using **id_token_hint** is not to request the **openid** scope. However, this is not feasible for us since our system requires that scope.

Could you confirm whether calling the API **connect/endsession** with a GET method, as per the standard OAuth 2.0, would allow **id_token_hint** to be potentially hacked or considered a vulnerability?

**Comment by josephdecock** [comment]
There isn't a security concern with using the id_token_hint at the end session endpoint. The RP Initiated Logout protocol is designed to be used in this way, and in fact, the main [security consideration](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#Security) at the endsession endpoint is how to handle the case where id_token_hint is _omitted_. Without an id_token_hint, the identity provider needs to prompt the user before ending the session to prevent an attacker from defacing sessions (which could allow for a denial of service attack, or potentially make a phishing attack more convincing/likely to succeed).

Id tokens aren't a vector for session fixation or hijacking, because the open id connect protocol protects against such attacks in a couple of ways. First, the id token has a short lived expiration, which is enforced by client applications. IdentityServer's id tokens default to a 5 minute lifetime. So, if an attacker stole an id token and tried to replay it, the attack would have to occur within that short amount of time from when the client requested login. More importantly, OIDC also includes a nonce parameter to prevent replay attacks. The nonce is a "number used once", and is generated by the client before it makes its authorize request. The resulting id token then has the nonce included as a claim. When the client receives the id token, it compares the nonce claim to the value it originally created (typically stored in a cookie), and won't proceed to login unless the two values match. And crucially, the nonce value is then destroyed so that the id token can't be used again. Technically, nonces are optional in some cases, but the OIDC authentication handler in ASP.NET (used in the BFF) always includes them, and of course we support the nonce parameter in IdentityServer itself.

**Comment by AndersAbel** [comment]
Looks like everything is sorted out so I'm closing the questions. Please feel free to reopen if neded.
