### ISSUE TITLE
Question: Deviceflow linked user

### ISSUE THREAD

**Issue by davidsterkenburg** [DuendeSoftware/Support#1144]
Right now, we're working on implementing the device flow.
We're using the IDeviceFlowInteractionService to authorize the device.

In this service, the session user is linked to the device, but we want to link another user to the device.
This is an user with specific device roles and can only be linked to a device by an admin account.

Are there possibilities to link this device user to the device or should we implement a custom DeviceFlowInteractionService?

What do you recommend?

**Comment by josephdecock** [comment]
I'm not quite sure what you mean by linking sessions and users to devices. That isn't what the device flow does. The only thing that flow does is obtain a bearer access token - the result of the flow doesn't provide _authentication_ and isn't bound to a session or a device.

In general, I wouldn't recommend the device flow, _at all_. It's deprecated by the standards bodies because it doesn't support MFA or passwordless authentication, doesn't allow for single sign on, doesn't allow for federation with other identity providers, and makes the login experience inconsistent, which at the very least means that you're duplicating work to create the login UI, and at worst trains your users to expect to enter credentials somewhere other than the main login page, which makes phishing more likely to succeed.

Instead, I would suggest you should follow the guidance in [rfc 8252](https://datatracker.ietf.org/doc/html/rfc8252), and use the app auth approach it describes in conjunction with open id connect to authenticate.  Then if need to have multiple users on the device, you can initiate an oidc channlege passing the prompt=login parameter to tell identity server that even if the user has an existing session, they need to enter credentials to login again (presumably as this other user).

Then back in the client application, you'll get the second user's id_token, which you can use to start a session for that user. From there, you'll need to manage the multiple users' sessions in the UI and in your session management within the client application.

**Comment by jvdsmonta** [comment]
Hi, let me give a bit more context (colleague of David),

We have an app running on TV screens showing some dashboards. We want to authenticate this app to our API with our IdP built with Duende IdentityServer. We also need to authorize the app to only fetch the information they need from the API. 

We thought it would be a good idea to create specific users for the TV screens, e.g. tv1building1, tv2building1, tv1building2, etc. 

Then when a TV is being set up, or it logges out for some reason, we want to use the device flow to log it in. Because the TVs do not have a keyboard attached and are hard to reach (placed high at walls). 

But now the access token returned from the device flow contains the user information of the user authorizing the device. We want to have it contain the user information of a TV user (e.g. tv2building1) chosen by the user authorizing the device. 

What's the best way to accomplish this or do you recommend something else?

**Comment by josephdecock** [comment]
Hi, I'm re-reading my previous answer and realizing that I was pretty confused. All of the things that I was saying are relevant to the resource owner password flow, not the device flow. I'm not sure how I managed to get that flipped around - sorry about that!

Anyway, with some more context about what you're trying to achieve, I think I understand better now.

The flow that you're describing isn't directly supported by the protocols that IdentityServer implements. The real issue is that the tv screens aren't being operated by or operating on behalf of an interactive user, so the semantics of having a user logging in doesn't really make a lot of sense to me. It seems like it would be a lot simpler to use the client credentials flow. Then, if you need to distinguish TVs from a security architecture point of view, you would make each such TV a separate client. In this architecture, you would be authenticating particular TVs, and have the ability to make specific authorization decisions per TV.

Alternatively, you could have a single client, and configure the tv identifiers within the client. Then, when your TV client made a request, it would authenticate not as a particular TV, but merely as "the software that runs on the TVs", and it happens to be asking for data relevant in building x, screen y.

**Comment by AndersAbel** [comment]
Another way to handle this would be through a custom login page on IdentityServer. The admin would authenticate using their own credentials, but instead of logging in the admin you would present them with a list of TV user accounts and let them select one. Then the call to `SignInAsync` would be with the TV user account.

**Comment by jvdsmonta** [comment]
Thanks for your help! We are going to try your suggestions.
