### ISSUE TITLE
User Bookmarks IS Login Page With BFF Flow

### ISSUE THREAD

**Issue by mitchescapeplan** [DuendeSoftware/Support#1148]
**Which version of Duende BFF are you using?**
2.1.1
**Which version of .NET are you using?**
net6.0

Hello,

I've implemented BFF into our login flow about 6 months ago. We've been converting a .NET Framework application that is hosted in Citrix into a website, and we're finally starting to slow roll it out to a few clients at a time.

Something we're finding is that our clients are bookmarking the IS login site. That link will work for a little bit, but only until the BFF session expires. After that, when the IS redirects to the /bff/signin-oidc endpoint, BFF just throws an .AspNetCore.Correlation error that says 'cookie not found'. I know implementing a landing page will help some of those users bookmark the landing page instead, but I know people are still going to bookmark the IS login page.

I'm just wondering if there's a "best practice" for handling this case. At the very least I'm hoping to just catch the error and redirect them back to our site, which in turn would redirect them through the full flow and IS will automatically accept everything since they already entered their credentials. Thanks.

**Comment by StuFrankish** [comment]
Not knowing the specifics about your client, I can only offer my own general advice about when I've had this issue myself.
It might not be best practice, but it does do what I need it to do, so you milage may vary.

Inside the `AddOpenIdConnect(...)` call, I've added;
```c#
options.Events = new()
{
    OnRemoteFailure = failureContext =>
    {
        // Log the error

        failureContext.Response.Redirect($"/Error/AuthError?message={Uri.EscapeDataString(failureContext.Failure.Message)}");
        failureContext.HandleResponse();
        return Task.CompletedTask;
    }
};
```
I've then implemented the error controller and view (not included here as you get the drift) as such;
```c#
public class ErrorController : Controller
{
    // GET: /Error/AuthError
    public IActionResult AuthError(string message)
    {
        // Pass the error message to the view.
        return View((object)message);
    }
}
```
In my sandbox repo I'm playing with a client that uses the BFF library from Duende and the PAR OpenIdConnect events type.
Which if you look at their PAR sample, you'll find a `ParOidcEvents` type similar to mine;

```c#
public class ParOidcEvents(HttpClient httpClient, IDiscoveryCache discoveryCache, ILogger<ParOidcEvents> logger, IOptions<IdentityProviderOptions> idpOptions) : BffOpenIdConnectEvents(logger)
{
    public override Task RemoteFailure(RemoteFailureContext context)
    {
        // Custom logic for handling remote failures
        _logger.LogError(message: "Remote Failure Handled in ParOidc Events");

        context.Response.Redirect(location: "/Home/Error");
        context.HandleResponse();

        return Task.CompletedTask;
    }
}
```
I've specifically handled the remote failure there in my sample, but the basic premise is the same either which way you implement it.

**Comment by RolandGuijt** [comment]
To mitigate replay attacks, when the authorization request to the identity provider is initiated by the client's OpenID Connect middleware, "nonce" is part of the URL. It is a query parameter containing a random value.
Simultaneously this value is stored in a cookie.
When login is complete and the tokens are sent the tokens will contain the same nonce value. The client will read the cookie and check if the values are the same.
This cookie has a limited lifetime of 15 minutes by default.
So that's the reason the bookmarked link containing the nonce will only work for a limited time.

The lifetime of the cookie can be extended with the NonceCookie object while configuring the OpenID Connect middleware. However by design it should live only as long as the user needs to log in.

It's important to understand that this behavior is not specific to Duende products, it's just how OpenID Connect works. The handling of the error also isn't related to our products since that's done in Microsoft's OpenID Connect middleware.

So the only things that can be done is educating users and handle the error as @StuFrankish pointed out.
When the error is handled, there are a couple of things to keep in mind though:

- To avoid getting into an infinite loop, don't automatically retry. For example, if there was a cookie configuration problem that made the nonce cookie not get sent, you wouldn't want to automatically do a new challenge at the oidc provider because it would just redirect back to your application and you would still not have a nonce cookie, so you'd get the error again and automatically retry again, looping forever (or until the browser gives up following redirects). Instead, make the user interact with the error page to try again.
- If the user has a session at the client application, you need to convey the current account clearly on the error page. This could happen if a user on the client app used the back button to go back to the login screen. From there, they might enter different credentials in an attempt to switch accounts. The response back to the client would fail, but you'd still have a client session. The user might then be confused about which account they are using. So, if you're on the error screen and have a session, you should say so prominently. And you can even include a "not you?" button to log in as someone else (make that button issue a challenge, passing the prompt=login oidc parameter).

**Comment by mitchescapeplan** [comment]
@StuFrankish That's basically what my thought process was, I just hadn't looked into how exactly it would be implemented. So thank you for the guidance.

And thanks for the response @RolandGuijt. I'll keep all of that in mind when I'm implementing this error handling. I won't be able to work on this for a little bit, so I'll close the issue considering I got my question answered.

I appreciate all of the help.
