### ISSUE TITLE
Pushed Authorization Request validation question (possibly a bug)

### ISSUE THREAD

**Issue by StuFrankish** [DuendeSoftware/Support#1160]
**Which version of Duende IdentityServer are you using?**
Identity Server 7.0.1

**Which version of .NET are you using?**
.NET 8

**Describe the bug**
Identity Server appears to only validate PAR URI's after a user is authenticated, not before.

**To Reproduce**
- Initiate a login using a PAR client.
- Copy the full URL from the browser before logging in.
- Complete the login flow.
- In a new browser tab, paste the copied URL with the PAR URI from the original request.

**Expected behavior**
Based on the details in [rfc9126](https://datatracker.ietf.org/doc/html/rfc9126#name-authorization-request) I would (from my understanding) presume that the Authorization Server should validate the PAR URI parameter exists and is valid before prompting a user for credentials.

Currently a user is able to re-use the same URL with a URI that doesn't exist in the `PushedAuthorizationRequests` table, and only after entering their credentials does Identity Server validate that the URI doesn't exist and return an error.

**Notes**
While the RFC doesn't explicitly dictate the sequence of these checks relative to user authentication, the specification's requirements on request URI usage strongly suggest that the Authorization Server should reject a reused PAR request URI before the user authentication process begins.

**Comment by josephdecock** [comment]
Hi Stu, thanks for the question.  We do actually validate the request uri at the /connect/authorize endpoint before the user authenticates. An attempt to reuse the request uri there will fail. If you skip past the authorize endpoint and go straight to the login page, the login page does render, and sort of functions. What happens is that when the return url is passed to the interaction service, the fact that the request uri has already been used means that the interaction service will return null. This is the same behavior you'd get if you just went directly to, e.g., https://demo.duendesoftware.com/account/login without any redirect uri at all. We don't pass back to the UI that the request uri is invalid, that is true. But we also don't pass a valid authentication context back from the interaction service - its just that our default UI allows the user to continue to authenticate in that circumstance. But you won't have any client-specific information from the context. And then, after the UI redirects back to the authorize callback, we validate request uris again.

So, we think that checking at the authorize and authorize callbacks and returning null from the interaction service in the ui is sufficient. If you really wanted to, you could completely prevent the login page from functioning without a valid request uri by checking for that null from the interaction service. But we default to making the login page functional without a valid request uri since you might want to be able to login on the identity provider outside a protocol flow. In any event, we're not leaking information to the login page through the invalid request uri, since again, you get null back from the interaction service.

**Comment by StuFrankish** [comment]
Thanks Joe, that's spot on!
