### ISSUE TITLE
Request for generic version of  IPersistedGrantStore

### ISSUE THREAD

**Issue by 1saeedsalehi** [DuendeSoftware/Support#1170]
**Which version of Duende IdentityServer are you using?** 

6.0

**Which version of .NET are you using?**

.Net Core 7

**Request:**

In order to add custom fields to the Persisted grant store, we need the ability to specify our custom type instead of using the default `PersistedGrant`. Unfortunately, this is not currently possible with the current implementation. Is there a possibility of having a generic version that would allow for this customization?

**Comment by RolandGuijt** [comment]
I'm curious to know why you would want this since persisted grants are tightly coupled with the OpenIdConnect specification.

You could implement your own version of the store using the IPersistedGrantStore interface. It uses the PersistedGrant model, but the Data property which can contain any serialized (and data protected) grant information.
More information [here](https://docs.duendesoftware.com/identityserver/v6/reference/stores/persisted_grant_store/).

Depending on what you want to do there are also more specialized store interfaces like IRefreshTokenStore, IReferenceTokenStore and IAuthorizationCodeStore which might be more suitable. Take a look [here](https://github.com/DuendeSoftware/IdentityServer/tree/main/src/Storage/Stores) to see what is available.

**Comment by AndersAbel** [comment]
Do you have any more information to share or did Roland's information above answer the question?

**Comment by 1saeedsalehi** [comment]
@RolandGuijt Thank you for your response,  it helped me to find a better solution
