### ISSUE TITLE
Discovery endpoint provides wrong addresses when behind reverse proxy

### ISSUE THREAD

**Issue by poohinq** [DuendeSoftware/Support#12]
Hi, 

We have an Identity Server running on HTTP and there is a reverse proxy in front of it running on HTTPS
The Discovery endpoint ExpandRelativePathsInCustomEntries is left to default - which is true

When try to get /openid-configuration via the reverse proxy , the addresses returned are http not https
The port is translated correctly though. 

Example :
Host Identity Server : **http://localhost**
Reverse proxy : **https://[hostname]:12345**

Addresses provided in /openid-configuration: **http://[hostname]:12345**

Is there an way to provide the correct shceme as well?

Kind Regards,
Svetlana

**Comment by brockallen** [comment]
Have you configured the forwarded headers middleware in ASP.NET Core?

https://docs.duendesoftware.com/identityserver/v6/deployment/proxies/

**Comment by GavinOsborn** [comment]
We haven't used Identity Server in anger yet - just a proof of concept at the moment but I too struggled with this.

By enabling the `ForwardedHeaders` as @brockallen suggests I got the same results that the OP is reporting now.
To fix the discovery endpoint I had to add the following middleware hack to the request pipeline:
```cs
 // Found on StackOverflow from an IdS 4.0 user struggling with exactly the same symptoms.
 app.Use(async (ctx, next) =>
     {
         ctx.Request.Scheme = "https";
         await next();
     });
```

To my mind this should all be covered by the `ForwardedHeaders` - I did check, the correct `x-forwarded-proto` header is received - but I haven't allocated any time to debugging this yet. It's entirely possible the problem is our side.

**Comment by poohinq** [comment]
I figured it out!

Configuring FrowardedHeaders in ConfigureServices() and just calling app.UseForwardedHeaders() in Configure() didn't work.

But providing the configuration in  UseForwardedHeaders as parameter did the trick 

app.UseForwardedHeaders(new ForwardedHeadersOptions(){...});

**Comment by poohinq** [comment]
it works both way - removing services.Configure<ForwardedHeadersOptions>()  or not
As for the ForwardedHeadersOptions
            var options = new ForwardedHeadersOptions();
            options.ForwardedHeaders = ForwardedHeaders.All;
            options.ForwardLimit = 1;

            options.KnownNetworks.Clear();
            options.KnownProxies.Clear();
