### ISSUE TITLE
IRequestObjectValidator internal scope

### ISSUE THREAD

**Issue by tiagofe** [DuendeSoftware/Support#1223]
**Which version of Duende IdentityServer are you using?**
7.0.4

**Which version of .NET are you using?**
8

**Expected behavior**
We would like to use the `IRequestObjectValidator` in our custom classes. However, since the IRequestObjectValidator in internal, it is not possible to do that.

My question is would be possible to make `IRequestObjectValidator` having public scope? Any problem doing that?

https://github.com/DuendeSoftware/IdentityServer/blob/7.0.4/src/IdentityServer/Validation/IRequestObjectValidator.cs#L9

**Comment by AndersAbel** [comment]
Anything in IdentityServer that is `public` and can be accessed by external callers need careful change management to avoid breaking changes. Sometimes we do keep classes and interfaces internal if we think that they are an implementation detail and not anything we expect external code to use.

Could you please share some more information about your scenario and how and why you would like to use the `IRequestObjectValidator` directly? The only place that we use it internally is as part of our `IAuthorizeRequestValidator` implementation. That implementation is also internal, but the `IAuthorizeRequestValidator` interface is public. Why would you want to call the `IRequestObjectValidator` directly instead of going through the `IAuthorizeRequestValidator`?

**Comment by RolandGuijt** [comment]
@tiagofe Would you like to continue with this issue? If not I'd like to close it.

**Comment by RolandGuijt** [comment]
Closing for now, but please re-open if needed.
