### ISSUE TITLE
Large file download via browser example

### ISSUE THREAD

**Issue by tylersouthard** [DuendeSoftware/Support#1323]
**Which version of Duende BFF are you using?**
Duende.BFF.Yarp 2.2.0

**Which version of .NET are you using?**
ASP.NET 8

**Describe the bug (question)**
I have a React frontend with an ASP.NET 8 backend using the Duende BFF library, similar to the example [here](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v7/BFF/JsBffYarpSample). I have a separate ASP.NET 8 web API that the frontend+BFF call into (the BFF reverse-proxies calls from the frontend to the API).

Could you provide an example of how to have my frontend download a large file using the browser's download mechanism (e.g., Chrome performs the download, progress, etc.)? I control all three parts, and currently am trying to serve a file from the API by returning a `FileStreamResult` (streaming a large file from Azure Blob Storage). On the frontend, I can't just set the window's `href` to the API route, since it results in a 401 due to not going through the reverse proxy, etc. (I think?). I'm wondering how to go about a normal (in-browser) download in this case? 

It seems like I need to set `window.location.href = /api/path/to/remote/api/download/endpoint`, but it doesn't seem to work the same way as the rest of my API calls. For my other calls, I use Axios and it seems to properly use the reverse proxy with the auth cookie. But I get a 401 when attempting to use `window.location.href`, and the remote API doesn't see a call at all. If I bypass the reverse proxy and simply call to the remote API URL directly, the call goes through to the remote API, but it gets a 401 there. If I change the endpoint to allow anonymous access, the download works as expected. So the question is, how can I resolve the above two issues, so I don't need to bypass the reverse proxy and so I don't need to set the endpoint to allow anonymous access.

**Additional context**
Using React on the frontend, if that matters.

**Comment by josephdecock** [comment]
When you use the api proxying built in to the BFF, it expects that the caller will set an anti-forgery header. This triggers a CORS pre-flight request, preventing unexpected cross site requests (which could be a cross site request forgery). When you set the window.location the way that you describe, the browser won't include the anti-forgery header, and thus you get the 401 that you're seeing. Probably things work when you use Axios because you have some configuration for axios's requests to include the anti-forgery header. For more details on the header, see our docs on remote apis [here](https://docs.duendesoftware.com/identityserver/v7/bff/apis/remote/).

Instead of setting the location in this way, the way to tell browsers that a link is meant to be downloaded is to set the [download property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/download) of an anchor tag. For example <a href="example.com/path/to/big-file.txt" download="suggested-name">Download Me!</a>. If the user clicks on that link, browsers will download the file instead of navigating to the url. Unfortunately, the same functionality isn't part of the fetch api or similar, so the process of downloading a file initiated by javascript is a bit clunky. You have to create the anchor element with the download property set, add it to the dom (visually hidden), simulate a click on that element to start the download process, and then remove the anchor.

**Comment by josephdecock** [comment]
(Further discussion moved to other support channel.)
