### ISSUE TITLE
On silent authorization challenge return, referrer policy defaults to `no-referrer`

### ISSUE THREAD

**Issue by terflespie** [DuendeSoftware/Support#1335]
**Which version of Duende IdentityServer are you using?**
6.3.7

**Which version of .NET are you using?**
dotnet core 6.0

**Describe the bug**
On silent authorization challenge return from identity server, when `response type` is set to `form_post`, `referrer policy` in headers is set to `no-referrer` which removes referrer which is used for website analytics.

**A clear and concise description of what the bug is.**
In our implementation of Identity Server, our client website performs a silent authorization challenge on each page request.  In the OpenIdConnectAuthenticationOptions, we've recently updated our ResponseMode from `query` to `form_post`. Our analytics team reported that they were no longer able to report on organic search referrals. Investigating further, we found that this change caused the `Referrer Policy` in the authorization return to change from `strict-origin-when-cross-origin` to `no-referrer` which removes the value from `document.referrer`. 

**To Reproduce**

Steps to reproduce the behavior.
On client application, perform Request.GetOwinContext().Authentication.Challenge with Response Type = code, Reponse Mode = form_post. Notice in browser developer tools on authorization return to client,  `referrer policy` defaults to `no-referrer`.

**Expected behavior**

When updating ResponseMode from `query` to `form_post`, `Referrer Policy` acts similar on silent authorization challenge return.

**Log output/exception with stacktrace**

Did not see related log/output related to bug.

**Additional context**
![2024-07-15_14-21-15](https://github.com/user-attachments/assets/9f35daf1-baa3-4cd1-8566-fee568f585ba)

**Comment by RolandGuijt** [comment]
To avoid leaking sensitive information the OAuth specification [specifies](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#name-countermeasures-2) that no referrer should be included in the response.

Alternatively the referrer could be put in the authentication properties (`AuthenticationProperties` object) so it becomes part of the state of the flow which is protected.
In addition: is there a specific reason you are doing the challenge with every request? Asking because the recommended way is to do it when the access token expires in an iframe with the prompt option set to none.

**Comment by terflespie** [comment]
_"Alternatively the referrer could be put in the authentication properties (AuthenticationProperties object)"_
Currently investigating `AuthenticationProperties`

_" is there a specific reason you are doing the challenge with every request?"_
In the scenario that a user signs out of oauth directly or on another client we need to unauthenticate the user from the current session on next page request.

**Comment by RolandGuijt** [comment]
Instead of challenging with every request we recommend [front channel logout notifications](https://docs.duendesoftware.com/identityserver/v7/ui/logout/notification/#front-channel-server-side-clients) if possible for SPAs without a backend.
To avoid problems with browsers and iFrames when the SPA uses a backend (BFF), back channel logout notifications are the way to go.

**Comment by terflespie** [comment]
@RolandGuijt Appreciate you pointing me in the right direction, I noticed in the [MvcBackChannelLogout](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v7/Basics/MvcBackChannelLogout) example that if the user authenticates on IdentityServer and in a new tab visits a client non-secure page that they are not authenticated. How can we still achieve the silent login using back-channel notifications?

**Comment by RolandGuijt** [comment]
Please create a separate issue for this as this is deviating from the original question.
I'm assuming the original issue was addressed, so I'm closing this one. If my assumption is wrong, feel free to reopen.
