### ISSUE TITLE
Migration from IdentityServer4 to Duende

### ISSUE THREAD

**Issue by vikivenkat** [DuendeSoftware/Support#1365]
**Which version of Duende IdentityServer are you using?**
Not started using yet. Trying to identify a replacement for IdentityServer4

**Which version of .NET are you using?**
.NET 8.0

**Describe the bug**
Not a bug. Trying to decide on a replacement for IdentityServer4. Please see "additional context" section for more info.

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**
We have been using IdentityServer4 in our applications so far. We are looking to migrate to another Identity Provider and have identified duende as one of the potential replacements. Wanted to check on the following points
1. How easy is it to migrate from IdentityServer4 to Duende?
2. Is there a documentation available for the above? (We are using it in .NET 8)
3. Can we reuse the same tables created by the IdentityServer4 in Duende?
4. Does Duende allow for customization of the tables?. This was possible in IdentitytServer4 and we had altered the Identity Provider created tabled to add additional columns of our own.
Thanks

**Comment by RolandGuijt** [comment]
Answering your questions using your numbering:

1. Easy is a relative term but it will mostly involve upgrading the database schema with migrations and some modifications around the configuration. If you have any customizations (like a custom store) these might require some more work since parts of the API have changed like some interfaces.
2. Yes, it's [here](https://docs.duendesoftware.com/identityserver/v7/upgrades/). There's a guide to upgrade from v4.1 to v6.0. From there I would recommend to upgrade to each next minor version until you reach the desired one. This will also give you a good idea around what is new.
3. No. The database schema has changed. From v4 to v7 there are quite a few changes. But the data in the tables (using the default entities) can be mostly retained when running the migrations.
4. Yes, there still is a ConfigurationDbContext and a PersistedGrantDbContext with their entities and modification of the entities should work in the same way.

**Comment by RolandGuijt** [comment]
@vikivenkat Did my comment help? If you have any more questions feel free to add them. If not I'd like to close this issue.

**Comment by vikivenkat** [comment]
> Answering your questions using your numbering:
> 
> 1. Easy is a relative term but it will mostly involve upgrading the database schema with migrations and some modifications around the configuration. If you have any customizations (like a custom store) these might require some more work since parts of the API have changed like some interfaces.
> 2. Yes, it's [here](https://docs.duendesoftware.com/identityserver/v7/upgrades/). There's a guide to upgrade from v4.1 to v6.0. From there I would recommend to upgrade to each next minor version until you reach the desired one. This will also give you a good idea around what is new.
> 3. No. The database schema has changed. From v4 to v7 there are quite a few changes. But the data in the tables (using the default entities) can be mostly retained when running the migrations.
> 4. Yes, there still is a ConfigurationDbContext and a PersistedGrantDbContext with their entities and modification of the entities should work in the same way.

Thanks @RolandGuijt for the reply. That helps
