### ISSUE TITLE
Update Lifetime of refresh_token in Persisted Grant Store when AbsoluteRefreshTokenLifetime is changed on client

### ISSUE THREAD

**Issue by linuxchata** [DuendeSoftware/Support#1385]
**Which version of Duende IdentityServer are you using?**
7.0.6

**Which version of .NET are you using?**
net8.0

**Describe the question**
Flow: authorization_code. RefreshTokenExpiration: Absolute. RefreshTokenUsage: ReUse
AbsoluteRefreshTokenLifetime was changed from 3 months to 5 years. Is there a build-in way to update Lifetime of refresh_token in Persisted Grant Store without removing / invalidating refresh tokens?

**Comment by RolandGuijt** [comment]
Unfortunately there's no built-in way to do this.

However, the `DefaultRefreshTokenStore` class has [a method](https://github.com/DuendeSoftware/IdentityServer/blob/e9860c6488f90e8fbc11a4452b9dd111dbfae933/src/IdentityServer/Stores/Default/DefaultRefreshTokenStore.cs#L54) to update a refresh token. That calls [StoreItemAsync](https://github.com/DuendeSoftware/IdentityServer/blob/e9860c6488f90e8fbc11a4452b9dd111dbfae933/src/IdentityServer/Stores/Default/DefaultGrantStore.cs#L194) which is in the parent class `DefaultGrantStore`. That method is protected and takes an expiration `DateTime`.
Just for the migration, you should be able to derive from `DefaultRefreshTokenStore`, create a new method on the new class and call `StoreItemAsync` from that for example.
In addition you would have to override `StoreItemAsync` which hashes the key for security purposes. For the migration you would have to skip that step so that the actual key is used.
Also keep in mind that the data in the item itself is data protected.

**Comment by AndersAbel** [comment]
> For the migration you would have to skip that step so that the actual key is used.

To do this, use the the `GetItemByHashedKeyAsync()` and `StoreItemByHashedKeyAsync()` protected methods of the `DefaultGrantStore<T>`. The hashed key is the Id the Id that is actually in the database. If you read items from the Db and want to loop over them and process the items, these are the methods to use.
