### ISSUE TITLE
How to add client authentication with workload identity federation without a configured secret?

### ISSUE THREAD

**Issue by jesperkristensen** [DuendeSoftware/Support#1453]
**Which version of Duende IdentityServer are you using?**

**Which version of .NET are you using?**
.NET 8

**Additional context**

I am investigating if it is possible for clients to authenticate to IdentityServer without manually managing client secrets or keys. I am running my client applications in Kubernetes on-premises. I am thinking something similar to how Azure Entra ID (https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation-create-trust) and Google cloud support Workload Identity Federation, where I can configure the Kubernetes discovery endpoint URL https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery and a valid subject and audience for the client. Is this possible with Duende IdentityServer?

**Comment by narbit** [comment]
@AndersAbel, do you have any recommendation or thoughts on how this could be implemented in Duende? Should this be based on a custom token-exchange extension grant where client doesn't have a secret assigned OR is it a `client_credentials` token request that authenticates client with`"client_assertion": id_token, "client_assertion_type": "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"` ?

**Comment by josephdecock** [comment]
My initial reaction is that you can achieve client authentication without needing a shared secret by using the private key jwt client authentication mechanism. Basically the clients have a public private key pair that they use to sign requests, and IdentityServer is configured with the public key only to verify the signature. We have more docs here on that: https://docs.duendesoftware.com/identityserver/v7/tokens/authentication/jwt/. I'm not sure if this is exactly what you're looking for, but it would mean that you didn't have to have a shared secret between the services.

**Comment by narbit** [comment]
@josephdecock , a key pair is still just another type of secret. This is a bit different since WLI federation assumes no secrets at all. The links @jesperkristensen posted explain the approach.  Here is an additional reference with a nice diagram demonstrating it from the Azure side of things - https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation. GCP has similar docs.

The approach assumes there's a preconfigured trust in IDP that maps an IDP "service account" (client/executor) to a subject and issuer from the external entity so it can act "on-behalf-of" that external entity, i.e. get tokens and allow the external entity call IDP protected resources with a swapped token. This way secrets are not needed, the external entity token is validated against pre-configured trust values.

I'm thinking Duende token exchange w/out secret and with trust (mapped subject, issuer) configured via client's properties could accomplish this. Still deciding on the best approach though.

**Comment by RolandGuijt** [comment]
@narbit Checking to see if you are still waiting for a reaction or can we close the issue?

**Comment by narbit** [comment]
@RolandGuijt , it'd be nice to get your guys' opinion on potential options for workload identity implementation in Duende. Right now I'm using a token exchange approach combined with Client Properties to configure federated credentials. Would love to know if this is something that could be supported out of the box at some point but this can be closed for now. Thank you!

**Comment by josephdecock** [comment]
@narbit thanks for getting in touch. One thing to keep in mind about the managed identities in the cloud providers is that secrets are still being shared, it is just that those secrets are being managed by the infrastructure rather than within the application. Since we operate at the application layer, there isn't a clear way that we could do that. The other thing to take into account is that trust has to be bootstrapped by something - it's not clear to me how that would work with your token exchange mechanism.

**Comment by narbit** [comment]
I know this is closed but will leave this here for posterity. I might not have been clear describing the feature request but I (and I suspect the OP) was specifically after WLI Federation. This is how [Google describes](https://google.aip.dev/auth/4117) it:

`Traditionally, applications running outside Google Cloud have used service account keys to access Google Cloud resources. Using identity federation, you can allow your workload to impersonate a service account. This lets you access Google Cloud resources directly, eliminating the maintenance and security burden associated with service account keys.`

Similar functionality is available in Azure. So the question was how could Duende accommodate for such impersonation and eliminate the need for secrets? In other words, how do we configure a trust in Duende to allow a service to present a token from another IDP and use that as an authentication mechanism specific to that service instead of using a secret. 

Currently, I am using token exchange combined with a pre-configured external identity subject (via client properties in client configuration). So when a token request comes in via this extension grant and the subjectId on the incoming token matches the one configured on the client in the request, I allow for the token to be issued. But I was curious if there are better ways.

**Comment by AndersAbel** [comment]
As Joe said, there has to be some kind of trust to bootstrap an implicit trust through workloads/identity federation/service principals.

Using token exchange would be a viable solution to use the existing cloud infrastructure as the basis of the trust to let IdentityServer issue tokens based on that.
