### ISSUE TITLE
querySessionStatus generates a new reference token - is this correct?

### ISSUE THREAD

**Issue by rhysgodfrey** [DuendeSoftware/Support#1466]
**Which version of Duende IdentityServer are you using?**
7.0.6

**Which version of .NET are you using?**
.NET 8

**Describe the bug**

We are using reference tokens and the [querySessionStatus method in oidc-client-ts](https://authts.github.io/oidc-client-ts/classes/UserManager.html#querySessionStatus) to check if the server side session has changed in our front end application.

We trigger this check on a timer, everytime we query the session status a new reference token is generated, as this essentially does a silent signin I can see why this makes sense, but is it expected behaviour?  Intuitively this doesn't feel correct, but technically can see why.

This is causing our app to generate a large number of reference tokens, which the cleanup job is then struggling to clean up itself on the default settings.

**To Reproduce**

Create a new client with GrantType of Code, and AccessTokenType of Reference.

Create a new HTML/JS front end to sign in with, and then add a button to trigger the querySessionStatus call, when pressing this button inspect the responses/the database to see a new reference token being generated on each press.

**Expected behavior**

Querying session status wouldn't generate a new reference token.

**Comment by AndersAbel** [comment]
If the `querySessionStatus` method does a silent login it will create a new token yes.

Have you considered using the check session mechanism to monitor the session? It provides a JavaScript event and does not run any login flow. The check session feature only works within the same site on modern browsers due to third party cookie blocking. But if you are able to run the `querySessionStatus` method using a hidden iframe, then the check session iframe should work too.

**Comment by RolandGuijt** [comment]
@rhysgodfrey Is there anything else we can help you with regarding this issue? If not I'd like to close it.

**Comment by rhysgodfrey** [comment]
Sorry for the delay. That answers my question so nothing more on this, thank you.
