### ISSUE TITLE
Refresh Token - ReUse tokens

### ISSUE THREAD

**Issue by evilanf** [DuendeSoftware/Support#1478]
**Which version of Duende IdentityServer are you using?**
v7

**Which version of .NET are you using?**
.net8

**Describe the bug**
This is more of a question than a bug, im sure the issue is my understanding.

I have an interactive mobile application that is not working after 30 days at my best guess, which I assume is the lifetime of the refreshtoken
given the default settings are to reuse refreshtokens and the absolute lifetime of a refreshtoken is 30 days.

My question is that if refreshtokens are reusable and they have a lifetime of 30days, how are we supposed to handle the tokens after 30 days? Or when its a public facing mobile application, should it be using oneTime tokens? 

hope that has enough to convey my question, thanks in advance.

**Comment by evilanf** [comment]
Ok so I think I see my issue the reuse option is fine. It was the default of the token expiry set to absolute for mobile users, sliding is the best approach, so they continuously have access to the token without it expiring or requiring another login.

**Comment by RolandGuijt** [comment]
The `RefreshTokenUsage` setting on the client is about what happens when a refresh token is used within its lifetime. With `ReUse`, the same one will be used the next time the access token is refreshed, with `OneTimeOnly` a new one will be created each time which adds database pressure and has reliability issues. It also turns out that `OneTimeOnly` [doesn't really offer security benefits](https://blog.duendesoftware.com/posts/20240405_refresh_token_reuse/).

This setting is separate from how the lifetime is managed. As you have discovered there's the possibility for an absolute or sliding lifetime here but they can also be used together. The nuances of these are documented [here](https://docs.duendesoftware.com/identityserver/v7/reference/models/client/#refresh-token).
