### ISSUE TITLE
Feature: Add IdentityProviderProperty to set IdentityProvider properties

### ISSUE THREAD

**Issue by pampua84** [DuendeSoftware/Support#1501]
Hi,
is there any plan to add an IdentityProviderProperty class, similar to the ones for Client, ApiResource, etc.? 

This table could be very useful for setting additional properties on IdentityProvider, example such as enabling the LoginHint, or determining which flow to execute for a given provider based on its properties, and so on.

Thanks

**Comment by RolandGuijt** [comment]
Do you mean the `Dictionary<string, string> Properties` property?
If so it is already [present](https://github.com/DuendeSoftware/IdentityServer/blob/908d3dd8a4029a29069034db41cca5d99b20a1ce/src/Storage/Models/IdentityProvider.cs#L84).

**Comment by pampua84** [comment]
However, the basic properties of this type of object must still be predefined (see OidcProvider or SamlProvider properties). It would be convenient to have an additional table to simply add other properties or attributes to the IdentityProvider, without having to deserialize a JSON (dictionary), which in the case of SamlProvider is also quite substantial.

**Comment by jpda** [comment]
We've added our own in a derived DbContext but it would be great to have this out-of-the-box. Extending EF is a huge pain.

**Comment by damianh** [comment]
Schema changes, especially for a library, are particularly problematic. Every change requires a migration of some sort and is considered a breaking change. This is both a blessing and a curse. The former because it's been stable over the years and the latter because we haven't been able to make improvements without needing to bump the major version every time.

In the future we'll be re-evaluating our approach to our storage interfaces and implementations thereof.

**Comment by RolandGuijt** [comment]
Closing this issue for now in light of Damian's comment, but if you'd like to add anything, please do so.
