### ISSUE TITLE
Upgrading from IdentityServer v4 to v6.1, SetIdentityServerOrigin is obsolete

### ISSUE THREAD

**Issue by martyt** [DuendeSoftware/Support#152]
Getting a warning about `SetIdentityServerOrigin()` being obsolete, but the suggestion ("Use IServerUrls.Origin instead.") doesn't mean anything to me. I can find no occurrences of `IServerUrls` anywhere via Google. 

What am I missing here? 

```
                app.Use(async (ctx, next) =>
                {
                    ctx.SetIdentityServerOrigin(_baseUrl);
                    ctx.Request.Scheme = "https";

                    await next();
                });
```
https://github.com/DuendeSoftware/IdentityServer/blob/e929f3e3a681613a2d72ef923be87740bbe3b876/src/IdentityServer/Extensions/HttpContextExtensions.cs#L30

**Comment by rolfeisenhut** [comment]
Is there a sample available,
covering all required steps for configure the Headers..

Regards Rolf

**Comment by brockallen** [comment]
Sorry -- we don't have a sample. I think mainly because that's more of an ASP.NET Core feature (so it's not specific to IdentityServer), and since that config depends on that reverse proxy or load balancer you use (different ones sometimes send along things slightly different from my understanding).
