### ISSUE TITLE
Multiple Clients, Single Browser: Unexpected Authentication Behavior

### ISSUE THREAD

**Issue by lbrunshh** [DuendeSoftware/Support#1524]
IdentityServer 7.0.8
.NET 8

I have two separate clients (with separate client ID's) that are connected to my IdentityServer. If I login with the first client I get authenticated on the first client and the IdentityServer (as expected), however when I go to login on the second client on the same browser the IdentityServer will not display any kind of login/confirmation screen and will automatically redirect me back to the client as authenticated with the same principal that I used with the first client login on the IdentityServer.

I'm not sure if this is intended behavior, but if so does Duende have a built in way to allow the user to use another principal to login with?

For example Microsoft and Google will allow the user to pick a user or choose another user as seen below:
![Image](https://github.com/user-attachments/assets/ec4da55b-b577-4687-84f8-b30d657b9d33)

If any clarification is needed please let me know, thanks.

**Comment by StuFrankish** [comment]
Hi @lbrunshh 👋

The behaviour you're seeing is completely normal and expected due to the single sign-on functionality inherent in IdentityServer.
When you authenticate with one client, the session persists across the browser, leading to automatic authentication as the same user when accessing another client without prompting for login.

To prompt a user to login, you need to set `prompt=login` as part of the authorise request.
More information here: https://docs.duendesoftware.com/identityserver/v7/reference/endpoints/authorize/#optional-parameters

For example, when configuring your client using `AddOpenIdConnect(...)`, you can configure the options with:
```csharp
// Use prompt=login to force the user to log in every time
options.Events.OnRedirectToIdentityProvider = context =>
{
    context.ProtocolMessage.Prompt = "login";
    return Task.CompletedTask;
};
```

**Comment by AndersAbel** [comment]
Stu is right that `prompt=login` will let the user login again. I would just like to point out that it will not cause multiple session in the same was as Entra ID does. IdentityServer only supports a single session at a time and logging in again will overwrite the existing session.
