### ISSUE TITLE
Database / Datastore Support

### ISSUE THREAD

**Issue by CDOS13** [DuendeSoftware/Support#159]
Can we replace SQL Server with PostgreSQL, Mongo or any other data store? I know we could develop our own, but curious if there has been any work done on this? Would prefer a Duende supported solution.

**Comment by brockallen** [comment]
Repeating my email answer here :)

We abstract the stores so you can build your own, yes. And then we have have an in-memory and Entity Framework Core implementations of that abstraction. That's basically the two levels we offer. As for other non-EF implementations, I'm not sure.

So yes, you should be able to switch to Postgres, but the real problem is moving the data. It shouldn't be too hard to connect to the old DB, read it all out, and then push it to the new DB.
