### ISSUE TITLE
BFF + React: Login/Signup pages

### ISSUE THREAD

**Issue by OlegPanagushin** [DuendeSoftware/Support#185]
Hello, 
Maybe it's a stupid question, but it's not clear for me, if i implement a BFF SPA application with the following projects structure: 
* IdentityServer
* BackendApi 
* Front Host with React

where should be implemented Login/Signup pages, could they be implemented on React App or they must be part of the IdentityServer?

**Comment by brockallen** [comment]
That's an architecture questions, and so it's really up to you. It's common to have those co-hosted in your IdentityServer (since it would have access to the identity system), but you could also do that in the client apps but they'd need to somehow be able to write to the identity system, either by direct access or some API call.

**Comment by OlegPanagushin** [comment]
Approach when identity stuff stays on IdentityServer side looks more organic, but it's more complicated to frontend team to maintenance, since it's another project. That's why i'm looking solution how to keep all frontend in Fronthost app. 
Could you please give me a cue how i should configure IdentityServer to achieve it?

**Comment by brockallen** [comment]
>  Could you please give me a cue how i should configure IdentityServer to achieve it?

There's no magic -- build pages that create a new user record in the identity database. Unless I'm missing something?

**Comment by OlegPanagushin** [comment]
In my head it was way more overengineered 😀
Thanks @brockallen
