### ISSUE TITLE
Running Blazor WASM Hosted app with authentication managed by BFF in docker-compose

### ISSUE THREAD

**Issue by roby70** [DuendeSoftware/Support#194]
I'm using Duende BFF package 1.2.3 in a Blazor (.NET 6) web assembly application hosted as described in [quickstart documentation for IdentityServer 6](https://docs.duendesoftware.com/identityserver/v6/quickstarts/7_blazor/).

The problem is that the solution is based on microservices and for development purposes I use docker-compose orchestration.
When I set Authority option for OpenId I must specify docker internal address in order to let server side to communicate with identity server API. 

`options.Authority = "https://identity_api:443";`

This allow the web application to discover the service and call the login page, but the client at this point is redirected to `https://identity_api/connect/authorize...` that is not visible by the browser since it is only an internal docker address.

I need to redirect the client to the mapped port (e.g. `https://localhost:7093/connect/authorize...`).

If I browse the address `https://localhost:7093/` IdentityServer api respond with the correct UI.

I've tried to set Authority option to "https://localhost:7093" but in this way the application can't discover the configuration since it works in this phase internally to the docker network.

**Comment by brockallen** [comment]
This is a typical problem with containers.

The real solution is to have a proper DNS server, since the identity of the token server is based on the DNS host entry that clients use to connect to it.

A workaround would be to se the `IssuerUri` property on the [options](https://docs.duendesoftware.com/identityserver/v6/reference/options/#main) to force IdentityServer to use that host name, rather than some internal IP.
