### ISSUE TITLE
How BFF user session renew works?

### ISSUE THREAD

**Issue by LilitHakobyan** [DuendeSoftware/Support#243]
Hello

I am using IdentityServer  6.1.1 and  Duende BFF  1.2.3 with  YARP 1.2.3 .
Project is.NET6 with React.

I have these configs for the BFF cookie.
```
                    // set session lifetime
                    options.ExpireTimeSpan = TimeSpan.FromMinutes(15);

                    // sliding expiration
                    options.SlidingExpiration = true;
```
Referring to documentation that says 
"If your backend uses sliding cookies, you typically want to avoid that querying the session will extend the session lifetime.
Also, i read that the querying should be half time passed  the expiration window to be able to extend the session.
This means if I do request GET bff/user in the above conditions that will extend the session.

But during my experiments I saw that the user session renewed automatically when half time passed without calling any BFF or other endpoints. 

So my question is 
How is the BFF user session renewed process working? 
Is it possible that  BFF session renewal also renews the identity server session?
Hows the BFF user session happens when the Identity server session is expired?

Thanks)

**Comment by brockallen** [comment]
There are two "sessions" in the BFF scenario. One is the cookie that is controlled by the Microsoft cookie handler (added with AddCookieAuthentication), and the other is the "session" for the access and refresh tokens. 

The access token renewal happens when your BFF code need to use the access tokens, either manually or with automatic calls into a remote API.

I think you're mainly asking about the cookie. So yes, any requests into the BFF host might trigger the cookie session to be extended from the Microsoft code controlled by your `ExpireTimeSpan` and `SlidingExpiration` setting above. This could be AJAX calls or BFF endpoints, but could be for loading the page, favicon, CSS, etc. (depending on your BFF host middleware pipeline). 

>  How is the BFF user session renewed process working?

So in your tests, were other endpoints in the BFF host being executed that might cause the Microsoft code to slide the cookie session?

>  Is it possible that BFF session renewal also renews the identity server session?

Not unless you have other things configured such as the IdentityServer server-side sessions and user activity monitoring enabled: https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/inactivity_timeout/#user-activity-monitoring

>  Hows the BFF user session happens when the Identity server session is expired?

Unrelated, unless you do more things to configure them to be coordinated https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/inactivity_timeout/#user-inactivity-detection-and-session-termination

**Comment by LilitHakobyan** [comment]
Thanks for the details.  

> The access token renewal happens when your BFF code need to use the access tokens, either manually or with automatic calls into a remote API.
Do the access token renewal happens through the  Identity server or it also not connected and needs to be config manually?

> So in your tests, were other endpoints in the BFF host being executed that might cause the Microsoft code to slide the cookie session?
Yes if the half time passed in the expiration window.

So am I got right that BFF gets the access token from IdentityServer and saves the token, creates the session controlled by the Microsoft cookie handler, and further management of the access token and the cookie is done through the BFF middleware (if there are no special configs )?

**Comment by brockallen** [comment]
> Do the access token renewal happens through the Identity server or it also not connected and needs to be config manually?

When you use [our APIs](https://docs.duendesoftware.com/identityserver/v6/bff/tokens/) to get the access token or forward calls to a remote API, the BFF helpers will use the refresh token if necessary (if you have one). And yes, since all the tokens come from your IdentityServer, then that's what's contacted to renew the access token (that's how OAuth work).

> Yes if the half time passed in the expiration window.

So if you access anything from the BFF host, then it would make sense that the cookie is renewed.

> So am I got right that BFF gets the access token from IdentityServer and saves the token, creates the session controlled by the Microsoft cookie handler, 

Yes, that's correct.

> and further management of the access token and the cookie is done through the BFF middleware (if there are no special configs )?

The cookie is still managed by the Microsoft cookie handler, but the BFF layer might request the cookie to be updated when a new access token is obtained via renewal. So the BFF layer can cause new cookies to be issued.

**Comment by LilitHakobyan** [comment]
Thanks for the detailed responses.
