### ISSUE TITLE
Documentation for Testing with BFF

### ISSUE THREAD

**Issue by jimmytricks** [DuendeSoftware/Support#251]
Hi folks,

Apologies if this is not the right place but could I request some documentation around testing, particularly how to configure an end to end test such as Cypress, so that it can programmatically login through IdentityServer with an Asp.Net web app using BFF. There is little to no information I can find to assist with this, and with testing such a core part of development it would be great to have some official pointers. Thanks very much!

**Comment by brockallen** [comment]
Sorry, I don't know those testing frameworks well enough to give any guidance. For our testing, we've built our own style that you can see below. The link is to our BFF tests since those are newer/cleaner than our older IdentityServer ones, but the same general approach applies:

https://github.com/DuendeSoftware/BFF/tree/main/test/Duende.Bff.Tests

We have in-memory hosts:

https://github.com/DuendeSoftware/BFF/tree/main/test/Duende.Bff.Tests/TestHosts

And then load them and run various endpoints and run requests against them:

https://github.com/DuendeSoftware/BFF/blob/main/test/Duende.Bff.Tests/Endpoints/LocalEndpointTests.cs#L20

So this isn't approach does really use any off-the-shelf testing framework. Sorry I don't know more for you. At some point we'd love to have samples for load tests (like JMeter), but we just hasn't had time (but it's on our list).

**Comment by jimmytricks** [comment]
Hi @brockallen 

Thanks very much for the prompt reply, hugely appreciated. I have (gulp!) written a Stack Overflow question which I'll link here in case it gets answered and others have a similar question: https://stackoverflow.com/questions/73962307/how-to-run-cypress-end-to-end-test-with-identityservers-authorization-code-flow

Thanks for sending through the examples, in terms of what I was hoping to test would be more of an end to end / acceptance test. Cypress allows you to mock/intercept a login request and return something back, so ultimately I think the question is trying to work out a way where we can call identityserver and return this result as part of this mocked reply from Cypress, and then have this be passed into BFF.

I'm currently using the authorization code flow to login and the current route I'm exploring to get these tests working is to add a password grant type solely for this purpose (only on our non production environments), and then have Cypress make the api call to login with the password grant type. Hoping that from this we can get back the ID and Access Tokens, but then figuring out how to pass these into BFF / Session management is where I'm a little unsure.

Hopefully that makes sense, and if you do have any pointers or ideas would be hugely helpful.

Thanks and great job on an awesome product!

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
