### ISSUE TITLE
How to  do zero downtime hot swap Azure Web App slots

### ISSUE THREAD

**Issue by ttkaine** [DuendeSoftware/Support#262]
We are trying to make a zero downtime deployment process using Azure WebApps.

We do the actual deploy to an application slot which is not the live production slot. This slot has its own URL in the format:

mywebapp-staging.azurewebsites.net

We then run this application to test the deployment has been successful.

The next step is to swap this running application with the one currently in the production slot. This, in effect, just swaps around the URLs on the two running applications.

However, this turns out to be a problem when using Identity Server because the running application caches the URL somewhere. This means that after swapping the slots over the production site, which is running on a public facing URL, like www.myapp.com, the server then only accepts security tokens and cookies from the staging url mywebapp-staging.azurewebsites.net. This results in 401 errors for web services calls. 

The client application doesn't know that the server has changed and as far as the client is concerned it has a valid token for the same URL and so it doesn't ask the user to log in again - it just gets locked out of the API until the user refreshes the application. 

The brute force solution to this issue is to manually restart the application directly after swapping the slots in Azure - however, this means it is no longer possible to do a zero downtime deployment because there's a window between the swap completing and the restart of the application being complete where the client application is in a broken state. 

What is the best practice way to resolve this issue? Is there a way to prevent Identity Server caching the url? Or a way to flush that cache when swapping slots without restarting the application?

**Comment by leastprivilege** [comment]
Are you saying that

`mywebapp-staging.azurewebsites.net`

is the web app containing IdentityServer - or a client application?

**Comment by ttkaine** [comment]
In this case it's a asp.net core web application with a Blazor Web Assermbly component. 

mywebapp-staging.azurewebsites.net is the host url of the asp.net web application on the staging slot

**Comment by ttkaine** [comment]
This project has been built with the template provided by Microsoft for a Blazor Web Assembly hosted by a .net Core webapp. It comes with Identity Server included as part of the template.

**Comment by brockallen** [comment]
Do both these slots point to the same DB and have access to the same data protection keys?

**Comment by ttkaine** [comment]
Yes. The two slots have identical configuration (with the exception of the inbound url). They use the same DB and have the same app settings and access to the same services.

**Comment by brockallen** [comment]
You can set the `Issuer` option to tell your IdentityServer that it's physical host isn't important, and instead it should always use that value (the public/real host name you use). This will allow your staged instance to create tokens for your production one, though.

**Comment by brockallen** [comment]
> To clarify, this would be adding the IssuerUri option in the startup like this?

Yep, but I'm still not sure what you ran into here. I'm not sure why the staging instance, once swapped to prod, still thought that it was the staging URL. You might need to dig into the layers more and find the specific place that failed and with the error explaining it.

Your app is the one created via the MS template, so it has a SPA, ASP.NET Identity, and IdentityServer. You have a user using the prod instance, then the staging gets swapped into prod and you want that user to keep working. The only time the staging instance is used it to do a test.

As for cookies, and the staging slots -- cookies are not shared across host boundaries, unless you set the domain flag. That's just how browsers work, but I don't see how that would matter to the end user since they're on the prod URL the whole time, right?

Maybe this azure staging slot feature just isn't the right tool for the job?

**Comment by ttkaine** [comment]
I tried setting the IssuerUri as suggested, but this has the side effect of breaking the Staging slot as tokens made from the application running in staging are then not accepted when passed from the staging client. This means it is not possibl to test the staging client before swapping it into the production slot.

I did some more tests with slot swapping and found that it is possible to allow the tokens to be shared between the staging and produciton slots by not validating the issuer at all:

`
        services.Configure<JwtBearerOptions>(IdentityServerJwtConstants.IdentityServerJwtBearerScheme,
            options =>
            {
                options.TokenValidationParameters.ValidateIssuer = false;
            });
`

Since the tokens are created using a certficate that is unique to the application and the keys are stored in Azure this seems acceptable as the token can only be created by either production or staging.

This does indicate that it is the issuer not matching the request that is the root cause of the 401.

**Comment by brockallen** [comment]
> by not validating the issuer at all

Well, that's not really ideal, as the specs require issuer validation. 

Again, given the importance of the *Issuer* I again contend that `Maybe this azure staging slot feature just isn't the right tool for the job?`.

**Comment by ttkaine** [comment]
Agreed - skipping issuer validation is not ideal - however it seems to me that if the issuer of a token is the same url as the currently running instance then the issuer validation _should_ work. The fact that it _does_ work when you skip issuer validation suggests that the validation is failing in this case - my guess is that it's caching the URI, but I'm not familiar enough with the codebase of Identity Server to know quite where it gets the URI for comparison when validating the issuer. 

When digging through previosuly I managed to find this message:

IDX10205: Issuer validation failed. Issuer: '[PII is hidden]'. Did not match: validationParameters.ValidIssuer: '[PII is hidden]' 

And turning on the PII logging showed that the staging slot URI was being picked up by the production instance as the ValidIssuer.  

Using staging slots for deploment is the microsoft recommended best practice for azure webapps and so I'm reluctant to change the deloyment pipeline if it can be avoided.

**Comment by brockallen** [comment]
I know you described the scenario in the first post above, but I need a better picture of the different moving parts. You have IdentityServer and it has 2 slots (prod/staging each at different host names).

Do you also have the client app and API hosts doing this as well? I think this is the issue -- you won't be able to get a token from the staging issuer and then use it at the prod API unless its signing keys and issuer are the same. So that's why I thought manually setting the *Issuer* in the staging instance (which is to say really setting it in both) should have worked.

**Comment by ttkaine** [comment]
From a code perspective there's one single .net core (.net 6) application hosted on an azure web app. This application is essentially a website - it serves content to a browser. It has some MVC style controllers and also some Web API controllers, all of which just use the inbuild [Authorize] attributes of .net. The Identity Server is part of this application, it's bundled up as part of the original microsoft template.

The application is hosted twice, on two different slots with different URLs (production and deployment). 

I'll see if I can explain it clearly:

- There are two running instances - A and B.  
- Both A and B - they have completed any start-up process and are awaiting clients to connect. A is serving requests to www.production.com and B is serving requests to www.staging.com
- User 1 logs into www.production.com (currently instance A of application) - they get a cookie token issued by www.production.com
- The slots are then swapped - in effect the the URLs of the two running applications are switched over. A is now www.deployment.com and B is www.production.com
- User 1 requests a resource from www.production .com API using the cookie issued to www.production.com by instance A
- Instance B is now serving requests to www.production.com and rejects User 1's request with a 401 because it is expecting the issuer to be www.deployment.com even though it's currently serving a request to www.production.com

(If the instances are restarted after the swap they then validate as expected)

Explicitly setting the IssuerUri seems to work for the production slot, but it breaks the deployement slot because the deployment slot is not running on the same url and therefore will always fail to validate the issuer.

**Comment by brockallen** [comment]
> From a code perspective there's one single .net core (.net 6) application hosted on an azure web app. 

Ahhh, ok -- I think this is it then. When it's loaded as a staging app, the API layer connects to its own discovery document (sort of silly since it's co-hosted) so it knows how to validate the access tokens. I think that might be what's getting cached. So then when you switch it to prod, the app is not re-started, so then new tokens use the new Issuer and the cached discovery document uses the old issuer. Again, this is still a (presumably educated) guess.

> it breaks the deployement slot because the deployment slot is not running on the same url and therefore will always fail to validate the issuer.

Yea, I think it's caching the staging Issuer in the API token validation layer. I'd suggest disabling the PII restriction to get more data to confirm.

**Comment by brockallen** [comment]
Any update here?

**Comment by ttkaine** [comment]
Sorry - got pulled onto something else for a bit.... I've put the pii on a setting so I can turn it on and look at the logging - will get to that asap :)

**Comment by brockallen** [comment]
I'll close for now. You can re-open later if you need to. Thanks.
