### ISSUE TITLE
How to properly config the OpenIdConnect middleware for BFF implementation to  prevent "Correlation failed" exception?

### ISSUE THREAD

**Issue by LilitHakobyan** [DuendeSoftware/Support#267]
Hello

I am using IdentityServer 6.1.1 and Duende BFF 1.2.3 with YARP 1.2.3 .
Project is .NET6 with React.
Server-side sessions are enabled for both and stores in DB.

I am getting the "Exception: Correlation failed." when I try to log in after being logged out for 20 minutes. 

Found the config RemoteAuthenticationTimeout which fix the problem
`options.RemoteAuthenticationTimeout = TimeSpan.FromDays(2);`

And also found that there is a correlation and a nonce cookie that should be configured.

So my question
Is the RemoteAuthenticationTimeout option fixes the problem, Is it a comprehensive fix?
Do I need configs for correlation and nonce cookies?
Does the BFF implementation saves the code_challange and verifier in memory or is it stored in the DB in the session ticket payload?

**Comment by brockallen** [comment]
> I am getting the "Exception: Correlation failed." when I try to log in after being logged out for 20 minutes.

This is common when a user takes too long to login (for example -- they are redirected to the login screen and then go our for lunch). The reason is that the Microsoft ASP.NET Core OIDC handler generates some correlation values and put them into a cookie in the client app, and then when the OIDC response returns to the client app the correlation cookie in the client app has expired. If you set this too big of a value, then if the client creates lots of OIDC requests you'll end up with too many cookies (it can happen). 

I recommend handling the error in the client, and prompting the user if they want to try to login again. If you re-trigger OIDC then it's likely that the user just came back from lunch and just logged in, so they will have a valid SSO session at IdentityServer.

**Comment by LilitHakobyan** [comment]
Thanks for the response.
So you are saying that the configs for correlation and nonce cookies are not a comprehensive solution, right?
And can you please refer to my other question
> Does the BFF implementation saves the code_challange and verifier in memory or is it stored in the DB in the session ticket payload?

**Comment by brockallen** [comment]
>  So you are saying that the configs for correlation and nonce cookies are not a comprehensive solution, right?

In my opinion, yes. But that's an issue with the Microsoft OIDC handler, so you will have to address it by adding code there.

> Does the BFF implementation saves the code_challange and verifier in memory or is it stored in the DB in the session ticket payload? Or is it stored in the correlation and nonce cookies?

This is not performed by our BFF -- it's the Microsoft OIDC handler. It stores some of those things in the state param and in the cookies.

**Comment by LilitHakobyan** [comment]
Thanks for the response.
