### ISSUE TITLE
How to pass custom logout parameters from bff logout to identity to be able to show the logout message in identity spa login  page?

### ISSUE THREAD

**Issue by LilitHakobyan** [DuendeSoftware/Support#284]
IdentityServer 6.1.1 and Duende BFF 1.2.3 with YARP 1.2.3 .
Project is  .NET6 with React.

We want to have the logout status and logout message in the Identity server SPA login page .
The one solution which works and is not related to either the BFF or  Identity is passing the needed data using local storage.
But this is not the best solution of course.

I am trying to implement the following 
passing the two more query params with logoutId to bff/logout endpoint
and then I need some sort of configuration to pass it to the SPA logout page from the identity 
I have this config in the Identity part 
```
options.UserInteraction.LogoutUrl = $"{IdentityConstants.IDENTITY_UI_PREFIX}/sign-out";
options.UserInteraction.LogoutIdParameter = "logout_id";
```
so with these settings also need some other setting with will pass the custom params with the logout id to options.UserInteraction.LogoutUrl

Is there any kind of designed solution for this with some sort of configuration?
Is this possible to do?

**Comment by brockallen** [comment]
> We want to have the logout status and logout message in the Identity server SPA login page .

What do you mean by this? You want the "You Are Logged Out" page from IdentityServer in the SPA, and not in IdentityServer?

**Comment by LilitHakobyan** [comment]
We have an inactivity timeout in the client UI project so in our case there are two kinds of logouts one with the Logout button which we consider a successful logout and the logout when the session expired in the client UI with the error status and different message.
After logout, we redirect the user to the Identity server spa login page and we want to see those messages there.

**Comment by brockallen** [comment]
>  After logout, we redirect the user to the Identity server spa login page and we want to see those messages there.

This might be difficult. To get to the login page in IdentityServer, the client would initiate an OIDC request which given how the nonce works has an inherent timeout. That's not what people commonly do (at least when using OIDC).

> We have an inactivity timeout in the client UI project so in our case there are two kinds of logouts

Inactivity is not really a logout, or at least when you detect inactivity I would not suggest triggering OIDC logout. The reason is that the user might be inactive because they have 2 tabs open to 2 different client apps. The inactive one, if it forced OIDC logout due to inactivity, would cause the other to be logged out. Not very user friendly. 

>  After logout, we redirect the user to the Identity server spa login page and we want to see those messages there.

There's nothing in OIDC that is designed for that. Normally you'd just show this in the client app itself.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
