### ISSUE TITLE
Use identityserver methods in web api 

### ISSUE THREAD

**Issue by soufianelb** [DuendeSoftware/Support#291]
Can someone help me,
I am using identityserver for authentication and autohrization
Now i want to delete a user from my web api, so how can i use identityserver methods in my web api (external)
Should i call to identityserver or what ...

**Comment by brockallen** [comment]
>  Now i want to delete a user from my web api, so how can i use identityserver methods in my web api (external)

Your API would need to contact whatever system you use to manage your users to perform that operation. So that might mean either your API connects directly to your database, or you build an API on top of your user system to do that. 

User management is an extensibility feature of IdentityServer, so it's not built-in or part of the product.

**Comment by josephdecock** [comment]
I'm closing this thread as it appears to be answered and hasn't seen activity in a week. If you need more help feel free to reopen this issue or create a new issue. Thanks!
