### ISSUE TITLE
How to support centralized user timeout across multiple clients using IdentityServer?

### ISSUE THREAD

**Issue by acasciani** [DuendeSoftware/Support#292]
**Which version of Duende IdentityServer are you using?**
6.1.7

**Which version of .NET are you using?**
Core 6

We are looking for some Duende best practices and clarification on how to implement global application timeout using IdentityServer based on the documentation. 

By global application timeout, I mean a setup like the following:

- 1 IdentityServer
- 2 completely independent client applications  (Client A & Client B)
One could be on a Blazor WebAssembly stack, the other on a MVC or Web Forms stack 
- Client A and Client B use the IdentityServer for auth
- The user’s inactivity time is 30 minutes. After this time, they are required to login again to the IdentityServer.

Given this setup, the user starts on Client A and opens a new tab (same browser session) for Client B. 

**Scenario 1**: The user does not interact with Client A for an hour, but has been interacting with Client B within the last 5 minutes. Their activity flag shows them as **active**. They go back to Client A and when a new access token is requested, it is granted because they are still active (due to activity on Client B).

**Scenario 2**: The user does not interact with Client A for an hour, and does not interact with Client B for an hour. Their activity flag shows them as **inactive**. They are logged out (or a refresh token request fails) of both Client A and Client B because they are inactive.

It looks like supporting this type of use case may fall under Duende’s [**Inactivity Flag**](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/inactivity_timeout/) and [**Server-Side Sessions**](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/).

On both links above, it states "_the ability to centralize and monitor session activity in order to achieve a system-wide inactivity timeout_" and "_A common requirement in several industries is the concept of a system-wide 'inactivity timeout'_". 

1. Are scenarios 1 and 2 above, what you define as "_system-wide inactivity timeout_"? Or does that mean something different in IdentityServer?

Under the [**Design**](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/inactivity_timeout/#design) section of **Server-Side Sessions**, it states "_To achieve the goal of distributed session management, there must be a single record tracking the user’s session._"

2. In this case is distributed session management referring to sessions across multiple applications (clients), or sessions across the IdentityServer within a load balanced environment (i.e. multiple servers)?

Thank you!

**Comment by brockallen** [comment]
> We are looking for some Duende best practices and clarification on how to implement global application timeout using IdentityServer based on the documentation.

OIDC is not designed for this requirement. But, as hinted at [here](https://blog.duendesoftware.com/posts/20220406_session_management/), if you can centralize the session management and that central point is OIDC/OAuth aware (meaning client and token aware), then you can architect something that uses several of these different moving parts to achieve this requirement. This is what our server-side session and session coordination features are designed to help with. There is certainly planning needed to design for this, though (both in the IdentityServer and in the client apps).

As documented [here](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/inactivity_timeout/#user-activity-monitoring) our user activity monitoring will extend the user's server-side session at IdentityServer when they are active in any client app (due to refresh token or introspection activity). This means their session at IdentityServer is extended (in the serer-side session store). So then when their local session at ant one client expires and that client naturally re-initiates an OIDC request they do not have to login again (due to SSO).

> Are scenarios 1 and 2 above, what you define as "system-wide inactivity timeout"? Or does that mean something different in IdentityServer?

Scenario 1 is triggering the user activity monitoring so that when Client A re-triggers OIDC the user does not need to login again due to SSO. Scenario 2 is handled by our [session expiration monitoring](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/session_expiration/) by which sessions that have not been active are then expired, which is to say the server-side session record is deleted.

> In this case is distributed session management referring to sessions across multiple applications (clients), or sessions across the IdentityServer within a load balanced environment (i.e. multiple servers)?

This means the server-side session record at IdentityServer.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
