### ISSUE TITLE
Supporting basic authentication header(Rfc2617) in AccessTokenManagement.ClientCredentialsTokenEndpointService

### ISSUE THREAD

**Issue by bulat30** [DuendeSoftware/Support#306]
Is it possible to support basic authentication header(Rfc2617) in ClientCredentialsTokenEndpointService? We can configure ClientCredentialsClient.ClientCredentialStyle for using AuthorizationHeader, but it always uses BasicAuthenticationHeaderStyle.Rfc6749.
Would be great to add ClientCredentialsClient.BasicAuthenticationHeaderStyle configuration

**Comment by josephdecock** [comment]
If you read the spec, OAuth actually requires that credentials be url encoded. The IdentityModel client library includes the option to not url encode but that is only intended  for backwards compatibility with token providers that aren't expecting url encoded parameters. 

Do you have a use case in mind?

**Comment by bulat30** [comment]
What king of use case do u mean? Not sure that i understand the last question :/
I have integrations with token providers that aren't expecting url encoded parameters

**Comment by josephdecock** [comment]
The BasicAuthenticationHeaderStyle configuration option was originally created in the IdentityModel library as a work-around for dealing with providers that didn't comply with the spec wrt encoding the auth header. In fact, early versions of IdentityServer didn't expect url encoded auth headers, though that was fixed years ago. It's now been so long since that was fixed that we don't think it is necessary to include the option in the new AccessTokenManagement api. 

Our assumption is that providers at this point should be following the spec correctly, and we think the benefit of a simpler API surface outweighs supporting badly behaving providers. So, we probably won't add BasicAuthenticationHeaderStyle to the AccessTokenManagement API. Nevertheless, we're interested to know which providers don't expect url encoded auth headers. That's what I mean by use case - which providers aren't following the spec?

**Comment by josephdecock** [comment]
Any update on this?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if you want to discuss further.
