### ISSUE TITLE
[Feature Request] Option to decouple from .NET SPA integration

### ISSUE THREAD

**Issue by pdevito3** [DuendeSoftware/Support#311]
Hey guys, what are your thoughts on adding the capability to optionally decouple our BFF from the built in .NET SPA integration? 

In other words, not needing to have the SPA we’re using in our .NET app at all. Instead, we’d just have a standalone .NET app acting as our BFF that can be deployed alongside any SPA. All the normal interactions would still occur, but we’d have more flexibility and be able to lean into strengths of each platform without the current pain points around integration. 

The main motivator behind this for me is that as much as I love .NET, its interactions with the JS ecosystem need a good bit of gymnastics and can be very limiting at times.

By removing this dependency, we’d be able to focus on building the BFF portion in .NET land (which you guys abstract out super well) and also be able to focus on the strengths of our SPAs on that side of things.

Happy to clarify anything or bounce ideas if it would help. Thanks!

**Comment by josephdecock** [comment]
I think this is already possible. If you had a node process hosting your front end, a dotnet process hosting a bff for it, and a reverse proxy routing requests properly to the two, I think that would work today. The key thing is that the two processes need to be on the same domain and share cookies.

@leastprivilege - are there any other considerations that I'm forgetting here?

**Comment by pdevito3** [comment]
Thanks, @josephdecock

> If you had a node process hosting your front end, a dotnet process hosting a bff for it, and a reverse proxy routing requests properly to the two

If this is the case, an example would be great to see. 

FWIW, it would be nice to not even need the reverse proxy and just be able to call the BFF from the SPA and have it do it's normal proxying to the api that way.

**Comment by josephdecock** [comment]
I think you need a reverse proxy because the two hosts can't both listen on the same port of the same domain.

In order for the front end to authenticate with a cookie issued by the back end, you need the front and back ends to have the same domain and be differentiated by path. For example, the front end host would serve requests to https://example.com/app and the bff host would serve requests to https://example.com/bff. But you can't attach both hosts to port 443 on example.com, so if you set it up this way, you would need something in front of both hosts to route traffic.

You **might** be able to avoid that by putting the bff on it's own port, e.g., https://example.com:44321/bff (with no particular significance to 44321, I just picked it "randomly"). Cookies aren't normally isolated by port, so I **think** browsers would probably send the cookies properly from the front end to the bff, **but** I don't know for certain if every browser will do that. I would be a little worried that browsers that block 3rd party cookies might block this cookie now or in the future. I don't want to have to worry about that, and most of the time the systems I work on already have a reverse proxy for load balancing, so I'd just use that.

**Comment by pdevito3** [comment]
Roger. This is interesting and good to know. 

I'll try and get something together for this myself, but I do think this would be a useful sample as I bet lots of teams would like to avoid the built .NET:JS integration pain if possible.

**Comment by josephdecock** [comment]
Cool, thanks for a good discussion. It's always helpful to know what samples folks are looking for. Honestly it sounds like something that would be great for a blog post from "someone" in the community. 😉

**Comment by leastprivilege** [comment]
> FWIW, it would be nice to not even need the reverse proxy and just be able to call the BFF from the SPA and have it do it's normal proxying to the api that way.

Isn't that just the "normal" way of doing it? e.g.

https://docs.duendesoftware.com/identityserver/v6/samples/bff/#javascript-frontend

**Comment by pdevito3** [comment]
> Isn't that just the "normal" way of doing it?

No that still has the frontend wrapped in a .NET project in a .NET app. I want to have a SPA that's not directly in a .NET project at all. Instead, the SPA is separate and deployed alongside the .NET BFF, so you still get the benefits of the BFF without having to deal with .NET integrations to JS.

**Comment by josephdecock** [comment]
One thing to note is that you can host static content from an ASP.NET host without the .NET integrations to js (like the spa proxy). That's actually what our quickstart docs do. Granted, the quickstart isn't using any js framework and doesn't need a build step for javascript, but in theory you could build the front end, outputing build artifacts into your ASP.NET host's static content directory. I haven't actually tried that myself - perhaps that would be part 2 for ~your~ someone's blog.

**Comment by pdevito3** [comment]
@josephdecock you were right, reverse proxy works just fine :-)

and i even did a blog writeup for it! https://wrapt.dev/blog/standalone-duende-bff-for-any-spa
