### ISSUE TITLE
Calling Duende as external service from Azure APIM API policy 

### ISSUE THREAD

**Issue by tomfanara** [DuendeSoftware/Support#315]
**Which version of Duende IdentityServer are you using?**

version 6.1.7

**Which version of .NET are you using?**

.Net 6

**Describe the bug**

How can I call my Duende server from a APIM API Gateway policy external call? as in this snippet 

	<set-variable name="token" value="@(context.Request.Headers.GetValueOrDefault("Authorization","scheme param").Split(' ').Last())" />
	
	<send-request mode="new" response-variable-name="tokenstate" timeout="20" ignore-error="true">
		<set-url>http://myduendeserver/connect/authorize</set-url>
		<set-method>POST</set-method>
		<set-header name="Authorization" exists-action="override">
			<value>basic dXNlcm5hbWU6cGFzc3dvcmQ=</value>
		</set-header>
		<set-header name="Content-Type" exists-action="override">
			<value>application/x-www-form-urlencoded</value>
		</set-header>
		<set-body>@($"token={(string)context.Variables["token"]}")</set-body>
	</send-request>

I'm getting an error when calling http://mydeundeserver/connect/authorize

Steps to reproduce the behavior.

**Expected behavior**

return a json object

**Log output/exception with stacktrace**

NA

```
data
```
NA
**Additional context**

**Comment by brockallen** [comment]
> APIM API Gateway policy external call

Assume we don't know what this is. Can you please explain what you're trying to do?

> I'm getting an error when calling http://mydeundeserver/connect/authorize

This is the one bit I can confidently comment on here -- the OIDC protocol expects an interactive user in a browser to be making requests to the authorize endpoint, not programmatic ones. So I'm guessing there's a mismatch in your expectations and how the OIDC protocol works (as implemented by IdentityServer). 

I think it would help for a high level description of what you're trying to do. Thanks.

**Comment by tomfanara** [comment]
Hello sorry for being unclear. We are trying to use Duende at APIM API Gateway level to protect endpoints behind the gateway. Could be a BFF microservice or other microservice. Azure APIM API Gateways have inbound policies per Operation as in GET, POST and PUT calls that can be created to do many things but in the case we want to use Duende to simply authorize an incoming token from a client or mocked client for now. The specification for this is at https://learn.microsoft.com/en-us/azure/api-management/api-management-sample-send-request.

The prior code snippet was my first attempt. The response object should be JSON with a boolean Active field returning true or false.

So I need support on how to code or the URL and other settings to make an auth request to our Duende server. I cannot find anything on line.

**Comment by josephdecock** [comment]
IdentityServer supports standards based protocols like OAuth and OIDC. One goal of such standardization is that any platform can support the protocol, and indeed that is the case - there are a huge number of platforms that implement these specs. That does mean that we don't always have an example of, or much experience with, setting up a client on a particular platform - APIM being one example. So my answer to your question (how to call IdentityServer from APIM) is, make http requests to it, following the OAuth and OIDC specs that we support.

Sorry that we can't be more immediately helpful, but the APIM layer is kind of obscuring what you're doing (at least to me, because I don't know APIM). If you can eliminate that and talk to us in terms of the protocols ("I configured IdentityServer with options x, made a call with parameters y, got surprising results z") we'll be much more able to help you.

**Comment by tomfanara** [comment]
Hello Joseph, Thanks so much. I will research the specification for http communication with IdentityServer as per OAuth and OIDC and redefine my support need(s). Thanks agan!

**Comment by josephdecock** [comment]
Sounds good. Feel free to open new issues of you have more questions.
