### ISSUE TITLE
When do we need IResourceStore.FindApiResourcesByNameAsync implementation?

### ISSUE THREAD

**Issue by arisliang** [DuendeSoftware/Support#320]
**Which version of Duende IdentityServer are you using?**
6.1.7

**Which version of .NET are you using?**
6.0

I try to implement `IResourceStore` for `AddResourceStore` for jwt access token by scope and resource. I find that even without `IResourceStore.FindApiResourcesByNameAsync` implementation, the access token by scope is no issue. (Not sure if it's related, but access token by resource is not working, the error says "invalid scope".)

So in what scenario is the `IResourceStore.FindApiResourcesByNameAsync` implementation needed?

**Comment by josephdecock** [comment]
One of the main ways IdentityServer uses FindApiResourcesByNameAsync is when tokens are requested [with a resource indicator](https://docs.duendesoftware.com/identityserver/v5/fundamentals/resources/isolation/). That's probably why you're getting an invalid scope error.

**Comment by arisliang** [comment]
Seems `resource isolation` is a enterprise feature, not for community version, so this means `FindApiResourcesByNameAsync` is not needed to implement for community version, right? That would make sense.

**Comment by josephdecock** [comment]
Resource Isolation is an enterprise feature, but there are non-enterprise features that rely on the resource abstraction as well. For example validation of reference tokens requires that you define your resources and give the resources secrets so that they can authenticate. My recommendation is, if you're implementing a resource store, implement the full interface.

**Comment by arisliang** [comment]
Thanks for the clarification, will implement the full interface as suggested.
