### ISSUE TITLE
Can IS4 produce encrypted tokens from its endpoints?

### ISSUE THREAD

**Issue by andreuwz** [DuendeSoftware/Support#324]
I am interested in token encryption, since I want to improve the security of my app.
The problem is that I want my Angular Front End to issue new access token via refresh token and store it as a cookie. But the problem is that if I encrypt the cookie using some Angular library, there is no proper place to store my security keys.
And I want to "somehow" move (abstract) the whole process using the identity server.
Also, I need to de-crypt the tokens in a different API (since it is an API Gateway), where IS is not installed. Is this possible?

So is there a built in mechanism, so that IS4 can produce pre-encrypted tokens which I can safely store on the front end?
I read the info in here [https://docs.duendesoftware.com/identityserver/v5/fundamentals/keys/](url) , but I am still not sure if there is such functionality.

**Comment by josephdecock** [comment]
The documentation that you're linking to is to do with managing key material needed for _signing_ tokens. IdentityServer typically creates signed tokens, but it never encrypts tokens. This means that you're protected from an attacker creating fraudulent tokens, but if someone steals one of your tokens, they will be able to read its contents. 

It's not usually worthwhile to encrypt tokens. Encryption would prevent an unauthorized party who was in possession of a token from reading that token, but if an attacker has your token, you're already compromised. Access tokens provide authorization to protected resources just by the fact that you have the token. An attacker who steals your token doesn't need to read the token, they can just present it to a protected resource and thereby gain access to that protected resource. So, you don't really gain much by encrypting the token. 

Instead of encrypting the token, it typically is more useful to put resources into preventing exfiltration of tokens in the first place or to preventing stolen tokens from being used by an attacker. Things you can do to prevent exfiltration of tokens include following the [OAuth Security Best Current Practice](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics), and [preventing javascript from having access to your security tokens](https://docs.duendesoftware.com/identityserver/v6/bff/overview/). You can further protect your system by preventing stolen tokens being used by [binding the token to the intended client](https://docs.duendesoftware.com/identityserver/v6/tokens/pop/).

> The problem is that I want my Angular Front End to issue new access token via refresh token and store it as a cookie. 
Your front end does not issue tokens. That's the job of IdentityServer. Your front end can use the refresh token to obtain a new token from IdentityServer.

>Also, I need to de-crypt the tokens in a different API (since it is an API Gateway), where IS is not installed. Is this possible?
We've already talked about how you're not going to be encrypting the tokens. What the API should do instead is validate the signature of the token using the public key material used to sign the token and published by identity server. You can configure the JWT bearer authentication middleware to use IdentityServer as its Authority, and then it will do this signature validation for you.
