### ISSUE TITLE
asp identity

### ISSUE THREAD

**Issue by A-Yavari** [DuendeSoftware/Support#325]
Can we not use asp identity?  I want to give user information to the identity server through an api

Can you, please, give me a hint how to write IdentityServer with custom user&password dbo tables?

**Comment by josephdecock** [comment]
IdentityServer's integration with ASP.NET Identity is optional. We allow you to authenticate users however you like. Please see here in the docs: https://docs.duendesoftware.com/identityserver/v6/fundamentals/users/. We also have a quick start tutorial where we show how to set up authentication of interactive users: 
https://docs.duendesoftware.com/identityserver/v6/quickstarts/2_interactive/. That tutorial uses an in memory set of example users (and not ASP.NET identity). Instead of the in memory users, you can get user info from whatever data store you like.

**Comment by josephdecock** [comment]
Closing, but feel free to open a new issue is you have follow up questions.

**Comment by A-Yavari** [comment]
Thanks a lot
