### ISSUE TITLE
Azure APIM Integration with Duende (Identity Server) as an inbound policy on an API operation

### ISSUE THREAD

**Issue by tomfanara** [DuendeSoftware/Support#328]
**Which version of Duende BFF are you using?**

6.1.7

**Which version of .NET are you using?**

.NET 6

**Describe the bug**

Not a bug looking for some direction in terms of support. We have read your documentation and implemented a simple auth on a backend with in a asp.net controller but not at the gateway on an inbound policy.

The use case is securing backend resources or microservices at api gateway level per rest operation before sending token on to the service layer or microservices.

We feel this gives us additional protection before ever hitting the services although redundant.

I've searched extensively but found no support on the above subject "Azure APIM Integration with Duende (Identity Server) as an inbound policy on an API operation"

Here's what we are trying to accomplish.

For now, we are successfully getting a token from Duende with a client id and client secret
Using postman as a mocking UI client and adding the Bearer token and posting to an APIM API to Duende to get authorization to designated backend microservices
We want to add a policy inbound fragment as a way of authorizing backend resources
Based on response from Duende we can redirect in the policy code
Has anyone coded this for Identity Server 4 or Duende and Azure APIM?

We have tried a simple GET to Duende using the following policy on an inbound operation. Since the token now contains the client_id we assume no need to send it again to authorize?

Steps to reproduce the behavior.

just some basic code steps to make a request to Duende

<set-variable name="token" value="eyJhbGciOiJS......." />
    
    <send-request mode="new" response-variable-name="tokenstate" timeout="20" ignore-error="false">
        <set-url>http://myidentityserver/connect/authorize</set-url>
        <set-method>GET</set-method>
        <set-header name="Authorization" exists-action="override">
            <value>@($"Bearer {(string)context.Variables["token"]}")</value>
        </set-header>
        <set-header name="Content-Type" exists-action="override">
            <value>application/x-www-form-urlencoded</value>
        </set-header>
    </send-request>

to get a response either 401 or an access code

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
What are you trying to accomplish with your call to identity server? It doesn't make sense to send a token to the authorize endpoint-the endpoint's purpose is to start a flow that sends a token to the client application. It isn't expecting a token at all, and if you already have a token, you don't need the endpoint anyway.

**Comment by tomfanara** [comment]
We want to verify the bearer token passed in from the client or in our case postman as a mocking client is a valid token. Thus preventing any penetration before entering our micro services backend. This is commonly done at ingress or API gateway infrastructure.

Can you explain what endpoint we would use and what other values we have to pass in?
________________________________

**Comment by josephdecock** [comment]
IdentityServer can create two different formats of tokens - JWTs and reference tokens. JWTs are the default, and easier to validate. I'm assuming your token is a JWT. To validate a JWT, you validate its signature and the claims within it.

JWTs are just a chunk of JSON that has been cryptographically signed with an asymmetric key - that is to say, there is a secret key that is used to create the signature that IdentityServer manages, and a corresponding public key that can be used to validate the signature. The public key is made available by identity server through the discovery endpoints. For example, https://demo.duendesoftware.com/ is our demo identity provider built with IdentityServer. It publishes a metadata document at https://demo.duendesoftware.com/.well-known/openid-configuration (which follows the OIDC discovery protocol).  In the metadata, there is another url to the JWKS (JSON Web Key Set, which is the public keys for the signatures) - https://demo.duendesoftware.com/.well-known/openid-configuration/jwks. So, to validate a token, you retrieve the JWKS, following these urls, use the public key material to validate the signature of the JWT, and then inspect the claims, validating their values as per whatever requirements you may have. But, you don't actually have to write code to do all of that. Most platforms, including, I believe, APIM, already have tools in place to do this for you. I don't know much about APIM, but I found [this in their docs](https://learn.microsoft.com/en-us/azure/api-management/api-management-access-restriction-policies#ValidateJWT). The examples there, especially the ones that instead of specifying signing keys just mention the oidc configuration look promising to me.
