### ISSUE TITLE
/bff/login and /silent-login endpoints produce erroneous requests when accessing the website through azure front door

### ISSUE THREAD

**Issue by eugene-rebedailo** [DuendeSoftware/Support#335]
**Which version of Duende BFF are you using?**
v1.2.3
**Which version of .NET are you using?**
6.0
**Describe the bug**
When running BFF solution behind the azure front-door, signin handler fails to produce the redirect URI that would be visible to the outside world. Redirect URI for the remote authorization pointing at the /signin-oidc is pointing at the internal azure hostname and not the hostname that was requested.

**To Reproduce**
1) Host the BFF-solution on an azure app service. Restrict access to the app through it's private *.azurewebsites.net address
2) Setup the azure front-door to expose the BFF via a public hostname, making it accessible only via its front door hostname.
3) Try signing into the app by accessing /bff/login managed endpoint
4) Note the redirect_uri query parameter on the /authorize request that was produced. The hostname of the redirect_uri is matching the private azure hostname of the api, not the public hostname setup in the front door.
5) Browser is being redirected to the private azure hostname with the authorization_code and is failing to reach it.

When attempting the silent-login, similar issue is happening inside the iframe.

**Expected behavior**
Browser is redirected onto the publicly accessible hostname, that was used to reach the server to initiate the sign-on.

**Log output/exception with stacktrace**

N/A

**Additional context**
N/A

**Comment by josephdecock** [comment]
It sounds like you need to use the ForwardedHeaders middleware so that your identity server knows about the front door. We have some documentation [here](https://docs.duendesoftware.com/identityserver/v6/deployment/proxies/).

**Comment by hrjjml** [comment]
@eugene-rebedailo can you please post the rest of your changes aside from adding app.UseForwardedHeaders().
I have the same issue with Front Door, my ids app is using RSK SAML and it's failing the request validation because the app can't figure it out that it belongs to the custom domain.


2023-11-07 18:51:09.775 +00:00 [ERR] NACD.IDS.Core.SAML.SamlSingleSignOnRequestValidatorDecorator
SamlSingleSignOnRequestValidatorDecorator.Validate: Invalid SAML Request
Invalid SAMLRequest Destination
Received message destination: 'https://<app custom domain>/saml/sso'. Expected: 'https://<azureapp>.azurewebsites.net/saml/sso'
