### ISSUE TITLE
Authorize Callback throws exception when querying PersistedGrants

### ISSUE THREAD

**Issue by pbros** [DuendeSoftware/Support#338]
**Which version of Duende IdentityServer are you using?**
6.1.7

**Which version of .NET are you using?**
6.0.402

**Describe the bug**
In our logs, we saw the following error but do not know the cause

 Failed executing DbCommand ("0"ms) [Parameters=["@__token_Key_0='?'"], CommandType='Text', CommandTimeout='30']"
""SELECT p.\"Id\", p.\"ClientId\", p.\"ConsumedTime\", p.\"CreationTime\", p.\"Data\", p.\"Description\", p.\"Expiration\", p.\"Key\", p.\"SessionId\", p.\"SubjectId\", p.\"Type\"
FROM \"PersistedGrants\" AS p
WHERE p.\"Key\" = @__token_Key_0"

An exception occurred while iterating over the results of a query for context type '"OURNAMESPACE.Identity.Admin.EntityFramework.Shared.DbContexts.IdentityServerPersistedGrantDbContext"'."
""System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.Exec EventId_Name=Microsoft.EntityFrameworkCore.Query.QueryIterationFailed

Looking at the callstack, we tracked it down to this line of code: https://github.com/DuendeSoftware/IdentityServer/blob/b8444184354da12d87f0afc02dc548ab27a33635/src/EntityFramework.Storage/Stores/PersistedGrantStore.cs#L59

**To Reproduce**

Unsure, but we saw it in the logs a few times

**Expected behavior**

Not to have an error

**Log output/exception with stacktrace**

```
data
```

**Additional context**

Any ideas as to what could be causing this?

**Comment by josephdecock** [comment]
These log messages are caused by http requests being canceled. What happens is, when an http connection is terminated before we have generated a response, the framework cancels the task via a cancellation token. IdentityServer passes that cancellation token down to EntityFramework. When EF gets a cancellation, it both logs the cancellation as an error and throws an exception. IdentityServer has its own error handling which catches that exception and also logs it. We have added filtering to our logging in version 6.2 (check out the RC out last week!) which will help to reduce the level of noise from these exceptions. My understanding is that Microsoft's EF team is also intending to change the severity of their log levels which will help with the noise as well. I'm not sure when their changes will land, but for now, the upshot is that these log messages are not something to worry about.
