### ISSUE TITLE
Doesn't get any notification during backchannel logout

### ISSUE THREAD

**Issue by LilitHakobyan** [DuendeSoftware/Support#341]
IdentityServer 6.1.1 and Duende BFF 1.2.3 
Projects are .NET6, Web UI with BFF host, Identity server, and API.

Identity server and BFF server-side sessions are configured.

I want to fix the problem with multiple tabs logout, so when in one tab user logout the other tabes logout as well.

So i am trying to use a back channel logout approach.

Have the following configuration 
Client has  BackChannelLogoutUri = "host/bff/backchannel"

Identity server options.ServerSideSessions.ExpiredSessionsTriggerBackchannelLogout = true;
and in BFF  options.BackchannelLogoutAllUserSessions = true;

So with this configuration, i am not getting any log about back-channel logout and this doesn't help to resolve the problem with multiple tabs. 

Is the backchannel logout approach enough for fixing the multitab logout problem or i need to do some more configurations?
How should i test to make sure that back-channel logout is working?

Thanks in advance.

**Comment by josephdecock** [comment]
Are your multiple tabs all for the same application? If so, they should share a cookie and when you call the bff/logout endpoint, that cookie should get removed. Then, subsequent requests from the other tabs should be signed out.

**Comment by LilitHakobyan** [comment]
> Are your multiple tabs all for the same application? 
yes

>  If so, they should share a cookie and when you call the bff/logout endpoint, that cookie should get removed. 
this part is done

> Then, subsequent requests from the other tabs should be signed out.
I am mostly interested in this part 

How back-channel logout can help with this?
Should i use some sort of iframe to get notified from another tab?
And why i don't see any logs about backchannel if i did corresponding configurations?

thanks)

**Comment by josephdecock** [comment]
You don't need back channel logout in order to end the sessions in the other tabs - their sessions are already over, because their authentication cookies were shared, and deleted during the logout of the first tab. Anything that the user does in the future in those tabs that involves an authenticated API request is going to not have that cookie to authenticate the request. Or, you could build some sort of polling mechanism in your spa to make requests to an authenticated endpoint (maybe /bff/user) periodically and notice when your session ends if you want to make the UI show as logged out even if the user isn't actively using the app.

**Comment by brockallen** [comment]
Hi @LilitHakobyan -- any update here?

**Comment by josephdecock** [comment]
Closing, feel free to reopen if you need more help.
