### ISSUE TITLE
BFF queryParam, ui_locales, support

### ISSUE THREAD

**Issue by gryffs** [DuendeSoftware/Support#344]
**Which version of Duende BFF are you using?**

2.0.0-preview.5

**Which version of .NET are you using?**

6

**Describe the bug**

Unable to pass queryParam, ui_locales, through the BFF /bff/user endpoint and onward to the identity provider.

**To Reproduce**

Setup BFF and attempt to login while sending a queryParam from the SPA frontend.

**Expected behavior**

The ability to send a queryParam to our Duende Identity Provider when logging in from our SPA. We use this to send the language to display the login page in.

```

**Additional context**

My apologies if this is already supported, but I have not found how to accomplish sending a queryParam on login. I am in the process of upgrading an application to use BFF with an existing SPA (Angular) application. Thanks for the help!

**Comment by josephdecock** [comment]
I assume you mean the /bff/login endpoint, rather than the /bff/user endpoint. If so, you can control the ui_locales parameter by specifying it in the OIDC configuration:
```cs
 options.Events.OnRedirectToIdentityProvider = ctx =>
  ctx.ProtocolMessage.UiLocales = GetLocaleFromRequest(ctx.Request);
```

The UiLocales parameter will be parsed by IdentityServer and added to the [AuthorizationRequest](https://docs.duendesoftware.com/identityserver/v6/reference/services/interaction_service/#authorizationrequest) from [GetAuthorizationAsync](https://docs.duendesoftware.com/identityserver/v6/reference/services/interaction_service/#iidentityserverinteractionservice-apis).

**Comment by gryffs** [comment]
Thank you for pointing me in the right direction. I have successfully passed the ui_locales parameter through the /bff/user endpoint.
