### ISSUE TITLE
What would be the behaviour when enabling persisted grants cleanup with multiple instances(pods) of IS?  

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#353]
**Which version of Duende IdentityServer are you using?**
v6.1.0

**Which version of .NET are you using?**
.NET 6

**Describe the question**

We are going to enable the Persisted Grants Cleanup configs in our Identity Server. We have hosted it in Kubernetes with auto-scaling enabled, so there are multiple pods of the Identity Server running at the same time. Therefore, if we enabled auto cleanup with the 24Hr configured for the TokenCleanupInterval. Then how many times will it execute in a day? Would the clean-up be executed from all the instances or from only one instance?

For example, 3 pods of IS are running, so would it triggers clean-up three times?  

**Expected behaviour**

It should be run only once irrespective of the pod count.

**Comment by josephdecock** [comment]
The clean up job doesn't have any awareness of the fact that it is running in a load balanced environment, so if you have multiple instances of IdentityServer with the cleanup job enabled, they will all run the job. This could lead to failures as the pods each try to delete the same grants. Options here are:
- Have special configuration so that only 1 instance of the cleanup job runs (sorry, I'm no K8s expert, not sure if this is even possible for you with K8s)
- Disable the automatic cleanup job, and manually cleanup expired grants
- Accept that sometimes the jobs will run at the same time and try to delete grants more than once (might be possible to mitigate how often this happens by making sure that the pods start up with a delay?)

**Comment by brockallen** [comment]
@PratikPatel-Mtech -- all set here?
