### ISSUE TITLE
Question about cookie and token life times

### ISSUE THREAD

**Issue by gundogduhasan** [DuendeSoftware/Support#357]
**Which version of Duende IdentityServer are you using?**
V6

**Which version of .NET are you using?**
.net 6

Hello,
Currently I am trying to upgrade my project IdentityServer 4 to Duende Identity Server V6. So far everything good. I have a question about cookie and token life times in user interaction.

When user's cookie expired and renewed also access token life time renewed too. Of course access_token life is same the cookie life time.

My question is, Is there any harm, considering only cookie life time by making it access_token life time and cookie life time same? After that I use and consider only cookie life time for keep user logged in, or logged out according my scenario.

**Comment by josephdecock** [comment]
Typically access token lifetimes are shorter than cookie life times. The cookie life time sets how long will it be before the user has to log in again. That will vary depending on your requirements, but, very broadly speaking, longer is typically what users want. The access token lifetime sets how long an application can use the access token before it needs to get a new token. This can often be done automatically and without disrupting the user (with a refresh token). So, there's little harm or cost to making the access tokens lifetimes a bit shorter. On the other hand, there's some security benefits to limiting the lifetime of an access token - if the access token is stolen, the lifetime of the token will affect how great the impact of that token being stolen is. You also get user management benefits to limiting token lifetimes because it is hard to revoke a token once it has been created. The token literally has your digital signature on it stating that it is good until its expiration. If you want to be able to manage users and maybe lock out users for whatever reason, it can be hard to do if they have a token with a really long expiration.

**Comment by gundogduhasan** [comment]
I am appreciative your detailed answer. Many thanks @josephdecock
