### ISSUE TITLE
scope claims not updated on refresh token request with requested scopes  

### ISSUE THREAD

**Issue by aguacongas** [DuendeSoftware/Support#370]
**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
7.0

**Describe the bug**
My client configuration is:
```cs
new Client
{
    ClientId = "mauiblazorsample",
    RequirePkce = true,
    RequireClientSecret = false,

    AllowedGrantTypes = GrantTypes.Code,

    RedirectUris = { "mauiblazorsample://authentication/login-callback" },
    PostLogoutRedirectUris = { "mauiblazorsample://authentication/logout-callback" },

    AllowOfflineAccess = true,
    AllowedScopes = { "openid", "profile", "scope1" },
                
    UpdateAccessTokenClaimsOnRefresh = true,
}
```
When I send a refresh token with the scope parameter, I expect the access_token to be updated with requested scopes but the access token returned contains scopes requested during authorization:

```http
POST /connect/token HTTP/1.1
Host: localhost:5001
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token=3069641D41DAAD57AFE8EEAE21A55BAEF23F47A943516C62B83299A2E89BF868-1&scope=openid+scope1&client_id=test
```

```json
{
  "iss": "https://localhost:5001",
  "nbf": 1669843921,
  "iat": 1669843921,
  "exp": 1669847521,
  "scope": [
    "openid",
    "profile",
    "offline_access"
  ],
  "amr": [
    "pwd"
  ],
  "client_id": "mauiblazorsample",
  "sub": "1",
  "auth_time": 1669833311,
  "idp": "local",
  "sid": "345FF1C50B7BFCCECE7219BD6607EB38",
  "jti": "C9519A28873356A186B2A7903EB48FEC"
}
```

**Expected behavior**

The access token should contain scopes requested in the token request. For the example above, something like:

```json
{
  "iss": "https://localhost:5001",
  "nbf": 1669843921,
  "iat": 1669843921,
  "exp": 1669847521,
  "scope": [
    "openid",
    "scope1"
  ],
  "amr": [
    "pwd"
  ],
  "client_id": "mauiblazorsample",
  "sub": "1",
  "auth_time": 1669833311,
  "idp": "local",
  "sid": "345FF1C50B7BFCCECE7219BD6607EB38",
  "jti": "C9519A28873356A186B2A7903EB48FEC"
}

```

**Comment by josephdecock** [comment]
What scopes are you requesting in your initial authorize request? Refresh tokens create new tokens based on an existing grant, so if you don't request a scope in your initial grant, then the refresh token won't ever include it.

**Comment by aguacongas** [comment]
@josephdecock 
```json
"scope": [
    "openid",
    "profile",
    "offline_access"
  ],
```

That's the issue. in my opinion it should because the client is configured with UpdateAccessTokenClaimsOnRefresh.

We cannot implement [IAccessTokenProvider RequestAccessToken(AccessTokenRequestOptions)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.iaccesstokenprovider.requestaccesstoken?view=aspnetcore-7.0#microsoft-aspnetcore-components-webassembly-authentication-iaccesstokenprovider-requestaccesstoken(microsoft-aspnetcore-components-webassembly-authentication-accesstokenrequestoptions)).

**Comment by leastprivilege** [comment]
> When I send a refresh token with the scope parameter, I expect the access_token to be updated with requested scopes

This is not how it works. A refresh token can at maximum contain the scopes that were requested during the authorize request. Otherwise a client could potentially "silently" request scopes that were never consented to by the user.

The spec allows for "downscoping" - meaning a client could ask for less scopes during refresh. But we haven't implemented that.

By default a refresh token is an exact copy of the original token with an updates lifetime. `UpdateAccessTokenClaimsOnRefresh` means that we run through profile service again to update claims if needed.

**Comment by doeringp** [comment]
Are there any plans to support "downscoping" of access token during refresh with IdentityServer in the near future?

As a customer of Duende's Enterprise Edition, we're developing a web platform that uses IdentityServer as authorization server. Since we have multiple JavaScript apps within our website that need access tokens to call APIs we're decided to implement the "Token-Mediating Backend" as described in [OAuth 2.0 for Browser-Based Apps: Section 6.2](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps#section-6.2)

Because with this pattern access tokens are exposed to the browser, one of the best practices is to have minimally-scoped access tokens ([section 6.2.2.2](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps#section-6.2.2.2)). Therefore, it is important for us that IdentityServer provides a way for access token downscoping.

**Comment by leastprivilege** [comment]
> Because with this pattern access tokens are exposed to the browser, one of the best practices is to have minimally-scoped access tokens

Why does the access token have so many scopes to start with? Have you considered a full BFF instead (which is the recommendation)?
