### ISSUE TITLE
[Feature request] Allow extending OidcReturnUrlParser

### ISSUE THREAD

**Issue by MonstraG** [DuendeSoftware/Support#381]
**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
6.0.0

I'm trying to use a custom react-based frontend for the login/logout pages, and ended up basically following https://medium.com/@piotrkarpaa/using-spa-react-angular-ui-with-identity-server-4-dc1f57e90b2c, and both they and as a result, me, had to copy-paste `OidcReturnUrlParser.cs` with minor changes because it's marked as internal and cannot be extended.

**Comment by josephdecock** [comment]
Parsing return urls has historically been associated with open redirector attacks. The way that the specs have responded to this is to mandate that when redirecting, only allow exact string matches with pre-arranged uris - mistakes with bad regular expressions that allow an attacker to inject their own urls are just way too common otherwise.

Given how sensitive this logic is, we have made the url parser an internal class to try to discourage it from being extended.

**Comment by brockallen** [comment]
@MonstraG Can you explain under what condition your IdentityServer host is running in a different host than the code calling IIdentityServerInteractionService.GetAuthorizationContextAsync or IIdentityServerInteractionService.IsValidReturnUrl?

**Comment by josephdecock** [comment]
After that article was written, a new flag was added to identity server options: AllowOriginInReturnUrl, which allows the return URL validation to accept full URL that includes the IdentityServer origin.

**Comment by MonstraG** [comment]
Finally got around to trying it, adding `options.UserInteraction.AllowOriginInReturnUrl = true;` worked! Closing the issue, thanks!
