### ISSUE TITLE
Getting 502 Bad Request on Redirect

### ISSUE THREAD

**Issue by gryffs** [DuendeSoftware/Support#385]
**Which version of Duende BFF are you using?**

**Which version of .NET are you using?**

**Describe the bug**

Attempting to deploy BFF in Kubernetes in AKS. But, we are receiving 502 Bad Request after getting response from our Duende.IdentityServer and routing to /signin-oidc. We believe this to be related to headers and forwarding within the environment but have not been able to resolve the issue while following info found here:
https://docs.duendesoftware.com/identityserver/v6/deployment/proxies/
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0 

**To Reproduce**

Deploy BFF in Kubernetes using with ingress.

**Expected behavior**

We expect a successful login to route us back to the root of the application.

**Log output/exception with stacktrace**

```
      Request starting HTTP/1.1 GET http://ourdomain.com/bff/login?ui_locales=en - -
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/bff/login HTTP: GET'
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[12]
      AuthenticationScheme: oidc was challenged.
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/bff/login HTTP: GET'
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://ourdomain.com/bff/login?ui_locales=en - - - 302 0 - 293.8630ms
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://ourdomain.com/signin-oidc application/x-www-form-urlencoded 676
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[10]
      AuthenticationScheme: Cookies signed in.
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://ourdomain.com/signin-oidc application/x-www-form-urlencoded 676 - 302 0 - 276.7251ms
```

**Additional context**

Do you have any further guidance or suggestion to help us within this environment?

Thank you.

**Comment by josephdecock** [comment]
What I suspect is happening is that the auth cookie that the site is trying to issue is large enough that the cookie headers are too large for your reverse proxy. One way that can happen is if you have SaveTokens = true in your oidc auth handler in the application, because it persists the tokens within the cookie. You could test this theory by disabling SaveTokens (that will cause other problems - presumably the tokens are used by the app somewhere - but if your proxy stopped complaining, then you would know it was the auth cookie size that was to blame). 

You can reduce cookie size by storing the session data server side (you have to implement the ITicketStore interface) or by reducing the number of claims in your tokens. The other option is to tell the reverse proxy to allow the larger headers. But, if the proxy is having trouble with the header sizes, it is very likely that other systems will as well. For example, safari on iOS limits cookie data to 4kb. So you could solve the header issue at the proxy only to have the browser fail in the same way. That's why I would think first about server side session data or reducing the size of the tokens by limiting the claims in the tokens.

**Comment by gryffs** [comment]
Thanks @josephdecock ! This has pointed us in the right direction. It looks like our way ahead will be to implement ServerSideSessions. [https://docs.duendesoftware.com/identityserver/v6/bff/session/server_side_sessions/](https://docs.duendesoftware.com/identityserver/v6/bff/session/server_side_sessions/)
