### ISSUE TITLE
IdentityServer external auth provider SPA login page example

### ISSUE THREAD

**Issue by amadard** [DuendeSoftware/Support#39]
I am reviewing the SPA sample, and I dont see where it shows how to set up External Authentication providers for a SPA login page.  Is there any example?

If not, my assumption is that I would use the IIdentityProviderStore to retrieve the dynamically registered auth providers to present the user in the SPA.  Then recreate the logic in the Callback page as an API endpoint.  The SPA would have a callback URL for the external provider to redirect the user to for processing the results. The SPA calls the API endpoint with the details from the external provider.

**Comment by brockallen** [comment]
> I am reviewing the SPA sample, and I dont see where it shows how to set up External Authentication providers for a SPA login page. Is there any example?

No, we don't have anything like that. That's another example where it's often easier to just use server-rendered pages for the UI in IdentityServer (since so much of the ASP.NET Core plumbing leans that way already). But if you want that to be also a SPA, then you'd need to replicate the code in the login page that gets those values, get this list (presumably via Ajax?) and show it client-side, then have the use pick one and navigate to the external login logic to trigger Challenge.

**Comment by amadard** [comment]
Thank for the fast response!
