### ISSUE TITLE
IdentityProviders scheme is case sensitive

### ISSUE THREAD

**Issue by kappellaslx** [DuendeSoftware/Support#393]
IdentityProviders schemes should not be case sensitive as we have no control over what partners IdP's will send.
GetBySchemeAsync method is searching all IdP's with the provided scheme and creating an array in memory. Then it will take the record applying again the same Where clause but this time being case sensitive. 

` var idp = (await Context.IdentityProviders.AsNoTracking().Where(x => x.Scheme == scheme)
                .ToArrayAsync(CancellationTokenProvider.CancellationToken))
            .SingleOrDefault(x => x.Scheme == scheme);`

**Comment by josephdecock** [comment]
Sorry, but this is working as designed. Paths in urls are case sensitive (even if web servers using the case insensitive windows file system don't always respect that).

We have multiple filters in this code (and in many other places) because our implementation depends on case sensitivity, but we don't control if the linq provider or underlying database will be case sensitive.
