### ISSUE TITLE
User registration - login created user

### ISSUE THREAD

**Issue by PBMikko** [DuendeSoftware/Support#409]
**Which version of Duende IdentityServer are you using?**
6.2.0
**Which version of .NET are you using?**
.NET 6

How to do user registration process correctly? Users could navigate to register page from our web site or from login page. Then we verify new user email etc. and create new user. Now comes the problem. How can we sign in this new user without OpenId login request? After user creation we would like this new user to be automatically logged in so user would be able to set password for account.

Our user management is done by ASP.NET Core Identity.

**Comment by josephdecock** [comment]
### Navigation from Login Page to Registration Page
When IdentityServer redirects the user to the login page, it includes a returnUrl. There's no limitations on how the login page actually works - it can be a multiple step process, and it can link the user to other pages, including the registration page. The only requirement that IdentityServer imposes is that you establish a session (call `SignInAsync` in the IdentityServer host), and then redirect back to the returnUrl to complete the OIDC flow. 

So, when users navigate to the register page from the login page, keep track of the returnUrl that was passed to the login page. After the user is registered, make sure the registration process results in a session at IdentityServer, and then redirect to the returnUrl. If you pass the returnUrl as a query parameter from login to registration page, you must validate that the return url in the query parameter is a local url, otherwise you are introducing an open redirector vulnerability. 

See https://docs.duendesoftware.com/identityserver/v6/ui/login/redirect/ for more details.

### Navigation directly to the Registration Page
At the end of the registration process, call `SignInAsync` to create a session at IdentityServer. Subsequent requests to endpoints at the client application that require authentication will trigger a challenge and start the OIDC flow. Since the new user has established a session at IdentityServer, they won't have to enter credentials again.  It will the same as a single sign on experience for the user.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by PBMikko** [comment]
Hello,

Preserving returnUrl did the trick,

Thanks for help.
