### ISSUE TITLE
Integration of Microsoft Authenticator app with Duende

### ISSUE THREAD

**Issue by Umar-Mukhtar** [DuendeSoftware/Support#410]
**Which version of Duende IdentityServer are you using?**
6
**Which version of .NET are you using?**
Net 6.0
**Describe the bug**
MFA using TOTP is a supported implementation using ASP.NET Core Identity. How can we inject this into duende authentication pipeline?

I would like users to use Microsoft Authenticator app as a second factor of authentication after logging in using duende identity.

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**
The templates provided by Duende do not support 2FA but the ASP.NET Identity do provide support out of the box for 2FA.

**Comment by josephdecock** [comment]
Given the variety of requirements and different approaches to using ASP.NET Core Identity, our template deliberately does not provide features such as 2FA. The intent of the template is to be a starting point to which you can add the features you need from ASP.NET Core Identity, customized according to your requirements. Alternatively, you can [create a new project based on the ASP.NET Core Identity template](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-6.0&tabs=netcore-cli#create-a-web-app-with-authentication) and add IdentityServer to that project. With that approach, you may need to configure IdentityServer so that it knows the paths to pages for user interactions. Set the LoginUrl, LogoutUrl, ConsentUrl, ErrorUrl, and DeviceVerificationUrl as needed in your IdentityServerOptions.

**Comment by Umar-Mukhtar** [comment]
Thanks joseph i went that route and was successfully able to achieve it, it was a bumpy ride though 🙂 you can close this issue.
