### ISSUE TITLE
Protocol Claims handling in IExtensionGrantValidator

### ISSUE THREAD

**Issue by alex-sameli** [DuendeSoftware/Support#433]
**Which version of Duende IdentityServer are you using?**
6.1.7
**Which version of .NET are you using?**
net6.0

We implemented the token exchange flow using the IExtensionGrantValidator interface to exchange tokens between two audiences. As per https://www.rfc-editor.org/rfc/rfc8693.html, the "act" claim is used to represent that chain of delegation. 

Currently, the only supported way to add additional (protocol) claims within a client credentials context is the `ExtensionGrantValidationContext.Request.ClientClaims` collection. That collection however is subject to the client prefix feature, which prevents us from adding the "act" claim, as it would be prefixed. Configuring that specific client without a prefix would limit functionality otherwise. 

Exposing a separate collection (Which could be whitelisted to only allow certain claims - eg. protocol) would improve the existing behavior.

**Comment by josephdecock** [comment]
Hi, thanks for this feedback. To add the act claim, you first add it to the session in the validator and then emit it in the profile service. We document that here: https://docs.duendesoftware.com/identityserver/v6/tokens/extension_grants/token_exchange. Is that not working for you?

**Comment by josephdecock** [comment]
Looking at this a bit more, I see you're talking about a server to server scenario, where the profile service wouldn't be invoked. 

In that case, you have a couple options:

1. Change the `ClientClaimPrefix` option on the client configuration to null so that you don't prefix the act claim. 
2. Extend the `DefaultClaimsService`, and override `GetAccessTokenClaimsAsync`. In your override, call the base method to get the collection of claims, and then add the act claim to that collection.

**Comment by alex-sameli** [comment]
Hi @josephdecock , thanks for your valuable feedback.

1. We're unable to change the `ClientClaimPrefix` since we have other claims added to the response which require prefixing. 
2. We went with that option - thanks for pointing us in the right direction.
