### ISSUE TITLE
refresh_token is always null in GetTokenAsync

### ISSUE THREAD

**Issue by Umar-Mukhtar** [DuendeSoftware/Support#437]
**Which version of Duende IdentityServer are you using?**
6.0
**Which version of .NET are you using?**
6.0
**Describe the bug**
The swagger web api is client of duende ids, after enabling offline_access scope i am able to see the token in the developer tools xhr request but when i try to read the value from the api endpoint only access_token returns the value where as refresh_token is always null. What could possibly be wrong?

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

I need the value of access_token after user logs in to dump it in thw database. This client is swagger ui and not a web app at this point.
**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
> the api endpoint only access_token returns the value where as access_token is always null

I think there is a typo here - is it the refresh token or access token that is null? I'm assuming you're getting an access token but not a refresh token. Are you including the  offline_access scope in your  request for tokens? Is there outputs from IdentityServer's logs when you fail to get the expected refresh token?

**Comment by Umar-Mukhtar** [comment]
Yes, the refresh token is always null when requested using GetTokenAsync C# method however it does show the refresh token in developer tools. I need to save it against the user in the database but it's null when fetched in the code.

**Comment by Umar-Mukhtar** [comment]
![image](https://user-images.githubusercontent.com/3919963/214930794-559610f7-2367-4c64-8b8a-4f31ee7704d8.png)

This is what i get after logging in using swagger, the request includes access_token and refresh_token. 
There is no error but the value of refresh_token is null when captured using GetTokenAsync("refresh_token") in the api.

Yes the client application is set to SaveTokens

**Comment by josephdecock** [comment]
Sorry, I think I've been misunderstanding your architecture/what your expected outcome is. If you authenticate in the swagger ui, that authentication is happening in the browser, and the tokens (notably the refresh token) stay in the browser. The swagger ui is really a separate client from anything else. The API itself only ever sees the access token, so there's no way that the api would be able to get at the refresh token.

**Comment by Umar-Mukhtar** [comment]
Let's make it simple:

I need to store refresh token in the database for the user that has been
authenticated from the login page. Can we grab the refresh token within
duende? We tried to get refresh token on api side it failed, tried to get
it on react app it failed. Thanks

**Comment by josephdecock** [comment]
Refresh tokens are stored in the persisted grants store of IdentityServer itself. But what is your goal here?

**Comment by Umar-Mukhtar** [comment]
In my previous comment i have mentioned that i need to store the refresh token of the user in to the database to request access token in the future without having the user to log back in.  I just can't capture it neither on api level, nor on the react client end or within the duende web project. Any references to pull the refresh token from the grant store?

**Comment by josephdecock** [comment]
You're probably using one our implementations of the persisted grants store, which is why you didn't need to implement it directly. 

The refresh tokens are persisted in that store, but the purpose of that store is to allow IdentityServer to interact with clients that are presenting it with a refresh token. The persisted grants data should stay within IdentityServer, and pulling a refresh token from the grant store isn't what you want at all.

To allow users to get new tokens without logging in again, refresh tokens aren't typically stored in another database. Instead, you should store them in the user's session.

You mentioned that you have a react front-end. In general, we don't recommend javascript front ends ever touch any tokens, due to the inherent security risks posed by the shared execution environment of a web browser. Instead, our advice is to use the BFF pattern. We make some [great tools](https://duendesoftware.com/products/bff) to help you implement that pattern. If you are using Duende.BFF with your react app, then the refresh tokens will be stored in your bff session cookie, and we have session management tools to help you refresh the tokens as needed.

**Comment by josephdecock** [comment]
If you are sure of your threat model and want to accept the risk of having refresh tokens stored in the browser by your react app, then I recommend that you make sure that the refresh tokens are configured to have one time only use semantics (this is the default). 

Then you need to take a look at the react app and investigate how it is requesting tokens. When the react app redirects to IdentityServer to start the authorization process (with a redirect to /connect/authorize), you must include the offline_access scope in order to get a refresh token. Are you including that scope? After authorization, IdentityServer will redirect back to your application which will make an additional request to the token endpoint to get your tokens. This is where you would expect to see the id_token in the response, if you have requested offline_access. Note that your configuration of your client in IdentityServer also must have the EnableOfflineAccess flag on to allow this. Does the response from the token endpoint include the id_token? If it does, then you could store the refresh token in local or session storage, depending on if you want the token to be discarded if the browser is closed.

**Comment by Umar-Mukhtar** [comment]
Everything you mentioned is already in place and we do get the id_token.
The grant type for react app is implicit in duende client configuration. We
are able to login/logout, utilize the access token to establish session on
the web but the only thing we don't receive on react side is the no
refresh_token, it is simply not available in the response. It would have
saved hours of communication had this been received on the react app as a
response from /authorize endpoint.

**Comment by brockallen** [comment]
> The grant type for react app is implicit in duende client configuration. 

Well, this explains it -- that grant type does not allow for refresh tokens. You must use code flow to obtain a refresh token.

**Comment by josephdecock** [comment]
Yes, and I had a typo as well - I meant to say refresh token instead of id token.

**Comment by Umar-Mukhtar** [comment]
Thanks, what should be the  AllowedGrantTypes for react client in duende? We tried 
`AllowedGrantTypes = new [] { GrantType.AuthorizationCode }` 

Here is what we get 

<img width="1786" alt="MicrosoftTeams-image (6)" src="https://user-images.githubusercontent.com/3919963/216653294-bcb9d0da-20fa-4bed-98ef-eac70e57f28e.png">

**Comment by josephdecock** [comment]
Authorization code is the most typical grant type for a spa. The error that you're seeing probably means that the client ids don't match between the client and identity server configuration. 

In general, the error page that you're showing doesn't show very much detail though-this is by design for security and as per IETF recommendations. Instead, I would go to the identity server logs. Any time there is a protocol failure, there will be details explaining why that failure occurred.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?
