### ISSUE TITLE
How do the ApiResource-related tables get filled ?

### ISSUE THREAD

**Issue by kiansdi** [DuendeSoftware/Support#442]
I am using duende software v6.
I tried to search and clear the problem for myself but I couldn't find my answer within the documentation.
As I saw , there are 5 tables that are related to ApiResources.
ApiResourceClaims , ApiResourceProperties , ApiResources , ApiResourceScopes and ApiResourceSecrets.
But there is no prepared logic showing that how these tables are getting filled.
Therefore some main questions are still unanswered for me :
**How these tables are getting filled ?**
**How are the cilents and api reources related to each other ?**
**How can we specify the api resource that the intended access token is scoped regarding to ?**
  While creating a new instance of PasswordTokenRequest and sending taht request to identity server I'm getting a validation error about the way "Resources" property of the PasswordTokenRequest is indicated
```
Invalid resource indicator format
```
**How are the api resources and api socopes getting related at the database layer?**
I really need some help about handling these issues.

Thank you in advance for your attention.

**Comment by josephdecock** [comment]
The error you're getting indicates that your token request is malformed. The resource parameter in your request must be a uri without a fragment, for example, "urn:resource1". 

Configuration data in identity server is managed outside of IdentityServer itself. There are some 3rd party management tools, but you're free to add configuration to the database however you like.

The ApiResources table is the main table for defining resources. One function of a resource is to provide a grouping of scopes, which is captured in the related collection of ApiResourceScopes. Resources can be configured so that, when you request a particular resource you get a collection of claim types using the ApiResourceClaims. Resources can authenticate at the introspection endpoint using their collection of secrets, which is stored in ApiResourceSecrets. ApiResourceProperties provides a place to store extra properties about your resource.

Resources are further documented [here](https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/api_resources/) and [here](https://docs.duendesoftware.com/identityserver/v6/reference/models/api_resource/).

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?
