### ISSUE TITLE
localhost IdentityServer and permitted number of issuers

### ISSUE THREAD

**Issue by dave-Kinto** [DuendeSoftware/Support#449]
Duende IdentityServer 6.1.7.
.net 6.0

Hi,

So we are currently in the process of upgrading to Duende IdentityServer from a prior opensource version and we are getting the following message appearing in our logs:
Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2.

The two URLs being displayed are our external facing URL used for token requests (the URL recorded as the issuer in the tokens) and a localhost reference. Our IdentityServer is hosted on the same server as the client APIs and these are load balanced. The client APIs on each server refer to the localhost instance of the IdentityServer on the same server for token verification rather than the external URL.

So my question is, is this contrevening the license agreement as there is only a single issuer URL? 

Something that is confusing me somewhat is that I can generate this log message just by requesting a token from IdentityServer using the external URL when there is no reference to localhost being used. 

Thanks in advance.

Dave

**Comment by josephdecock** [comment]
What you're doing is allowed by the license - the intent of the license restriction is that there would be only 1 logical instance of IdentityServer, and that's clearly what you have done here.

Explicitly configuring the IssuerUri option should make the log messages stop. When you don't explicitly configure it, IdentityServer infers the issuer based on the request host. That makes your local requests and external requests have different issuers, and triggers the license validation.

**Comment by josephdecock** [comment]
On second thought, it would be much better to solve this through DNS instead of configuring the issuerUri. Change your services to use the public host name for identity server as their authority, and then use dns to make their requests to that name resolve to identity server on the same machine.

This is better for two reasons
- The OIDC spec mandates that the issuer be inferred from the dns name. Our option to override that is intended for rare usage when you must be non-standard, perhaps during a migration.
- If you override the issuerUri, the APIs will have to validate their tokens against that issuer, which will require code and configuration changes.

**Comment by dave-Kinto** [comment]
Hi Joseph, I will go with your suggestion and will look to resolve this using DNS. Thanks for your help.
