### ISSUE TITLE
Upgrading from Identity Server 4 to Identity Server 6: Database changes

### ISSUE THREAD

**Issue by KvnSearle** [DuendeSoftware/Support#453]
We are upgrading our instance of identity server 4 to identity server 6 .
We are using .Net 6.

Looking at the instructions at [Upgrading IdentityServer4 v4.1 to Duende IdentityServer v6 on the Duende Web site](https://docs.duendesoftware.com/identityserver/v6/upgrades/is4_v4_to_dis_v6/), it lists the changes made to the database but only goes into details for the indices.

The instructions talk about applying those changes using "dotnet ef database update....etc".

Maybe this is my lack of experience with entity framework, but I am wondering how I can use this whan deploying to environments other than Dev.

Is there a script of  the changes that need to be applied?

Thanks

**Comment by StuFrankish** [comment]
It's a question probably more suited to Stack Overflow as it's not specifically Identity Server related, but you could use the following as a starting point in your `Program.cs`

```c#
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

public static void Main(string[] args)
{
    var host = CreateWebHostBuilder(args).Build();
    MigrateDatabase(host);
    host.Run();
}

private static void MigrateDatabase(IWebHost host)
{
    var scopeFactory = host.Services.GetService<IServiceScopeFactory>();

    using var scope = scopeFactory.CreateScope();
    var coreContext = scope.ServiceProvider.GetService<IAppDbContext>();
    coreContext.Database.Migrate();
}
```
That will pickup any migrations that have not been applied to your implementation of  `IAppDbContext`, then apply them on start up.
Note that `IAppDbContext` is just the name of the interface I use that inherits from `IDbContext`.

**Comment by josephdecock** [comment]
IdentityServer is designed with a great deal of flexibility in mind when it comes to how data is stored. We don't mandate any particular database technology. We do provide the EF implementations of our stores for those who don't need to customize their data access, but even that is pretty abstracted - you can use the EF stores with any database that has an entity framework provider. We don't make any assumptions about the underlying datastore. Since each possible database will have a different schema language, we don't publish the scripts for doing database updates. Instead, we publish the entity framework entities, and allow you to build migrations from them if you so choose.

We also don't want to mandate any particular way to manage schema changes, because our experience is that different organizations have so many different tools and processes involved. Our docs are really just trying to give an example of how to get started with the EF tools, but at the end of the day we rely on you to manage your database using the tools and processes that you like.

There's definitely more than one way that you can use EF migrations and the tools microsoft has built for them. If you want to generate a sql script from you migrations, the EF cli tools can do that too with commands like `dotnet ef migrations script` (see https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli).

Finally, I probably wouldn't take the approach of running all unapplied migrations on startup. I'd want to control the deployment of database changes more explicitly in most cases. It does look like it could be convenient for demos and development though.

**Comment by KvnSearle** [comment]
@StuFrankish & @josephdecock thanks for the feedback.
It occurred to me that I could
- downloaded the zip file,
- search the code for the sql objects referenced in the Upgrade instructions
- deploy the upgraded application
- install any objects that might be missing of any errors occur during regression testing
Does that seem sensible?

**Comment by josephdecock** [comment]
I'm not sure which zip file you're referring to, sorry.

**Comment by josephdecock** [comment]
Most of the schema changes have either been improvements to indexing or additional data added to support new features, such as CIBA and server side sessions. It's possible that you're not using any of the new features and so haven't seen any errors so far, but I would still encourage you to update your database. 

A good way to get started is to generate a migration script with EF, and then review that script to see what it wants to do.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?
