### ISSUE TITLE
BFF - Duende IDS

### ISSUE THREAD

**Issue by allkeytech** [DuendeSoftware/Support#468]
**Which version of Duende BFF are you using?**
v6
**Which version of .NET are you using?**
6
I followed your Quickstarts and was able to implement it to a point that I had Duende IDS, Web and API configured and communicating using JWT token authentication. I am able to retrieve data from protected [Authorize]  controllers. I am in the process of using an Angular application using Duende BFF solution. Dominick was able to to point me in the right in finding the Angular end and it worked perfectly, pointing to your `options.Authority = "https://demo.duendesoftware.com";` IDS in the cloud. I would like to know where in your repository is a similar IDS solution that I can compare to what my IDS looks like? 
Dominick told me to look at [](https://github.com/DuendeSoftware/demo.duendesoftware.com) https://github.com/DuendeSoftware/demo.duendesoftware.com but that IDS solution doesn't seem to be like the one that's in the cloud because I could not get your Angular solution to be authenticated using Cookie. Can you please assist in pointing me in the right direction as to which solution has the Duende BFF / IDS solution?

**Comment by josephdecock** [comment]
That's the right repo for demo.duendesoftware.com. Sorry, I'm not sure what else you're looking for. Maybe we can help you with the issues you're having with the angular project. Can you describe the problem in more detail please?

**Comment by allkeytech** [comment]
So what you are saying: If I change the `options.Authority = "https://demo.duendesoftware.com";` to `options.Authority = "https://localhost:5001";` which will point to my local IDS and using the the Angular solutions under https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/BFF/AngularBffSample/src/FrontendHost/ClientApp I should be able to connect the Angular app and be authenticated using Cookie scheme?

[](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/BFF/AngularBffSample/src/FrontendHost/ClientApp)

**Comment by josephdecock** [comment]
Yeah, that's right. You might need to add client configuration to your identity server for the angular bff app though. If you get errors, usually the best place to look is the logs that IdentityServer writes to the console. It validates all the incoming requests and puts out lots of helpful information.

**Comment by allkeytech** [comment]
I'm getting this error from Angular:
[webpack-dev-server] [HPM] Error occurred while proxying request localhost:4200/bff/login to http://localhost:5001/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)

Another thing, I couldn't find any clientId anywhere within the Angular solution. How would the IDS know what client is requesting and how to resolve authentication? 

In my proxy.conf.js file, I change the following settings to point to my local IDS:
`const target = env.ASPNETCORE_HTTPS_PORT ? `https://localhost:${env.ASPNETCORE_HTTPS_PORT}` :
  env.ASPNETCORE_URLS ? env.ASPNETCORE_URLS.split(';')[0] : 'https://localhost:5001';`

**Comment by josephdecock** [comment]
When you use the BFF pattern, the front end doesn't participate directly in the OIDC flows. Instead, you redirect to a server side endpoint in the BFF host that initiates the flow. You never make any requests from the frontend to identity server in this architecture. That's why you're not seeing any OIDC configuration in the angular code. Also, you should undo the changes to your proxy.conf because you never want the Angular frontend to make direct requests to IdentityServer.

The OIDC configuration in the angular sample is in FrontendHost\Program.cs. You need to configure the OpenIdConnect auth scheme defined there to use your instance of IdentityServer:

```c#
AddOpenIdConnect("oidc", options =>
{
    options.Authority = "https://localhost:5001";
    options.ClientId = "bff";
    //...
```

Then in your IdentityServer config, you need to make sure that you have the corresponding client configuration for the bff client.

Something like this:
```c#
            new Client
            {
                ClientId = "bff",
                ClientName = "BFF Client",

                ClientSecrets =
                {
                    new Secret("secret".Sha256())
                },

                RequireConsent = false,
                AllowedGrantTypes = GrantTypes.Code,

                RedirectUris = { "https://localhost:44451/signin-oidc" },
                FrontChannelLogoutUri = "https://localhost:44451/signout-oidc",
                PostLogoutRedirectUris = { "https://localhost:44451/signout-callback-oidc" },

                AllowOfflineAccess = true,

                AllowedScopes = 
                { 
                    "api", 
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile,
                }
            },
```

And finally, the angular application is requesting a scope named "api", which we're including in the client config here. You'll need to declare that as an ApiScope, if you aren't already.

**Comment by allkeytech** [comment]
I looked at the solutions for Angular and "sort of" understand its implementation. I see that you are hosting the Angular app in a Asp.Net Core Web Application. I see the configuration in Program.cs where it would communicate to the IDS but what if you host your Angular application in a different environment like Firebase. How would that be configured to communicate with the IDS? I'm still fighting to understand the IDS configuration, but I'm sure I'll get it with some more investigation.

**Comment by josephdecock** [comment]
If you want to host the backend and friends separately, you can, it just takes a little more effort than hosting them together.

The Martin problem to solve is that the browser will block cross origin requests and prevent the authentication cookie from being sent cross origin.

You can solve this with CORS headers. We have a sample of that in the world that should be published in a week or two.

You can also solve this by putting a price in front of the two hosts so that the requests are not actually cross origin.

**Comment by josephdecock** [comment]
To diagnose the 401 error, I would confirm that you have a user access token by going to the /bff/diagnostics page, and also check the logs of the bff and api.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by allkeytech** [comment]
I got pulled off of the project temporarily. Thank you for your assistance. I will be looking at the solution again in the near future.
