### ISSUE TITLE
Question around runAllManagedModulesForAllRequests in IIS

### ISSUE THREAD

**Issue by crh225** [DuendeSoftware/Support#471]
**Which version of Duende IdentityServer are you using?**
6
**Which version of .NET are you using?**
.net core 6
**Describe the bug**
I am trying to use windows authentication on IIS with anonymous authentication turned off. When I turn off anonymous authentication some of our applications cant reach the endpoint .well-known/openid-configuration due to cors issues. This lead me to the following two articles:
https://stackoverflow.com/questions/22495240/iis-hijacks-cors-preflight-options-request
https://eugeneagafonov.com/post/38312919044/iis-options-cors-aspnet-webapi-en

and this one Identify Server 3 article:https://identityserver.github.io/Documentation/docsv2/configuration/overview.html

My question is, does this setting from Identity Server 3 still relevant to v6?
```
<system.webServer>
  <modules runAllManagedModulesForAllRequests="true">
  </modules>
</system.webServer>
```

**Comment by josephdecock** [comment]
If you're not able to access the discovery document due to CORS problems, then you need to either add the origins that should be allowed as AllowedCorsOrigins on your client configuration in IdentityServer, or if you need more control/customization you can implement the ICorsPolicyService.

Please see here in our documentation for more info: https://docs.duendesoftware.com/identityserver/v6/tokens/cors/

We also have a sample of using Windows Authentication in IIS: https://docs.duendesoftware.com/identityserver/v6/samples/ui/#windows-authentication-with-iis-hosting

And finally, you don't need RAMMFAR. IdentityServer3 was very different (using .NET Framework instead of .NET Core!) than the IdentityServer of today.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?
