### ISSUE TITLE
refresh token always be updated when UpdateAccessTokenClaimsOnRefresh is true

### ISSUE THREAD

**Issue by liuxingzhimahu** [DuendeSoftware/Support#475]
In https://docs.duendesoftware.com/identityserver/v6/reference/models/client/ says
![image](https://user-images.githubusercontent.com/25791741/215980663-f58bd5ae-de9f-4f95-8b5a-3dd29dcf4f66.png)

but in https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/ResponseHandling/Default/TokenResponseGenerator.cs, 
![image](https://user-images.githubusercontent.com/25791741/215983819-91a50109-adf2-4d37-9c29-633d792833fc.png)

when UpdateAccessTokenClaimsOnRefresh is true, both access token and refresh token will always be updated.
Old ID4 does not have this behavior.
This is intentionally or an issue?

**Comment by josephdecock** [comment]
The refresh token record in the data store needs to be updated in this case, because we store the most recent access token with the refresh token in the store. However, from the point of view of the application using the refresh token, there doesn't need to be any change to the token. If you are seeing new refresh tokens every time you use them, that probably means that you have your client's refresh token usage configured to be one time only. That's the default, which is needed for the security of a public client (like a spa without a bff), but for confidential clients, it is safe to switch to reusable refresh tokens.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?
