### ISSUE TITLE
JS-centric BFF

### ISSUE THREAD

**Issue by pdevito3** [DuendeSoftware/Support#486]
I know this would probably be big of a lift for you guys, but I keep seeing the opportunity for it I wanted to at least throw out the idea that you make BFF library for the JS world as well. 

The driver being that more and more teams are using frameworks like NextJs, Remix, Sveltekit, etc. that can handle the BFF side of things on their own, but require manual auth and BFF setup. 

The closest offering in the space right now is AuthJs and it’s really more just setting up the auth side of things. Honestly even that leaves a lot to be desired. 

Solution wise, I’d envision a typescript agnostic core and different frameworks like Next or remix each have their own lib to grab to take advantage of their framework. Tanstack Query is a good example of something similar. 

Regardless, if you guys were able to make a lib that makes setting up auth and a BFF as straightforward in JS frameworks as it is in the .NET world, that would make major waves.

**Comment by josephdecock** [comment]
Hey Paul, good to hear from you. Thanks for sharing your idea with us. We're not likely to prioritize this idea because we're focused on dotnet. The BFF's architecture uses ASP.NET's session management and Duende.AccessTokenManagment - tools that we have built and contributed to and have really deep experience with. At least for the foreseeable future, our plans are to keep building on that foundation.

**Comment by pdevito3** [comment]
Yeah, that's what I figured. Sorry to clog up y'all's feed!
