### ISSUE TITLE
Persisted Grant Stores data clean-up

### ISSUE THREAD

**Issue by nhumby** [DuendeSoftware/Support#492]
**Which version of Duende IdentityServer are you using?**
6.23

**Which version of .NET are you using?**
7.0

**Describe the bug**

Does the Duende IdentityServer delete records containing expired tokens or tokens/auth codes that have been exchanged and can no longer be used? Or is this a manual process we need to implement, and if so what's the best way of doing that? I saw methods in IPersistedGrantStore named RemoveAllAsync() and RemoveAsync() which I've implemented in my SQL-based grant store but I'm not sure how they're triggered, and my table is starting to contain a lot of expired tokens in it.

**Comment by josephdecock** [comment]
Our Entity Framework based implementation of the stores includes a background job that can be enabled that will periodically delete expired or consumed tokens. Since you have a custom implementation of the stores, you can't directly use that background job. However, you can take a look at what it is doing to build your own cleanup service.

See here:
https://github.com/DuendeSoftware/IdentityServer/blob/6.2.3/src/EntityFramework/TokenCleanupHost.cs
https://github.com/DuendeSoftware/IdentityServer/blob/6.2.3/src/EntityFramework.Storage/TokenCleanup/TokenCleanupService.cs

The main logic of cleaning up tokens is essentially to delete records that have a non null consumption date or an expiration date in the past. Sometimes it is beneficial to keep tokens after they are consumed or expired - they can be used for replay detection, and other purposes. So, you can decide how aggressive to be with cleaning out the tokens.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
