### ISSUE TITLE
No key matching kid or alg found in signing keys

### ISSUE THREAD

**Issue by msaha-sei** [DuendeSoftware/Support#500]
I'm getting below error - 
**"No key matching kid or alg found in signing keys"**

This is happening for both automatic and manual key management. 

Note that "https://localhost:44300/.well-known/openid-configuration/jwks" response contains both kid and alg value

**Comment by josephdecock** [comment]
That error looks like either a client or api that uses IdentityServer as its authority is failing to find the signing keys that it expects. That can happen when signing keys are rotated because clients and apis cache the key material - most .NET applications cache for 24 hours by default. Are you able to restart the client or api that is getting this error? Restarting would clear its cache, so if a restart fixes the issue, that is strong evidence of a caching problem. The way to mitigate these caching problems is to rotate keys more slowly, in a phased approach. First, you announce a new key but don't sign with it. Then, you wait for enough time to pass that all clients and apis have a fresh cache of the keys. Only then do you switch to signing with the new key. The old key needs to be maintained for a time to validate signatures of tokens that were signed before rotation. Only after all those tokens are expired can you finally completely remove the old key.

Our docs on key management describe this process in more detail, depending on if you are using automatic key management, manual key management, or transitioning from manual to automatic key management: https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/
