### ISSUE TITLE
SQL server tables not populated with configuration?

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#505]
**Which version of Duende IdentityServer are you using?**
Community

**Which version of .NET are you using?**
7.0.102
**Describe the bug**
All DB tables are empty. I expect them to be populated with the client configuration when the application starts up?

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by brockallen** [comment]
> All DB tables are empty. I expect them to be populated with the client configuration when the application starts up?


This is up to you and how you want to architect your solution. We don't (and can't) make any assumptions about that, so that's why the tables are empty. 

Even though we provide a EF implementation of the stores, it's often that customers don't really need that as their architecture and config tends to be static once developed. But your situation might be different.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by khteh** [comment]
> > All DB tables are empty. I expect them to be populated with the client configuration when the application starts up?
> 
> This is up to you and how you want to architect your solution. We don't (and can't) make any assumptions about that, so that's why the tables are empty.
> 
> Even though we provide a EF implementation of the stores, it's often that customers don't really need that as their architecture and config tends to be static once developed. But your situation might be different.

If it is not needed why do you provide it? Since you provide it, isn't there a need to provide clear and concise workflows, when / how to populate the tables, in order to use your library?

**Comment by josephdecock** [comment]
IdentityServer gets its configuration data through the abstraction of the IConfigurationStore. You therefore need an implementation of that store, for which there are 3 options:

- Use our in memory store. This is the most common choice. You simply write down your client configuration as a compile time constant, or load it from a config file at startup. In many cases, client configuration changes are very rare, and the simplicity of this approach is good.
- Use our Entity Framework based implementation of the store. Using a database adds flexibility but also complexity. There aren't tools from Duende to create or update the data in the underlying database, but there are some third party options (both commercial and open source). In our experience, it is [usually better ](https://blog.duendesoftware.com/posts/20220204_admin_ui/) to create something custom that can make the specific changes that are appropriate in a particular use case, rather than a tool that lets you set every possible option.
- Implement the interface yourself, for even more flexibility.

**Comment by khteh** [comment]
How do I read the configuration data added through the `AddInMemory<foo>` interfaces?

**Comment by khteh** [comment]
Found it -> `IClientStore`
