### ISSUE TITLE
Reference Token validation - lifetime

### ISSUE THREAD

**Issue by Hylaean** [DuendeSoftware/Support#544]
**Which version of Duende IdentityServer are you using?**
6.2.3 (licensed to inexto.com)

**Which version of .NET are you using?**
7.0.3

**Describe the bug**
We provide Reference Tokens to our customers as a (revokable) way to access our APIs.
We recently found out that some recently generated tokens were invalidated as we updated the certificate used for the general .net DataProtection. 
Older tokens generated by the IdentityServer 5 prior to our switch to Duende weren't affected.

This is related to this option:
options.PersistentGrants.DataProtectData = false;

**To Reproduce**
Use  .AddDataProtection().ProtectKeysWithCertificate(a) 
Generate a Reference Token.
Use  .AddDataProtection().ProtectKeysWithCertificate(b) 
The Reference Token is now invalid.

**Expected behavior**
I didn't expect DataProtection to be used for long duration token validation, this creates new constraints on its storage and key validation.
DataProtection keys expires after 90 days by default.

A warning in the traces telling about the lifetime differences when PersistedGrants are data protected with keys that are more ephemeral than the grant stored.

**Comment by josephdecock** [comment]
It seems like there are 2 different issues here.

Your reference token was invalidated because you changed your data protection configuration in such a way that the data protection keys that protected the reference token was no longer available. That would happen regardless of the expiration of the data protection keys - if you change how you tell the data protection system to protect its keys, then it no longer has certificate a, and therefore can't access the old keys.

Your suggestion about logging lifetime differences is interesting, but in the end it isn't necessary, because expired data protection keys can still be used to unprotect data. Expiring simply means that no new data will be protected with the expired key. As long as you don't delete the expired key, you'll be fine. And the data protection system intentionally does not expose a mechanism to do so, because it is a dangerous, destructive act.

**Comment by Hylaean** [comment]
I mean I was surprised by the new behavior as it was a major change from the previous version and it is a bit hidden in the documentation. The documentation states that use of DataProtection should be reserved to databases that aren't encrypted at rest, which is most production scenarios anyway.
