### ISSUE TITLE
 Duende IdentityServer only permits 1 number of issuers

### ISSUE THREAD

**Issue by arungunda** [DuendeSoftware/Support#559]
**Which version of Duende IdentityServer are you using?**

**Which version of .NET are you using?**

**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
Support for multiple issuers is an enterprise feature that requires the enterprise license, but it may be possible to change your configuration so net you do not need that.

Identity Server infers the issuer based on the requested host. We've seen it happen that an identity server implementation has both an internal and an external dns name unnecessarily. In that case, changing dns configuration so that there was just one hostname resolved the problem without needing the enterprise license.

On the other hand, if your architecture requires that you produce tokens with different issuers, then you do need the enterprise license.
