### ISSUE TITLE
User Login and Registration without  password using code by Email or SMS

### ISSUE THREAD

**Issue by SuhaibAlomary** [DuendeSoftware/Support#563]
I need your assistance in sharing some documentation or sample code on how we can obtain tokens through code will be sent to the user via email or SMS. By doing so, we will only allow our customers to register or login to our mobile application using that code only no need to create password for them.

**Comment by josephdecock** [comment]
Sorry, this is beyond the scope of what IdentityServer does or what we can support here. We don't have sample code or documentation for this. 

What I can help you with is to point out the mechanics of how IdentityServer works. When you make OIDC or OAuth requests to IdentityServer, it looks for an auth cookie. If it finds one, there won't need to be any user interaction in order to produce tokens. So, I imagine your custom code will ultimately need to create an auth cookie (that is, call SignInAsync). But the specifics of how you generate magic links and send them to your users, the threat model of that interaction, etc are all questions beyond the scope of what we can support here.

**Comment by SuhaibAlomary** [comment]
Thank you Josephdecock.

Another question please from device token I can get bearer token , if yes how ?

**Comment by josephdecock** [comment]
I'm not sure what exactly you mean by this, but if you are trying to change one token into another, you might take a look at our documentation on [Token Exchange](https://docs.duendesoftware.com/identityserver/v6/tokens/extension_grants/token_exchange/).
