### ISSUE TITLE
BFF BlazorWasm Auth Redirect

### ISSUE THREAD

**Issue by maldworth** [DuendeSoftware/Support#565]
**Which version of Duende BFF are you using?**
latest (2.0.0)

**Which version of .NET are you using?**
net6.0

**Describe the bug**
Our whole BlazorWasm app is protected (`[Authorize]`), and I want to avoid a flicker, which happens because the BlazorWasm SPA first has to load, before it issues the `.ChallengeAsync()`.

So I put in a middleware to do this. See the commit I put in from the forked Sample to reproduce:
https://github.com/maldworth/DuendeSoftwareBFF/commit/9e7c6c3590b367cac199fcfd3f1649fa74feefb0

The bug is, if I do this with the oidc authority:

```
options.Authority = "https://localhost:5001";
options.ClientId = "spa";
```
it works as expected.

if I do it against
```
options.Authority = "https://demo.duendesoftware.com";
options.ClientId = "interactive.confidential";
```

it's stuck in an infinite loop, [line 98](https://github.com/maldworth/DuendeSoftwareBFF/blob/9e7c6c3590b367cac199fcfd3f1649fa74feefb0/samples/Blazor6/Server/Program.cs#L98) always has User.Identity?.IsAuthenticated as false

**To Reproduce**
repo: https://github.com/maldworth/DuendeSoftwareBFF

Put breakpoint on line 98, and run Blazor6.Server. log in with bob/bob, and you will see the infinite loop.

Then swap line 46 to 47, and line 50 to 51, and set multiple startup projects:
![image](https://user-images.githubusercontent.com/187903/224423362-6daeaba0-8c70-4539-965c-49115078b329.png)

and it will succeed.

**Expected behavior**

No infinite loop when using demo.duendesoftware.com

**Log output/exception with stacktrace**

unfortunately no log data, as it is just stuck on a `.ChallengeAsync()` loop.

**Additional context**

nope

**Comment by josephdecock** [comment]
Your application cookie is being blocked by the strict SameSite cookie policy because the site changed due to redirects during the same sequence of requests that set the auth cookie:

![image](https://user-images.githubusercontent.com/1145533/224594712-c5e4a029-9238-4473-ae29-21fe89b51cbf.png)

Changing to SameSiteMode.Lax should resolve this problem.

**Comment by maldworth** [comment]
Thanks. Yeah if your Duende IDS instance is on the same domain as your app, strict would be fine. But if you are running it on a different domain, using LAX here is necessary. I made a PR to add a comment to the sample to help anybody in the future.

**Comment by brockallen** [comment]
@maldworth Did you ever try setting the OIDC options:

options.ResponseMode = "query";

And still use SameSite strict in your test case?

**Comment by josephdecock** [comment]
I think this is only necessary because you are issuing the challenge in the middleware. Our normal sample does work with demo.duendesoftware.com.

Another option for you, if you want to keep the cookie to be samesite strict, you could put in a javascript redirect instead of a server issued redirect. Brock describes that approach on his blog [here](https://brockallen.com/2019/01/11/same-site-cookies-asp-net-core-and-external-authentication-providers/).

**Comment by maldworth** [comment]
Thanks for looking into this. Yeah the purpose of using the middleware was to avoid the application having to load the SPA on initial load, just to redirect. More of a user experience issue I guess, but what I have to decide, is it worth it to switch from Strict to Lax, just to avoid the initial load? Anyways that's irrelevant for the discussion here. Cheers!
