### ISSUE TITLE
PostLogoutRedirectUri - What happens if the user doesn't click on the redirect link?

### ISSUE THREAD

**Issue by joseftw** [DuendeSoftware/Support#574]
Hello!

We're using IdentityServer together with the BFF application. Everything works like a charm.
However, we've modified the logged out page on IdentityServer to not automatically redirect to the PostLogoutRedirectUri.

Question: Is this, in anyway, "dangerous"? What happens if the user doesn't click on the link that redirects to the PostLogoutRedirectUri?

My understanding is that the session in the BFF has already been destroyed when calling /logout, is that correct?

**Comment by josephdecock** [comment]
There's no need for the user to follow the post logout redirect uri-it is a UI convenience only. You do need to sign out of the cookie auth scheme at the client application as well as the OIDC auth scheme though. Usually I do that in one call, because SignOutAsync can take multiple scheme name arguments.

**Comment by joseftw** [comment]
Awesome, thanks!
