### ISSUE TITLE
User login/logout audit logs

### ISSUE THREAD

**Issue by stefan0s** [DuendeSoftware/Support#576]
**Which version of Duende IdentityServer are you using?**
6.1.7

**Which version of .NET are you using?**
.NET6

**Describe the bug**

We are using the aspNetIdentity sample you provide for identity server. We would like to audit ipaddress and host whenever a user login and also determine the logout/end of that session. Which are the proper events we can achieve that?

My initial thought was to enable server side sessions and extend them with extra properties. Also when that session is terminated we cannot delete that record, so maybe that is not efficient.

Another approach would be to create a record per session on the profile service. How can I know that session is terminated then? Using logout event I can get that, but what if this is not triggered?

**Comment by josephdecock** [comment]
I don't recommend using the profile service for this, because it isn't only invoked when the user logs in or out. Instead, you could log events when the user logs in and out using our [Eventing](https://docs.duendesoftware.com/identityserver/v6/diagnostics/events/) infrastructure. This is probably the easiest thing to do, but you'll only get events when the user explicitly logs out. Very often, users just close their browser and you won't be notified of that.

If you do want to know when a user's session expires, you could also customize the session coordination service to do so. This service is invoked when server side sessions are enabled and a session ends either because the user logged out or because the session expired. Our default implementation cleans things up for you when a session ends by revoking tokens and sending backchannel logout notifications.

You could create a custom implementation of that service that would log the expiration of sessions. If you need to do that, probably you don't want to implement the interface from scratch. Instead, extend the `DefaultSessionCoordinationService`, and override `ProcessExpirationAsync`. In your override, log that the session has ended and then call the base method (to ensure all the normal processing occurs).

**Comment by ribsdigital** [comment]
@stefan0s did you have any luck with this approach?

we've been looking into doing a very similar thing i.e. when a `grant_type: password` token is requested via `/connect/token` and a user successfully authenticates we want to update a `LastLoginDate` property in the `AspNetUsers` table in the database.

the eventing side of things seems to be the go but despite reading through https://docs.duendesoftware.com/identityserver/v6/diagnostics/events/ we can't get any events that we've written to fire...

**Comment by josephdecock** [comment]
@stefan0s, the idea of events isn't to be a callback that can update records for you, the idea is just to emit data for structured logging. I think what you need instead is to override `ResourceOwnerPasswordValidator.ValidateAsync`. Call the base method and then look at the `context.Result` to see if you have a valid user. Then your custom code can update the database from there.

**Comment by ribsdigital** [comment]
hi @josephdecock thank you for getting back to us, that worked perfectly!

this is very cut down code, but the basics are:

```c#
public class ResourceOwnerPasswordValidator : ResourceOwnerPasswordValidator<ApplicationUser>
{
	private readonly ApplicationDbContext _dbContext;

	public ResourceOwnerPasswordValidator(
		UserManager<ApplicationUser> userManager,
		SignInManager<ApplicationUser> signInManager,
		ILogger<ResourceOwnerPasswordValidator> logger, ApplicationDbContext dbContext) : base(userManager, signInManager, logger)
	{
		_dbContext = dbContext;
	}

	public override async Task ValidateAsync(ResourceOwnerPasswordValidationContext context)
	{
		var user = await _dbContext.Users.FirstOrDefaultAsync(u => u.UserName == context.UserName);
		if (user != null)
		{
			user.LastLoginDate = DateTime.Now;
			_dbContext.Update(user);
			await _dbContext.SaveChangesAsync();
		}
	}
}
```

and remember to wire it up in the `HostingExtensions.cs` file in `ConfigureServices` (again, very much cut down code):

```c#
builder.Services
	.AddIdentityServer()
	.AddResourceOwnerValidator<BcnaResourceOwnerPasswordValidator>();
```

all working, happy days 👍
