### ISSUE TITLE
Question on Response body Version 6.2

### ISSUE THREAD

**Issue by 3stanmariano** [DuendeSoftware/Support#577]
**Which version of Duende IdentityServer are you using?** 
- Version 6.2

**Which version of .NET are you using?**
- net6.0 

**Describe the bug**

- We have a API automation for various end route of the Identity Sever and one test is failing because of the changes from the structure of the response body. Just want to validate if there are changes on the structure of the response body returned by version 6.2 on .well-known/openid-configuration/jwks? We've upgrade our Identity Server from 4.1.2 to 6.2 and here are the results of the two version

4.1.2

![image](https://user-images.githubusercontent.com/46551906/226497462-ed734704-3a7b-4161-ac84-2c208646b443.png)

6.2

![image](https://user-images.githubusercontent.com/46551906/226497492-867b840a-462e-4077-b684-97ab7d9542ae.png)

Although we don't see any issues during our manual testing, we just need to validate if we need some adjustment on the tests

**Comment by brockallen** [comment]
The first key in your 6.0 keys endpoint looks like it's coming from our automatic key management feature. The key used is an RSA key, but it's not coming from an X509 certificate, this the "x5c" is not needed, and thus is absent. It's all legit discovery document data, it's just different because of where the key is coming from.

Does that help?

**Comment by 3stanmariano** [comment]
Yes. Thank you for your response
