### ISSUE TITLE
Access BFF from other app on same domain

### ISSUE THREAD

**Issue by larserikfinholt** [DuendeSoftware/Support#58]
We're in the process of modernizing an old mvc app (brown(field)). As it is huge, the process will take long time (years). Our strategy is to build new functionality in a new SPA using BFF and multiple api's (green(field)). 

![image](https://user-images.githubusercontent.com/1328417/168067286-451e99cc-294c-41de-8d99-6035c536ea97.png)
 
Parts of the new functionality must also be able to run inside (as js/webcomponent, not as in an I-frame) the old mvc app. 
We understand that our first step will be to make the old mvc app use the same STS as the new app. 

This raies a few questions regarding authentcation, and retrival of accesstokens. How could we authenticate the user

Then to the (red arrow) questions:

- Question 1: Could we authenticate and call the BFF at /newapp from js at /mvcapp ?
- Question 2: How could we call the api1 from the .NET framework? Could we simply extrat the accesstoken from the httpcontext?
- Question 3: There will likely be multiple "newapp". We assume you would use one BFF per app?

Maybe we're missing something here, and picking the wrong strategy. We would be very greaful for any advice or recommondations.

Thanks for your help

**Comment by brockallen** [comment]
> Question 1: Could we authenticate and call the BFF at /newapp from js at /mvcapp ?

I assume you mean API calls here. Just thinking out loud here, since I've not had to solve this before:

If those two apps same site, then any cookie you have from the BFF will work. The trick is if the user has not yet visited the new app, then how do you get the cookie. You'd know this because the API returns 401, so your old app UI would have to know to redirect the user over to the new app. So then the hard part is when you redirect to the new app, how would it know to redirect back. So sounds like some custom landing page in the new app to know to "handshake" back. Beware open redirect attacks in your design here :)

> Question 2: How could we call the api1 from the .NET framework? Could we simply extrat the accesstoken from the httpcontext?

The old app should request an access token for that scope when it makes its OIDC request to the STS. There's nothing special about this scenario.

> Question 3: There will likely be multiple "newapp". We assume you would use one BFF per app?

Given how our BFF library currently works, yes, you'd use one BFF per SPA.

**Comment by larserikfinholt** [comment]
> The trick is if the user has not yet visited the new app, then how do you get the cookie

Agree, our login process has an extra step that complicates further, so we'll probably skip reusing the BFF for the old app.

Since there's no (as I know of) yarp for .NET framework, then we'll have to do some manually plumbing to use the new api's from the old app (add the token and route the request). Correct?

**Comment by brockallen** [comment]
> Since there's no (as I know of) yarp for .NET framework, then we'll have to do some manually plumbing to use the new api's from the old app (add the token and route the request).

Only if you need/want the automatic forwarding to the API. But if you just have custom code server side, then that can call the APIs "manually" with the access token that's part of the user's session.
