### ISSUE TITLE
Revoke Refresh Token on logout

### ISSUE THREAD

**Issue by sgartner-cityofboise** [DuendeSoftware/Support#584]
**Which version of Duende IdentityServer are you using?**
IdentityServer6
**Which version of .NET are you using?**
7
**Describe the bug**
When using refresh tokens, the tokens can be manually revoked, but it seems like it would be a good idea to revoke the refresh token during single signout.  This does not appear to happen currently.

**To Reproduce**
Enable refresh tokens, login and receive a refresh token, logout and the log does not show that the refresh token was revoked.

**Expected behavior**
When logout occurs, the refresh token would be revoked.

**Additional context**
This came out of the Identity & Access Control for modern Applications and APIs using ASP.NET Core 7  class.  This seemed like a good idea but the instructor, Joe DeCock, didn't know if there was a valid reason that the refresh token is not revoked in this situation.

**Comment by brockallen** [comment]
>  When using refresh tokens, the tokens can be manually revoked, but it seems like it would be a good idea to revoke the refresh token during single signout. This does not appear to happen currently.

Yes, this is possible but you would need to trigger it. One approach would be to do this on the logout page and use the IIdentityServerInteractionService's RevokeTokensForCurrentSessionAsync API:

https://docs.duendesoftware.com/identityserver/v6/reference/services/interaction_service/#iidentityserverinteractionservice-apis

>  This seemed like a good idea

Depends. If the client needs long lived access to the API after the user is logged out, then this would not make sense. Think about how mobile apps work on the phone -- you login once and never login again, typically because they use refresh tokens. And they can continue to do so after the user has logged out of the browser. This is why the scope is called "offline_access".

**Comment by brockallen** [comment]
Also, to add to this, client can also revoke their own refresh tokens when they know they are done with them. This could be done at logout time, or when they receive logout notifications, or at any other point.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
