### ISSUE TITLE
Multiple Access Tokens

### ISSUE THREAD

**Issue by dsheng123** [DuendeSoftware/Support#586]
**Which version of Duende BFF are you using?**
2.0.0

**Which version of .NET are you using?**
net7.0

**Question**
What is the intended way to manage multiple access tokens in Duende BFF? 

We have a system where we need to swap out the access token depending on which external system a user selects. Our workaround is to use the ServiceProvider of the HttpContext, but that seems to be more of an internal part of the Duende BFF framework and might also lead to problems with dependency injection lifetime as it is outside of our control?

```csharp
var tokenStore = _httpContextAccessor.HttpContext.RequestServices.GetRequiredService<IUserTokenStore>();
await tokenStore.StoreTokenAsync(user, token);
```

**Comment by josephdecock** [comment]
I think your approach is fine, actually. 

The `IUserTokenStore` is part of the `Duende.AccessTokenManagement` library which the BFF depends on. Its default implementation is the public class `AuthenticationSessionUserAccessTokenStore`, and it is registered as a scoped (that is instance-per-HTTP-request) service. It really is okay to use those services - we intend for IdentityServer and the BFF to be a framework that you build on, and its fine to call into the services to build the things you need to build.

By default, the BFF stores tokens in the authentication properties. Calling `StoreTokenAsync` replaces the token there with the token that you're storing, and calls `SignInAsync` with those properties updated. It also updates the store's internal cache so that as soon as you've made the call, the store will start returning the token (it doesn't depend on the newly issued auth cookie coming back).

**Comment by josephdecock** [comment]
A caveat though - the BFF wasn't designed with this scenario in mind. It sounds to me like it would work, but I haven't tried it.

**Comment by dsheng123** [comment]
Thanks for your quick reply

If you don't see any issue with this approach, than we are also happy with it!

Sounds like `IUserTokenStore` should be a somewhat stable interface then

**Comment by attilah** [comment]
@dsheng123 what solution worked for you in the end? We're trying to do something very similar, user's can switch between orgs and something is not adding up on our end. After token exchange we call the StoreTokenAsync, but it does not seems to be enough as we get an error message that cookie is missing the access token and SaveToken should be set to true which is like that as everything works before exchange.

**Comment by dsheng123** [comment]
@attilah I only remember that we solved the issue as described in the first post, but unfortunately not the exact details. I don't recall having any errors though.

**Comment by josephdecock** [comment]
> [@josephdecock](https://github.com/josephdecock) could you please confirm is it a bug or feature in this class that the `FilterPrincipalAsync` and `SignInAsync` and `AuthenticationTicket` is referencing the already logged in principal?


This is actually the intended design. The contract of the interface is to give you a user and their token and then perform some operation with that token. Different implementations of the store could make use of that user information, but the default `AuthenticationSessionUserTokenStore` implementation just stores the user in the current session. That's the easiest and most widely useful thing to do, because the default session is stored entirely in a cookie. This means that if the store wanted to associate the user and the token, there would have to be a server side session.

**Comment by attilah** [comment]
@josephdecock thanks for the explanation, that's what we thought, thankfully the interface was designed well so we could implement the required functionality!
