### ISSUE TITLE
Does BFF work within an iFrame?

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#589]
**Which version of Duende BFF are you using?**
Community

**Which version of .NET are you using?**
7.0.102

**Describe the bug**
My client application needs to run inside an iFrame of an external website (SAP Ariba Network). When I tried redirecting from https://www.mydomain.io to https://iam.mydomain.io to do the OAuth, it just doesn't get through. Clicking the "Sign in" button just doesn't bring the application over to https://iam.mydomain.io. There is no error logs in the browser debugger console as well as the OAuth application. 

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**
A web application should be able to redirect to the OAuth subdomain and back without any issue.

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by khteh** [comment]
Manage to get it to work but it doesn't successfully redirect back to the original application in the same iFrame. How should I configure the redirect URL for this use case?

**Comment by khteh** [comment]
The redirection back to the original website after successful login doesn't work. When Ariba Network first "punch out" to our web application it appends `?sid=<GUID>` to the URL which the website uses to communicate with Ariba Network. This information is missing when redirecting back from the OAuth to the original website.

**Comment by khteh** [comment]
Thanks for reaching out. I have figured it out by configuring cookies at both ends to use `SameSite = None`, `Secure=true` at both ends to get it going for now. Will use stricter cookie config once I have figured out how to identify if the applications are accessed within an iFrame.

**Comment by LarsKemmann** [comment]
@khteh Were you ever able to figure that part out reliably (how to identify if the applications are accessed within an iframe, in order to set `SameSite` either more or less strict)? I'm looking at a similar scenario of running a SPA (with Duende BFF) in Teams, SharePoint, and elsewhere while also supporting non-iframe use. I was starting to think I'd have to give up and go with client-side tokens, but the idea of dynamically setting the `SameSite` property hadn't occurred to me. I feel like that could maybe be accomplished through two domains (e.g., `app.example.com` and `embed.example.com`) that host the same SPA but with different Content Security Policy `frame-ancestors` settings, so that `app` is never allowed to be embedded (and requires `SameSite=Strict`) whereas the `embed` version allows embedding (and maybe has some other protection in it to prevent it from running outside of an embedded context)?
