### ISSUE TITLE
[Question] Are there any specific recommendations for modeling users in production?

### ISSUE THREAD

**Issue by pm64** [DuendeSoftware/Support#590]
The summary for the TestUser class is careful to state "Not intended for modeling users in production."

Would it be possible to provide a little more depth on this? Obviously a real user model will have domain-specific characteristics -- but in terms of security, are there specific omissions or simplifications in TestUser (aside from the plaintext password) that would be need to be considered for a production system?

**Comment by josephdecock** [comment]
It's hard to give just one answer to this question, both because IdentityServer is designed to not be coupled to the user store, and because different applications are going to have different security requirements. The fundamental simplification that makes `TestUsers` not suitable for production is that it isn't backed by any persistent storage. In terms of security, again, "it depends" on your security requirements. A couple of ideas for you:

1. Very likely you want to have multiple factors for authentication. Depending on which factors you use, you'll need to track additional data for them (e.g., text-based MFA would require a phone number to send to).
2. You probably want to track authentication failures so that you can detect attacks, such as credential stuffing and password spray.

**Comment by pm64** [comment]
Hi @josephdecock, thank you for your kind response.

There's been a bit of a miscommunication though, my question relates specifically to the `TestUser` class, i.e. the model representing an individual user. This is where the comment "Not intended for modeling users in production" appears.

The unsuitability of `TestUsers` in production is more obvious, though I greatly appreciate your suggestions and will definitely use them in my production user store.

But while I've got your attention, is there anything specific about `TestUser` requiring special consideration (aside from the plaintext password) that prompted Duende to include that comment above the `TestUser` definition?

**Comment by brockallen** [comment]
The reason we added that comment was because there were times when people trying to use IdentityServer, we often got questions like "how do I map from user data in my database to the TestUser class". In other words, it was not clear that IdentityServer was meant to be separate from the user and credential management library.

**Comment by pm64** [comment]
Ok I understand. Duende is warning users to not use the `TestUser` class *directly*. I interpreted it as "the way this class is designed would be inappropriate for a production user model", which is a misinterpretation. Thank you @brockallen for the clarification.
