### ISSUE TITLE
Endsession endpoint

### ISSUE THREAD

**Issue by juliussa** [DuendeSoftware/Support#592]
When `id_token_hint` is invalid or not provided, how to pass `post_logout_url` and `client_id` from `/connect/endsession`  to `/Account/Logout` endpoint?

If I provide `id_token_hint` and id_token is valid, logout works like a charm. But if not, user is redirected to `/Account/Logout` endpoint, where he can submit post form for logout. But then, I don't have the info, where to redirect user.

**Comment by juliussa** [comment]
I understand why `id_token_hint` is necessary and it is a valid point. But what I want to say is, when `id_token_hint` is missing,  Identity server doesn't generate the `logoutId` when redirect from /connect/endsession to /Account/Logout. And both values `post_logout_url` and `client_id` is not sent and are missing in ` /Account/Logout` page. Is there any specific reason for that?

**Comment by josephdecock** [comment]
The early drafts of the OIDC RP Initiated Logout specification say that redirection absolutely requires an id_token_hint, and OIDC Providers are prohibited from redirecting without it. In the last year the spec has been finalized with slightly relaxed language, so that now OPs are merely recommended to use an id_token_hint, "unless the OP has other means of confirming the legitimacy of the post-logout redirection target". The spec also seems to imply that this is distinct from checking for a registered post-logout redirect uri, because the very next sentences says (emphasis mine): 

> The OP **_also_** MUST NOT perform post-logout redirection if the post_logout_redirect_uri value supplied does not exactly match one of the previously registered post_logout_redirect_uris values.

So for now, our implementation continues to require the id_token_hint. We might revisit this in a future release, if we can determine how to provide "other means of confirming the legitimacy of the post-logout redirection target".

**Comment by juliussa** [comment]
Thank you @josephdecock for explanation.
