### ISSUE TITLE
This one is not an Issue need some help on SSO Implementation

### ISSUE THREAD

**Issue by mandar003** [DuendeSoftware/Support#596]
We have two different consumer apps an Desktop APP/Windows app and a Web site.
Both of these use identity server 4 for login purpose.
In desktop app we have some flow where user will be redirected to Web APP to view existing webpages. However the problem is SSO in not maintained between cross type application like Desktop and Web. user has to login again in Web
Is there any way we can achieve this?

**Comment by josephdecock** [comment]
As of November last year, IdentityServer 4 is no longer supported. To get support on these forums, please get in [touch to get licensed](https://duendesoftware.com/products/identityserver).

That said, to get SSO working across a desktop and web application, you need the desktop application to use the system browser rather than an embedded browser. How you go about doing that depends on the tools that you're using to build your application.

**Comment by josephdecock** [comment]
Closing, but feel free to open a new issue if you have other questions!
