### ISSUE TITLE
React Framework with BFF Pattern

### ISSUE THREAD

**Issue by tylersouthard** [DuendeSoftware/Support#602]
**Which version of Duende BFF are you using?**

Duende,BFF 2.0.0

**Which version of .NET are you using?**

ASP.NET Core 7

**Describe the bug**

This isn't a bug, but a question. I'm writing a new SPA using React, and I am trying to use the BFF pattern. I have read the resources indicating the benefits of using the BFF pattern for securing SPAs, so I'm using Duende.BFF with an ASP.NET Core backend that basically just handles the authentication and reverse proxy aspects of the SPA (for now). I used the template for ASP.NET Core + React, where the React app is located in the ClientApp folder.

My question is: According to the [React docs](https://react.dev/learn/start-a-new-react-project#can-i-use-react-without-a-framework), it is heavily suggested to utilize a framework for any real, production React app, and that several issues will likely arise down the line if one isn't used. They list Next.js and Remix as options, but those are "full stack" options, dictating Node.js as the backend. **Are you able to offer any suggestions for using Duende.BFF in ASP.NET Core with a React frontend in a production app?** Is there a React framework that can work well in this situation? Is a framework not really needed, and the React docs are over-blowing the case for one? I can't imagine this hasn't been done, but I only see test app examples, and no one describing production-level apps with this pattern and combination of technologies.

**Comment by josephdecock** [comment]
The main benefit I'm aware of that these node-based frameworks can provide that isn't easily replicated on .NET is server side rendering. For a while there was an open source .NET library for using react that would do server side rendering, but it is [no longer being maininted](https://github.com/reactjs/React.NET/issues/1315) and isn't compatible with the latest version of React. 

If you decide not to use server side rendering, then you can probably add individual components for routing and managing state and whatever else you need. But if you do want server side rendering and/or a framework to give you something a be a bit more opinionated about which tools to use, you're probably going to need to incorporate some node into your architecture, and have a separate host for the front and back ends. 

Getting back to the BFF pattern, the main requirement of the architecture is to make it so that when the browser makes requests from the front end to the back end, it includes the BFF's session cookie. For maximum security you generally want the session cookie to be same-site=strict, and to support browsers like firefox and safari that block 3rd party cookies, you need to make sure that the front end and back end are first party to each other.

One way to accomplish that would be to host the BFF and front end on sibling subdomains. I have a sample (not officially released yet, but "coming soon") of how to set that up [here](https://github.com/DuendeSoftware/Samples/pull/93). This technique requires using CORS as well as adding a flag to your fetch requests so that they include the auth cookie. The limitation of this technique is that the front and back ends have to be on the same site (in the [precise sense of the term](https://developer.mozilla.org/en-US/docs/Glossary/Site)).

Another option is to arrange for the BFF to host the index page of your front end as static content, and host all the UI assets on a different domain (this could be a CDN). That solves all of cross-site and 3rd party issues because the front end's origin is identical to the BFF, but it can add some complexity to your deployment and dev experience (you need to get the index page from your front end build into the static content of your BFF somehow, as well as configure your front end build to understand that its assets need to be retrieved from another site, and the details are probably different in local dev and deployed environments).

**Comment by tylersouthard** [comment]
Ok, thanks. I'm just trying to get started on a SPA and was trying to utilize best practices. Reading the information about the BFF pattern led me to implement an ASP.NET Core BFF with React as the frontend. The problem is, I'm having trouble finding any production-level examples that use ASP.NET Core as a BFF for a React frontend, and I'm wondering if I'm going to go down a path I'll regret by not prioritizing using something like Next.js from the start. I wasn't sure how to do the BFF pattern (which makes a lot of sense to me) with a framework like that.

**Comment by josephdecock** [comment]
I think ASP.NET (and Duende.BFF in particular) will work great with a react front-end, even if you use next.js or something similar. Your next.js application can run in one host and the bff can run in another, and then you handle the cross origin stuff as I mentioned above.
