### ISSUE TITLE
Missing document for keyring

### ISSUE THREAD

**Issue by khoa-nguyendang** [DuendeSoftware/Support#618]
**Which version of Duende IdentityServer are you using?**
6.1.0
**Which version of .NET are you using?**
.NET 6
**Describe the bug**
``` 
Unknow where to move next
```

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
System.Security.Cryptography.CryptographicException: The key {1d24f08b-abb7-44e8-b92a-63849bc5a3ba} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 75
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 447
```

**Additional context**

**Comment by josephdecock** [comment]
IdentityServer needs cryptographic keys, called signing keys, to sign tokens such as JWT access tokens and id tokens. These keys are critical secrets for IdentityServer because a valid signature provides integrity and non-repudiation guarantees that allow client applications and APIs to trust those tokens. 

You can manually configure signing keys, but by default IdentityServer will manage signing keys for you. The signing keys that IdentityServer generates are protected at rest using ASP.NET's data protection feature. Data protection is a separate cryptographic tool built into ASP.NET that signs and encrypts data. ASP.NET data protection has its own cryptographic keys, called data protection keys, that are  managed separately from the signing keys that IdentityServer uses. The data protection keys can cause problems if you have a signing key stored in your signing key store, but try to decrypt it without the data protection key that encrypted it.

There are several ways that this can occur:

1. In load balanced environments, every instance of IdentityServer needs to share signing keys, and you need to configure data protection to do so. Microsoft has extensive docs [here](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview) describing how to configure storage and protection of data protection keys.
2. Signing keys could be generated in a (local) development environment and then accidentally included into the build output. If your automatically managed keys are stored on disk, which is the default, you should exclude the ~/keys directory from source control and make sure keys are not included in your builds. Note that if you are using our Entity Framework based implementation of the operational data stores, then the keys will instead be stored in the database.
3. Data protection creates keys isolated by application name. If you don't specify a name, the content root path of the application will be used. But, beginning in .NET 6.0 Microsoft changed how they handle the path, which can cause data protection keys to break. Their docs on the problem are [here](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview#setapplicationname), including a work-around where you de-normalize the path. Then, in .NET 7.0, this change was reverted. The solution is always to specify an explicit application name, and if you have old keys that were generated without an explicit application name, you need to set your application name to match the default behavior that produced the keys you want to be able to read.
