### ISSUE TITLE
PersistedGrant Key column nullable

### ISSUE THREAD

**Issue by pampua84** [DuendeSoftware/Support#625]
Hi, how come in the PersistedGrants table since version 6.1.0 the Key column became nullable? Is there a particular reason? I ask because I have seen that an index is always created on the column

**Comment by josephdecock** [comment]
In 6.1, we added a new integer primary to the table, because such integer primary keys have better performance. As part of that change, the key column is now no longer the primary key of the table and is therefore no longer required. We index the non null values in the column, and I think in typical operation, you would never get nulls there, but we went with this design for added flexibility.
