### ISSUE TITLE
Issue:- Bearer error="invalid_token", error_description="The signature key was not found"

### ISSUE THREAD

**Issue by aritro60** [DuendeSoftware/Support#632]
I am using Duende.IdentityServer 6.2.3 with dotnet version as .NET 6

Bug:-
I am getting 401 error code when I am trying to call APIs by passing the token generated from Duende.IdentityServer(6.2.3). When I am using IdentityServer 4.1.2, it is working fine but when I am upgrading it to Duende.IdentityServer 6.2.3, I am getting this issue.
I have updated the Database schemas(added the Keys table in DB) and I am able to see the key(in Keys table) in database which has been generated with the new feature called 'Automatic Key Management'. I have set the KeyManagement Rotation Interval as 90 days.

This is how the configure services function in startup file looks:
![image](https://user-images.githubusercontent.com/126474470/234269516-18962895-afb3-4432-aa19-3f97871c67fa.png)

This is how the configure function in startup looks like:
![image](https://user-images.githubusercontent.com/126474470/234272117-0bf5ca06-c812-4541-8351-7ef3409dbab2.png)

**Can someone please tell me if I am doing anything incorrect or let me know if you need further details**

**Comment by josephdecock** [comment]
This sounds like an error from a client application. If that's so, then probably what happened was, when you deployed you got a new automatically managed key and immediately started using it. However, the client applications cache the public key material (typically for 24 hours), so the clients were unable to validate your signatures after you deployed. The chapter in the documentation on [key management](https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/) goes into detail on various strategies for how to change and rotate keys smoothly. But I would guess by now, you no longer have this issue since the caches have had time to refresh.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
