### ISSUE TITLE
Best practice: How to deal with SSO when multiple Clients have different AMR requirements

### ISSUE THREAD

**Issue by stephmueller** [DuendeSoftware/Support#647]
**Which version of Duende IdentityServer are you using?**
6.1.0 (soon 6.2.x)

**Which version of .NET are you using?**
.NET 6

**Question**
Our IdentityProvider, which is built upon the Duende Identity Server Framework (v. 6.1 / C# .NET 6), has some registered Clients. For some of them we implemented a 2FA (MFA) Login and some of them just require a login with a password (pwd). This is a problem, as with the SSO, a user can login to a  client with the lower login-security-quality and then is automatically as well authenticated for the apps which need 2FA/MFA.
 
What is the best practice to solve this issue? We thought about the StepUp-mechanism (Setting the AMR-claim according to the login-type) as one option. But there it seems, that Session-Cookies (idsrv / idsrv.session) are still valid between the different clients and only access to a (API-)Ressource is protected. (Because the amr-Claim of the Token is validated). And additionally it seems to be an approach for intra-Client not between different Clients..

On the other hand we thought about introducing 2 different tenants via the acr_values QueryParam and an tenant claim. One tenant just with pwd-Authentication and one tenant with mfa-Authentication. And then enable option ValidateTenantOnAuthorization. But here we do not know: Is the tenant information available in the Cookie itself? And is this a valid approach or it the tenant then just missused as a non-existent security-feature?

Or, third option, should this be solved via the a CustomAuthorizeInteractionResponseGenerator? But then how if there is already an established browser-session?
 
Are these three approaches valid approaches? Should it be a combination? 

Or what is your recommendation to solve this issue?

**Comment by josephdecock** [comment]
There are two ways you might approach this, depending on if you want the client application to control the decision to use MFA.

If the client is going to control that decision, and the workflow looks like a simplified step up. You use the same parameters as in step up to indicate if you need MFA, it just is initiated by the client needing to login rather than the client detecting that it (or an API) needs a higher level of trust.

To implement step up, or a flow like this, you will need to customize the authorize interaction response generator. Your custom code there will either use the existing session or redirect the user to login again, based on the way they initially logged in and the way that the authorize endpoint is being invoked.

If you want your identity server to control the decision to use MFA, you would still use a custom response generator. In this case however, rather than doing whatever is indicated by the request parameters, you make the decision based on the client ID.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
