### ISSUE TITLE
Best practices or recommendations to move Identity Server from one domain to another?

### ISSUE THREAD

**Issue by hugoqribeiro** [DuendeSoftware/Support#650]
**Which version of Duende IdentityServer are you using?**

6.2.3

**Which version of .NET are you using?**

.NET 7.

**Describe the question**

We have the challenge of moving our Identity Server deployment from one domain to another.
This deployment is a full-blown server with Identity Server and ASP.NET Identity to manage the users.

I suppose that this will affect user's security stamps and issued tokens and, ultimately, the way client applications validate those.

Can you point to any best practices to minimize this impact?

**Comment by brockallen** [comment]
> This deployment is a full-blown server with Identity Server and ASP.NET Identity to manage the users.

We can't speak to issues with ASP.NET Identity, as that is Microsoft's product. As for IdentityServer, it's the same as any other ASP.NET Core app. This means you need to address all the issues related to deployment: https://docs.duendesoftware.com/identityserver/v6/deployment/. But also, the main thing I'd wonder is if the domain is changing, is it the same OIDC provider as before? The identity of the OIDC provider is tied to the issuer in the protocol, so it's hard to say what that means for your architecture.

**Comment by hugoqribeiro** [comment]
Well, you would expect at least something like this:

Day -1 (IdP is in server1.com)

User X user application A and signs in with email/password.
Client Y obtains token for API resource B.

Day 0 (IdP is in server2.com)

User X opens the same application. He's forced to sign in again. Worst scenario, he's forced to change his password.
Client Y tries to use the same token, fails and obtains a new token.

In a perfect world, it would be possible to redirect requests from server1.com to server2.com and have everything going as above, no?

What is strange to me, is that I'm unable to find any info out there about a migration like this. I'm sure someone as gone through the pain before...

**Comment by josephdecock** [comment]
Just redirecting the requests from 1 domain to another is not going to be enough, because the various client applications and apis trust a particular domain, so they'll be expecting tokens that are signed by that entity with that domain in the iss claim. 

Brock linked to the docs that discuss it, but I just want to call out that you'll need to share the data protection keys between the two environments so that your new host can decrypt data that was encrypted in the old environment. 

Depending on your situation, there are a lot of different strategies that might be appropriate for this migration. A couple of different ideas:
1. If you control all the applications and apis, and can accept some downtime, you could update all the applications at once in a "big bang" approach. 
2. Alternatively, you might need both identity providers to live side by side for a while as you migrate from one system to the other. You can set up your APIs so that they'll accept tokens signed by multiple IDPs, and incrementally switch your client applications to use the new IDP. However, as you incrementally update applications, the ones using the new IDP will have single sign on among themselves, and the ones using the old IDP will as well, but you won't get single sign on across 
applications that are using different IDPs.

Hope that helps!

**Comment by hugoqribeiro** [comment]
Thank you, @josephdecock.
In fact, we are pursuing (2).
The big bang is too big to be feasible.
