### ISSUE TITLE
Can not authenticate user if user try to login to client app through identity server login page after few hours of loading 

### ISSUE THREAD

**Issue by RajaSomu783** [DuendeSoftware/Support#662]
**Which version of Duende IdentityServer are you using?**
6.0.2
**Which version of .NET are you using?**
.net 6- Angular auth oidc (SPA)
**Describe the bug**

We have an application that uses IdentityServer  for authentication. Everything works except in one Edge case. 
The Edge case is we have loaded the client app into browser but for some reason user didn't login into application and after few hours if user try to login then client app redirecting to IdentityServer  login page and after entering user credentials it failed to authenticate and shows 400 status on browser. If I reload the client app and it works without any issues. I believe something has expired to tell to the IdentityServer  where the request coming from.  Could you please let me know how to fix the issue or any hints to fix this.

![image](https://github.com/DuendeSoftware/Support/assets/111736502/e983c2ef-9e83-460e-9815-5fefd6948b44)

**Comment by josephdecock** [comment]
ASP.NET's oidc handler keeps track of some state in a cookie when it starts an OIDC login flow. When the flow sends the user back to the application, it uses that state to make certain security checks, and if it has been too long, those checks fail in this (ungraceful) way. You can add custom code to the handler's [onauthenticationfailed event](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnectevents.onauthenticationfailed?view=aspnetcore-7.0#microsoft-aspnetcore-authentication-openidconnect-openidconnectevents-onauthenticationfailed) to give the user a better experience, such as restarting the flow. Since the user already has a session at IdentityServer, they should end up logged in after some quick redirects back and forth. But a word of caution - watch out for infinite redirects. If there is a "real" error, restarting the flow might trigger the error again, leading to an infinite loop.

**Comment by RajaSomu783** [comment]
Hi @josephdecock , Thank you for the reply.  Did mention ASP.NET's oidc handler on client or Identity server side? Sorry I should have mention clearly. It is a SPA app using Angular auth oidc with Code and PKCE (I have mentioned under 'Which version of .NET are you using?' ) I am not using ASP.NET oidc on client side. I can see SPA is sending 'NONCE' and 'Code Challenge' when user tries to access protected routes or login button. It looks like is it is failing on Identity server side it's self as if I try to enter incorrect credentials it is still giving 400 status.  Could you please let me know if you any have more idea about this.

**Comment by RajaSomu783** [comment]
it is a problem with Anti Forgery token validation in .NET CORE and I have resolved by redirecting user to same url if we get 400 status code.
