### ISSUE TITLE
Consent View always pops up when retrieving refresh token using offline access

### ISSUE THREAD

**Issue by sash9143** [DuendeSoftware/Support#700]
**Which version of Duende IdentityServer are you using?** 6.2.3

**Which version of .NET are you using?**  6.5

**Describe the bug**

It occurred to me that whenever a user logs in again to a client that he has already consented to give access to his resources (and specifically to offline_access - meaning the client will get a refresh token), he has to consent again and again.

I just think of real life applications - you don't consent every time you login again to an app

I have a customized identity server can I handle that from there, if so can I know what is the possible way

**Comment by josephdecock** [comment]
The decision to display the consent screen is controlled by the `IConsentService.RequiresConsentAsync` method. The easiest way to customize this behavior is to extend the default implementation of that interface (the `DefaultConsentService`), which marks its methods as virtual so that you can override what you need to and rely on the base methods to get the default behavior you don't want to change. The default implementation requires consent every time that a refresh token is issued if the client has enabled RequireConsent. The intent is that when applications that require consent will have long-lived access, the user needs to be notified before giving out that long lived access, and that once the user has granted that access, the application will use its refresh token, rather than making the user log in again, but again, you're free to customize this according to your needs.

**Comment by brockallen** [comment]
> The default implementation requires consent every time that a refresh token is issued if the client has enabled RequireConsent. The intent is that when applications that require consent will have long-lived access, the user needs to be notified before giving out that long lived access

To add some context here, our default implementation does this because the OIDC spec provides strong language that we should prompt the user:

https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

Of course, as @josephdecock mentioned, you can change this behavior if you want.

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
