### ISSUE TITLE
ValidIssuers

### ISSUE THREAD

**Issue by mfarahy** [DuendeSoftware/Support#707]
**Which version of Duende IdentityServer are you using?**
6.2.1
**Which version of .NET are you using?**
6
**Describe the bug**
We have one identity server but with two different domain name located in a k8s cluster. The first domain name is an external domain name such as identity.website.com and another domain name is k8s local domain name. We need to authenticate a JWT token from both these domains so we need to add validIssuers parameter to the TokenValidator but there is no way to set this.
![image](https://github.com/DuendeSoftware/Support/assets/10452228/e417aff5-e4b9-4157-a105-e1a311809f87)

**Comment by josephdecock** [comment]
We don't normally recommend having a deployment of identity server with multiple domain names, as it tends to cause issues like this. The licensing system actually will treat this situation as distinct deployments of identity server, which does require an enterprise license. Instead, I would try to solve this problem using DNS. Have a single DNS name for your identityserver and configure your cluster so that it knows that that name should resolve to the appropriate node in the cluster.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
