### ISSUE TITLE
bff/user - return 401

### ISSUE THREAD

**Issue by wantwi** [DuendeSoftware/Support#725]
**Which version of Duende BFF are you using?**
2.0.0
**Which version of .NET are you using?**
6.0
**Describe the bug**
I keep getting 401 for the bff/user endpoint even though I have successfully login into my application. This occurs after publishing my app unto a development server

**Expected behavior**
On my local development, am able to fetch user claims using bff/user, however after publishing to a development server to test in a build environment, bff/user returns 401 even though I have successfully login form the identityserver

**Comment by josephdecock** [comment]
The most likely cause of this issue is that the browser is not sending the bff's authentication cookie when you make these requests. This could be due to the samesite cookie attribute or other cookie rules that the browser is following. 

You should check the http request to /bff/user and make sure that it is sending the authentication cookie (I suspect you will see it is not). If not, then the browser dev tools will hopefully have more information about why the cookie is not being sent. You might see errors or warnings on the console or in the details of the network requests, especially the network requests that set the auth cookie.

**Comment by wantwi** [comment]
Thank you for the respond. 
After setting the cookie to same site mode, am not getting 401 after login when I call the bff/user endpoint.
However, there seem to be anther problem. After a successful login, am redirected to my app but as a blank page with white background.
I clone the bff with react sample project and am getting the same blank white page when I build and deploy the app.
Any possible cause ?

**Comment by josephdecock** [comment]
You should look at the http requests and see which request is failing. You might also look at the logs of the associated component.

**Comment by wantwi** [comment]
well after a successfully login, the only http request is the one to bring the user claims. Even though it returns with a status code 200, upon checking the response, it's retuning an html page as the response and there are no errors, just that the expected response should have been the user claims.

**Comment by wantwi** [comment]
I also realized that the cookie is not been set after login, hence the request is not going with the cookie, but on my local development environment, the cookie sets and  its part of my http request. What could be the possible cause?

**Comment by wantwi** [comment]
Issues resolved. I removed the prefix __ from the cookie  name ( form __Host-bff, to Host.bff)and it works.
