### ISSUE TITLE
Blazor webapp and redirect to connection page

### ISSUE THREAD

**Issue by LouisYNot** [DuendeSoftware/Support#742]
**Which version of Duende IdentityServer are you using?**  6.3.2

**Which version of .NET are you using?** .net core 7.0.6

It's not a bug.

I want my user redirect automatically to the duende connection page rather that clicking on Connect and then see the Dudende connectiuon page.

I try something but i'm redirect constantly (loop).

**Comment by josephdecock** [comment]
I'm not sure I'm totally following what your desired user experience is. If you just want the user to be prompted to log in when they need to be, take a look at our [sample](https://docs.duendesoftware.com/identityserver/v6/samples/bff/#blazor-wasm). If you click on the Fetch Data link on the left side, that page will automatically issue a challenge without the user needing to explicitly click on login, since that page requires authentication.

**Comment by louisbouchard** [comment]
Thank you Jospeh for your answer.  When I start my Bazor webapp I see the welcome page of my site and at the upper right coner I have Login.  I wonder if it's possibe to go directely to the login page of Duende rather see the welcome page.  Maybe something to do with route somewhere (like in Authentication.razor file).

**Comment by josephdecock** [comment]
If you put the [authorize attribute](@attribute [Authorize]) on your welcome page, you should get an immediate login as soon as the application loads.

**Comment by louisbouchard** [comment]
You RIGHT Joseph! So simple!  Thanks a lot for your precious help and your wonderful product!
