### ISSUE TITLE
How to get phone in Okta claims

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#745]
I'm using IdentityServer4/.NET 6.0 and Okta to implement SSO.

We are using Authorziation Code flow.

Here is my setup:

```
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddControllersWithViews()
        .AddNewtonsoftJson();
    services.AddAuthentication()
        .AddCookie("Cookies")
        .AddOpenIdConnect("oidc", "OpenIdConnect", options =>
        {
            options.GetClaimsFromUserInfoEndpoint = true; // doesn't work
            options.SignInScheme = "idsrv.external";
            options.SignOutScheme = "idsrv.external";
            options.Authority = "https://mysaas.oktapreview.com";
            options.ClientId = "0oa1ml149rjc2sybG0h2";
            options.ClientSecret = "secretHere";
            options.ResponseType = "code";
            options.Scope.Add("email"); // this works
            options.Scope.Add("phone"); // this doesn't work
            options.Events = new MyOpenIdConnectEvents();
        });
}
```

```
public class MyOpenIdConnectEvents : OpenIdConnectEvents
{
    public MyOpenIdConnectEvents()
    {
        OnTokenValidated = OnTokenValidatedImpl;
        OnUserInformationReceived = OnUserInformationReceivedImpl;
    }

    private Task OnTokenValidatedImpl(TokenValidatedContext context)
    {
        context.Success();
        return Task.CompletedTask;
    }

    private Task OnUserInformationReceivedImpl(UserInformationReceivedContext context)
    {
        // Never gets executed
        return Task.CompletedTask;
    }
}
```

This method is called via the `Login()` method:
```
private IActionResult ForwardToIdentityProvider(string returnUrl, string loginHint)
{
    var callbackUrl = Url.Action(nameof(Callback));
    const string provider = "oidc";
    var props = new AuthenticationProperties
    {
        RedirectUri = callbackUrl,
        Items =
        {
            { "scheme", provider },
            { "returnUrl", returnUrl },
            { "loginHint", loginHint }
        }
    };

    return Challenge(props, provider);
}
```

This is where I access the claims:

```
[HttpGet]
public async Task<IActionResult> Callback()
{
    var result = await HttpContext.AuthenticateAsync("idsrv.external");
    var claims = result.Principal.Claims.ToList();
    // Code omitted for brevity
    return Ok();
}
```

The claims object has this (notice there is no `phone` claim):
![image](https://github.com/DuendeSoftware/Support/assets/13111539/1c5689a5-39f6-4e07-8266-6655006e8a92)

You can see the scopes are in the URL:

![image](https://github.com/DuendeSoftware/Support/assets/13111539/84acac2b-b6a4-4c4b-96b3-f1aaa85b58e8)

I've set up the default authorization server in Okta to have a `phone` scope/claim:

![image](https://github.com/DuendeSoftware/Support/assets/13111539/236ad10a-93a8-42bc-a84f-363c5214f870)

![image](https://github.com/DuendeSoftware/Support/assets/13111539/abda0bce-2ada-470d-b955-16bd3118dc80)

I can see the `phone` coming through in the token preview:

![image](https://github.com/DuendeSoftware/Support/assets/13111539/18af11c4-2d0b-439e-9fec-3622c4366b4e)

Is `phone` meant to come through via the `UserInfoEndpoint`?

If so, since I have `options.GetClaimsFromUserInfoEndpoint = true`, why doesn't the `OnUserInformationReceivedImpl()` method get executed?

I noticed email comes through even without having set up a custom claim/scope in Okta.

How can I access the `phone` claim?

**Comment by brockallen** [comment]
Any claims coming back from an external IdP (Okta in your case) is for your callback logic to manage. This is state associated with your user, and IdentityServer doesn't know anything about it. The profile service is the extensibility point for IdentityServer to ask your logic to access this state (i.e. claims) for your user. So in short, you need to store any state coming back from Okta and make it available to your profile service. Does that make sense?

**Comment by DavidKlempfner** [comment]
I've been told the `phone_number` claim is to be taken from the `UserInfoEndpoint`.
How do I call that endpoint using configuration?
I set `options.GetClaimsFromUserInfoEndpoint = true` but the breakpoint I set in `OnUserInformationReceivedImpl()` is never hit.
I tried manually using Postman and can see the endpoint does work (but there is no phone claim), but I'd still like to be able to call this endpoint anyway:

![image](https://github.com/DuendeSoftware/Support/assets/13111539/1f136f3e-bf8a-4c98-bebd-d9914bf4479c)

**Comment by brockallen** [comment]
> I've been told the phone_number claim is to be taken from the UserInfoEndpoint.

If you're talking about the phone number coming from Okta, then you have to understand that it's the OIDC client code in your IdentityServer that would make this call to Okta. This should be done automatically by the Microsoft OIDC handler you have configured in your IdentityServer, and the result of that is that the OIDC handler creates this as a claim in the cookie issued as a result of the OIDC interaction. You can see that claim present in the screen shot you show above. Once that's all done, then the OIDC interaction from your IdentityServer to Okta is complete.

Now, if you're talking about the phone number coming from your IdentityServer to your client app, then that's where the IdentityServer profile service I mention above is invoked. And since IdentityServer doesn't know about your users' data, it's up to your profile service to "find" the phone claim value for the user. But given your Okta integration, this value is in the cookie in the user's browser. So what I said before still stands -- your callback logic needs to manage this state so that it gets from the cookie in the callback page to some store that your profile service can access. If you do that, then the user info endpoint in IdentityServer will be able to access it to return it to the client app via the OIDC protocol.

Hopefully this explains a bit better all the moving parts that are going on here.

**Comment by DavidKlempfner** [comment]
That clears things up. Thanks for the explanation.
So just to confirm, using `options.GetClaimsFromUserInfoEndpoint = true`, `OnUserInformationReceived` will only be executed if the client calls the Identity Server's `userinfo` endpoint, ie. it doesn't execute it when Identity Server calls Okta's `userinfo` endpoint?

**Comment by brockallen** [comment]
GetClaimsFromUserInfoEndpoint is called from whichever client to whichever token server the trust is configured for. And IdentityServer's userinfo endpoint only uses the profile service to find claims (typically from your store or however you implement it).

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by DavidKlempfner** [comment]
You can close it.
