### ISSUE TITLE
CORS policy malfunction

### ISSUE THREAD

**Issue by pudrik** [DuendeSoftware/Support#752]
**Which version of Duende IdentityServer are you using?**
v5

**Which version of .NET are you using?**
net6/net7

**Describe the bug**

When presented with the "login" options screen and entering a valid authentication duende returns a 400 and stops.

The CORS policy seem to malfunction, if you configure it using sample provided in the documentation 
https://docs.duendesoftware.com/identityserver/v5/tokens/cors/ and setting “*” as origin which should be same as anything.
however it does get a fail response pointing out 

[09:45:17 Debug] Duende.IdentityServer.Hosting.CorsPolicyProvider
CORS request made for path: /Account/Login from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint

for some reason * dont include null, reason for this is unknown the only additional thing i can see is the ReturnUrl has a relative path and not an absolute one unlike all the other arguments in the request.

**To Reproduce**

Create a Office-addin web based plugin that uses Duende
Install the Addin in Office365 online solution.
open the addin
Try to login.
Will fail once login button is pushed.

**Expected behavior**

Login should work and redirect back to the client app.

**Log output/exception with stacktrace**

[09:45:17 Debug] Duende.IdentityServer.Hosting.CorsPolicyProvider
CORS request made for path: /Account/Login from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint

**Additional context**

This works fine if you use a local installed version of Office instead of the Web one.

**Comment by brockallen** [comment]
> When presented with the "login" options screen and entering a valid authentication duende returns a 400 and stops.

The login page is 100% under your control and not built into IdentityServer, so you have the control to make it work any way you want and for any workflow you can. This is something you'd need to debug on your side. It sounds like you're trying to build it to work with an Ajax style client, so you'd need to configure your own CORS policies using the Microsoft CORS middleware for your UI endpoints.

> The CORS policy seem to malfunction, if you configure it using sample provided in the documentation
https://docs.duendesoftware.com/identityserver/v5/tokens/cors/ and setting “*” as origin which should be same as anything.
however it does get a fail response pointing out

The CORS policy built into IdentityServer is only for the pertinent IdentityServer endpoints, which excludes the UI endpoints as I hinted at above. The endpoints covered by the CORS policy are listed in the CORS options:

https://docs.duendesoftware.com/identityserver/v6/reference/options/#cors

And for completeness here's a list of all the protocol endpoints we expose: 

https://docs.duendesoftware.com/identityserver/v6/reference/endpoints/

Also, "*" is not an origin, so I would not expect that to work anyway.

**Comment by pudrik** [comment]
CORS policies and CSP policies are set up but i get the error once i press login as far as i understand it it then calls the internal endpoint /Account/login which is an internal mechanics?

our client uses your BFF component.

* is not a origin but is an alias for anywhere, however if i hardcode it to the correct urls i still get the same issue

**Comment by josephdecock** [comment]
The /Account/Login route is the default route that IdentityServer will redirect to when there is an interactive flow and the user needs to login. When IdentityServer redirects there it is basically handing off control from endpoints supplied by itself to a user experience that you build (or customize based on our quickstart ui). IdentityServer's CORS policies only apply to the protocol endpoints that IdentityServer implements. The UI's implementation is separate (as Brock says above). The debug message you're seeing is probably not the most relevant here, because it is just an informational message from our CORS stuff - it is saying "hey, I don't apply here because this route isn't a protocol endpoint". 

The way I would debug this is by looking at the network traffic. Which network request is returning a 400 response? Is it a protocol endpoint supplied by identity server? If so, you'll have other logs from identityserver to guide you to the real problem. Is it coming from your login page? If so, you'll have to debug that yourself.

**Comment by pudrik** [comment]
The error manifests itself in the Console window of firefox but looking in the network tab nothing is ever requested / transmitted anywhere. (tried in chrome too same issue)

To clairify this implementation works like it should when running the Web based application it also works when running as an addin in MS Office (word etc..) but only errors after the login screen appears and login is pressed when using it in Office365 online version. (Tried Excel / Word same error)

And i have set the CORS policy and correct CSP as previous mentioned, this is the reason i still think its a mechanical issue inside the duende package as it says origin is null, (ive even tried setting it to allowAnyOrigin in c#)

i dont get any exception or a stacktrace only the cryptic message from identity server console window and the error in the console window of the webbrowser.

Its kinda hard to debug the internal mechanics when it doesnt show any useful output.

**Comment by josephdecock** [comment]
CORS requests are not normally shown by most browser tools (https://bugs.chromium.org/p/chromium/issues/detail?id=995740#c1), so probably you are making an OPTIONS CORS preflight request and getting denied. That denial is not coming from IdentityServer, because IdentityServer's cors services only apply to protocol routes (basically, routes that start with /connect - /connect/token, /connect/authorize, etc). You need to create your own CORS policy for your login page separately.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by pudrik** [comment]
Still not resolved, link you point towards is related to chrome as far as i can see and i dont utilize chrome but firefox either case same issue with both. 
How can i enable better tracing inside duende so i can rule out that the error is 100% not duende?

Ive looked at the documentation but its at best described as lacking, as some parts arent even documented

**Comment by josephdecock** [comment]
You're already seeing the debug level log messages from identity server, so I don't think there's really any additional logging that you can add.

I still think that the issue is to do with the CORS policy for your login endpoint, which you need to build separately from the IdentityServer CORS options (which again only apply to the protocol endpoints provided by IdentityServer, not the login pages or other UI).

Microsoft's docs on CORS are [here](https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-7.0#cors-with-named-policy-and-middleware). What CORS policies are you creating?

**Comment by josephdecock** [comment]
Also, I'd really appreciate if you could tell me more about which parts of the documentation you found lacking, so that I can improve them for you and the rest of the community.

**Comment by pudrik** [comment]
well i havent looked at everything but to name one thing which ive already pointed out to Dominick is that its bad documentation to explain how windows authentication is possible from for instance linux as the documentation meantioned this but didnt show any examples or any source how to do this while showing examples for every other thing meantioned on the same page.

**Comment by pudrik** [comment]
regarding the CORS issue ive done what is described on ms page and also duende's page i also utilize a CSP policy. and as mentioned earlier this works well when operating on a local hosting environment same / multiple machines different uris.

Only place i cant get it to work is when i try utilizing the software in office365 online version (part of the software is made as a office web addin) it does work like it should if used in a local installation but not in their cloud solution thats where i see this error that dont make any sense as the policys have been setup and work on all other implementations.

Flow goes MS -> Addin -> ourproduct -> duende identity server -> stops, this is the reason why i keep persisting that this is most likely some logic issue inside the mechanics. 
Might also point out that ive tried local login / azure ad and windows all fail when they return to the duende implementation.

if there is any kind of sample that proves me wrong regarding this testing scenario feel free to point me towards it.

**Comment by josephdecock** [comment]
Looking at this again, the thing that occurs to me now is that CORS problems on the login page often happen with javascript code makes a request (a fetch or ajax request) to the /bff/login endpoint. When that happens, the login endpoint issues an oidc challenge, so it returns an http redirect, which the fetch or ajax request will attempt to follow. That redirect will redirect on to the /Account/Login page, and following that redirect can trigger a CORS request. But ultimately, that CORS problem isn't the real problem, because the fetch/ajax request to the bff/login endpoint doesn't need to get the /account/login page in the first place.

So, first of all, I would make sure that your login page's javascript is redirecting to /bff/login, rather than making a fetch request to it.

And if it is, I wonder if the Office 365 mechanics extension's mechanics are interfering with things. If the redirect to the bff/login endpoint is already in place, can you describe a little more how the O365 extensions work? I have an impression that they're running in an iframe, but I'm not an office expert and could use some more context.

**Comment by pudrik** [comment]
To be more technical https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/word-tutorial for a boiler plate office web addin.

it does run in somekind of frame, need to have the frame-ancestors CSP set to 'self' https://*.sharepoint.com https://*.office365.com https://*.office.com https://*.live.com; for it load.
you also need to have the manifest.xml configured with all needed appdomain under the appdomains tag. Duende application being the one of importance, and organisation sharepoint url, and

https://aadfs.msauth.net
https://login.microsoftonline.com

more depending of authentications method (Azure) if the the site isnt listed here with it will spawn a popup when trying to open the site. (breaks the app) and its very picky if you utilize custom ports beyond they need to be included.

once it loads our product it checks if youre authorized if not it redirects to our duende implementation (this part works)
Duende shows up i can select 3 types of login local, windows ,azure. Doesnt really matter which one i choose once i input l/p and try to login it tosses the error. 

And as mentioned before the super odd part is this works in the local office install but not in their "cloud" version.

Im sorry if the response is slow on progress as the vacation season is currently ongoing in sweden so many things to mend.

**Comment by pudrik** [comment]
its based on the quickstart ui, razor pages. not much difference to the standard implementation except for our code is based on older version from around beginning of 2021

**Comment by josephdecock** [comment]
In that case, it doesn't sound like there is any ajax/fetch requests on the login page itself, so I assume there must be some added complexity from O365 (that I suppose is consistent with the fact that the issue only shows up with them). 

Can you share the CORS policy that you're using on the /Account/Login page please?

**Comment by josephdecock** [comment]
@pudrik - yes please do share a basic sample that reproduces the issue. Thanks very much!

**Comment by pudrik** [comment]
@josephdecock ive uploaded a demo repo with instructions how to run it to manifest the error. ive also invited you to the repo as its set private.

**Comment by josephdecock** [comment]
@pudrik thanks for the demo! I believe what is happening is that the login page isn't  being sent the antiforgery cookie because the antiforgery cookie by default sets the samesite property to strict, and thus won't be sent in a framed request. The anti-forgery cookie is on by default in razor pages (like the login page) to prevent cross site request forgery attacks. When the login page is sent a request without the cookie, the antiforgery middleware prevents the request from ever reaching the page itself, and you just get a 400 error (often with not much of anything else in the logs). 

You can solve this problem by adding the following code to make the antiforgery cookie less strict about where it will be sent:

```
        builder.Services.AddAntiforgery(options =>
        {
            options.Cookie.SameSite = SameSiteMode.None;
            options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
        });
```

Relaxing the way that the antiforgery cookie is handled is safe to do. The antiforgery tokens have been around since before the samesite cookie attribute was invented. They are designed to mitigate CSRF in a context where all cookies are samesite=none, so this should be safe.

**Comment by pudrik** [comment]
Thank you that seem to have solved the issue with duende stopping, 

i did however notice that the authentication respisne dont seem to be passed to the return site when running it in offce365.org while it works locally, do you have any idea what might be the cause of that ?

**Comment by pudrik** [comment]
btw feel free to use the demo as a sample on how to use duende auth with office. (Just remove our domains from the manifest) :)

**Comment by pudrik** [comment]
Nevermind i solved it, i forgot to change the cookie settings in FrontendHost's Program.cs to be SameSiteMode.None also.

Thank you very much for you assistance.
