### ISSUE TITLE
Federation gateway: idsv-identity vs client-identity

### ISSUE THREAD

**Issue by Tobias-08** [DuendeSoftware/Support#758]
**Which version of Duende IdentityServer are you using?**

6.3.2

**Which version of .NET are you using?**

.NET 6

**Question**

We are using IdentityServer as a federation gateway for multiple external logins. Clients request the external claims and some additional claims that are added in idsv via `OnTokenValidated`. In this context I am wondering what the role of the idsv-internal identity/cookie is in contrast to the one created on the client's side.

- Is the idsv-internal identity only needed for SSO purposes?
- What claims should be stored in the idsv-internal identity? Or: How do the claims in the idsv-internal identity relate to the claims delivered to the client? Even in a SSO scenario the client seems to get all requested claims even if they are not part of the idsv-internal identity. How does that work? 

Thanks!

**Comment by josephdecock** [comment]
The cookie at IdentityServer establishes the session at IdentityServer, and its main use is to allow for SSO. The claims that are emitted in tokens are controlled by the profile service. The default profile service takes the claims in the identity server session and filters them to only include claims that were requested by the client application by requesting scopes and/or including resource indicators.

If you are using ASP.NET Identity to as your user store, our ASP.NET Identity integration changes the profile service so that the user and default profile data is retrieved from ASP.NET Identity. That might be why you're seeing some claims in the tokens that aren't in the cookie.

Another possibility is that you have a custom implementation of the profile service that is manipulating the claims that are emitted. For more details on the profile service, see [here](https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/).

**Comment by Tobias-08** [comment]
@josephdecock Thanks!

We are not using ASP.NET Identity and we do not have a custom profile service.

I am still wondering why clients in the mentioned SSO scenario (and without an additional roundtrip to the external provider) seem to get additional claims (they asked for) which the IDSV-session doesn't seem to have (as configured in `/ExternalLogin/Callback`). Does IDSV save the full reply/claim set of the external provider anywhere else (independent of the session cookie)?

But at the moment this is more a problem in my understanding because it works in the end as intended.

**Comment by Tobias-08** [comment]
@josephdecock Thanks! I'll try that and investigate further.

**Comment by josephdecock** [comment]
Sounds good - please do let us know what you find out.

**Comment by Tobias-08** [comment]
@josephdecock Logging via the mentioned events helped to understand what is happening under the hood. The behaviour is like you described above. So no more questions here. Thanks!
