### ISSUE TITLE
[Question] Using a local identity server as an external provider to another local identity server

### ISSUE THREAD

**Issue by forrestab** [DuendeSoftware/Support#759]
**Which version of Duende IdentityServer are you using?**
6.1.5

**Which version of .NET are you using?**
net6

**Question**

Im a little confused and need some help clarifying some things. Currently we have 2 identity providers, 1 for our customers and 1 for our employees. We now have a requirement that employees need to login into the customer applications and my first thought was to register the employee-idp as an external provider to the customer-idp.

I started following the external provider samples and im making some assumptions such as registering the customer-idp as a client in the client* tables for the employee-idp and statically registering the custom scheme in the customer-idp as:

```
.AddOpenIdConnect("employee", "Employee Login", options =>
{
    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
    // Authority
    // ClientId
    // ClientSecret
})
```

So,

* Am I doing this right?
* I noticed in the external provider samples for google registration there is a comment about setting the "redirect URI to https://localhost:5001/signin-google", but I cant for the life of me find the accompanying view/razor page in the sample, so Im not sure what im missing?

*Edit*: fixed who is the client of what, ie customer-idp is a client of employee-idp.

**Comment by forrestab** [comment]
After reading other support issues and the documentation a couple more times, it looks like external provider redirect urls should be different, but ultimately end up at the /callback page where verification, mapping and user is signed in. 

Do I have this right? If so, if we have specific logic that needs to happen for a specific external provider, do we just:

```
// Callback.cshtml.cs

public async Task<IActionResult> OnGet()
{
    // snip
    if (provider == "employee")
    {
        // employee provdier specific logic
    }
    // snip
}
```

And im sorry for overloading with so many questions, but if I need to gather more information from the user after they have successfully logged in with an external provider, do I first sign them in on the callback page and redirect them to the additional info page where I then sign them in again with the additional claims?

**Comment by AndersAbel** [comment]
Yes, that looks right.

The `/signin-google` and similar paths are handled internally by the authentication handler, that's why you do not see any razor page or controller for those paths. For Open ID connect the default path is `/signin-google`. If you only have one registered scheme of each type (e.g. call `AddOpenIdConnect` once), you do not have to do anything about that. But, if you have multiple schemes using OpenID Connect, you need to give them each a unique path such as `/signin-employee` and `/signin-customer`. If you don't do that, only the first registered scheme will work as that will grab all the responses to the configured path. And the first scheme will not recognize the responses from the second Idp and reject them.

The `signin-XXX` paths handle the protocol level processing of the incoming authentication response. There are events/notifications that offer some limited post-processing capabilities, but they cannot not show UI.

Our templates instead use the external callback pattern where the user is redirected to the external login callback for post processing after the protocol level processing is done. You are right in that a switch/if on the provider type is the right way to do provider specific post processing in the callback.

**Comment by forrestab** [comment]
@AndersAbel thanks for the explanation and I'm glad I was going in the right direction. 

One last question, when I redirect from the callback page to an "additional info" page, it would be that "additional info" page's responsibility to sign the user in, right? Essentially completing what the callback page would have done if the redirect didn't occur? I'm pretty sure the answer is yes, but want to make sure there isn't anything I'm missing.

**Comment by AndersAbel** [comment]
Yes, you're right. If you want to display additional UI during the login process, you would redirect to that from the callback page and it would be the last page in that flow that calls SignInAsync to establish the session. You can call AuthenticateAsync on the external scheme in those pages to get hold of the external identity and the authentication properties.

It's possible to have different callbacks for different schemes the way you suggest, yes. One important thing though is to validate the scheme from the authentication properties in those callbacks. A malicious user could sign in using one external provider and then manually change navigate to the callback belonging to another scheme. Or simply put, the scheme as part of the path is untrusted user input. The scheme from the authentication properties however is trusted data as it was set in the challenge and then protected by encryption/signing.

**Comment by forrestab** [comment]
@AndersAbel perfect! I figured there was a potential vulnerability with different callbacks for schemes, but couldn't figure out how to validate those callbacks. Thanks for providing the solution.

This has been very informative and I appreciate the feedback.
