### ISSUE TITLE
Infinite loop when acr_values:idp is present in return url

### ISSUE THREAD

**Issue by pampua84** [DuendeSoftware/Support#761]
Hello, 
in my application there is the possibility of being redirected directly to an external provider bypassing the page where the email is entered. In reality, in the OnGet method of the email page, I check the presence of the IdP value in the acr_values and if it is populated, I launch the challenge directly. The problem is that once I go back to the method that manages the callback, doing the Redirect with the returnUrl, I enter an infinite loop where the OnGet method is called again. Do I have to clean up the acr_values by hand or am I doing something wrong?

**Comment by josephdecock** [comment]
The returnUrl on your external login callback page should not take you back to the login page. Instead, you want it to be a redirect back into the endpoints that are provided by identity server. IdentityServer supplies that url as the returnUrl parameter when it initially redirects to your login page. You should persist that return url so that you can redirect to it after the external login.

Our quickstart UI keeps track of it like this:

```cs
\\ The Login Page forwards it to the external login challenge page
        if (View.IsExternalLoginOnly)
        {
            // we only have one option for logging in and it's an external provider
            return RedirectToPage("/ExternalLogin/Challenge", new { scheme = View.ExternalLoginScheme, returnUrl });
        }
```

```cs
\\ The External login page validates the url and saves it in the authentication properties
        if (string.IsNullOrEmpty(returnUrl)) returnUrl = "~/";

        // validate returnUrl - either it is a valid OIDC URL or back to a local page
        if (Url.IsLocalUrl(returnUrl) == false && _interactionService.IsValidReturnUrl(returnUrl) == false)
        {
            // user might have clicked on a malicious link - should be logged
            throw new Exception("invalid return URL");
        }
            
        // start challenge and roundtrip the return URL and scheme 
        var props = new AuthenticationProperties
        {
            RedirectUri = Url.Page("/externallogin/callback"),
                
            Items =
            {
                { "returnUrl", returnUrl }, 
                { "scheme", scheme },
            }
        };

        return Challenge(props, scheme);
```
```

**Comment by pampua84** [comment]
I debugged the code a bit and practically when I land in the class `AuthorizeEndpointBase`, precisely at the following portion of code:
```
if (interactionResult.ResponseType == InteractionResponseType.UserInteraction)
{
      if (interactionResult.IsLogin)
      {
         return new LoginPageResult(request, _options);
      }
      if (interactionResult.IsConsent)
      {
         return new ConsentPageResult(request, _options);
      }
      if (interactionResult.IsRedirect)
      {
         return new CustomRedirectResult(request, interactionResult.RedirectUrl, _options);
      }
      if (interactionResult.IsCreateAccount)
      {
         return new CreateAccountPageResult(request, _options);
      }
}
```

I enter the if of the login, but in reality I'm doing a redirect. 
All this is due to the fact that in the class `AuthorizeInteractionResponseGenerator` in the following code:

```
// check if idp login hint matches current provider
var idp = request.GetIdP();
if (idp.IsPresent())
{
   if (idp != currentIdp)
   {
         Logger.LogInformation("Showing login: Current IdP ({currentIdp}) is not the requested IdP ({idp})", currentIdp, idp);
         return new InteractionResponse { IsLogin = true };
   }
}
```

 it is set that it is a login, infact i have this log:
 
> Showing login: Current IdP (local) is not the requested IdP (soffolocal) 

  Can you please help me figure out how to fix this?

**Comment by josephdecock** [comment]
> ```
>    if (idp != currentIdp)
>    {
>          Logger.LogInformation("Showing login: Current IdP ({currentIdp}) is not the requested IdP ({idp})", currentIdp, idp);
>          return new InteractionResponse { IsLogin = true };
>    }
> ```

The interaction response generator's responsibility is to decide if IdentityServer needs to show a login page or other interactive page. This part of the generator that you've found is checking that the scheme that you have signed into is in fact the requested scheme. Since they don't match, IdentityServer is trying to log you in again.

When you pass `acr_values=idp:soffoLocal`, that means, "call `ChallengeAsync("soffoLocal")`". If your code that finds the acr value and challenges is instead challenging the local scheme, then you'd end up in this state. 

Another way this might be happening is that after you sign in externally, there should be an intermediate step where external identities are mapped onto internal ones, and this step crucially needs to keep track of the identity provider. IdentityServer is looking for that in a claim named "idp" - that's where the `currentIdp` value comes from.

Our quickstart UI's external login callback page captures that information like this:
```cs
        // capture the idp used to login, so the session knows where the user came from
        localClaims.Add(new Claim(JwtClaimTypes.IdentityProvider, externalResult.Properties?.Items["scheme"] ?? "unknown identity provider"));
```

**Comment by pampua84** [comment]
Thanks a lot, it works perfectly.
