### ISSUE TITLE
"token_type" property is always not available in the response for Refresh token request with v6.3.1

### ISSUE THREAD

**Issue by skuppusamy-intermedia** [DuendeSoftware/Support#775]
Duende IdentityServer -> v6.3.1

.NET -> 6.0

"token_type" property is always not available in the response for Refresh token request with v6.3.1
Response is success (200), but only problem is "token_type" property is missing.

Request parameters
"grant_type" : "refresh_token",
"client_id": "xyz********",
"client_secret":"cs*******",
"scope" : "offline_access openid",
"refresh_token" : "reft**********"

Actual response is below
{
    "id_token": "id******",
    "access_token": "acc*****",
    "expires_in": 3600,
    "refresh_token": "reft***********",
    "scope": "openid offline_access"
}

Expected response is below(Per previous version -> v6.1.0)

{
    "id_token": "id******",
    "access_token": "acc*****",
    "expires_in": 3600,
    "token_type": "Bearer",
    "refresh_token": "reft***********",
    "scope": "openid offline_access"
}

Can you please help with this?

**Comment by josephdecock** [comment]
Looking at the code that generates responses to the token endpoint, the only way I see that the token_type could be missing is if the `ITokenResponseGenerator` failed to set the `TokenResponse.AccessTokenType`. The default implementation did change in 6.3, because we added DPoP support. So, the `AccessTokenType` there might now be either "DPoP" or "Bearer", but our default implementation always returns something:

```
AccessTokenType = request.ValidatedRequest.ProofType == ProofType.DPoP ? OidcConstants.TokenResponse.DPoPTokenType : OidcConstants.TokenResponse.BearerTokenType, 
```

Do you have a customization of the `ITokenResponseGenerator` or its default implementation `TokenResponseGenerator`?

**Comment by josephdecock** [comment]
Any update here?

**Comment by skuppusamy-intermedia** [comment]
Hi @josephdecock 

Thanks for the information.
Actually, we had extended the class "TokenResponseGenerator", As you mentioned above, I just added the "AccessTokenType" property value also in the return object("TokenResponse") of a method "ProcessRefreshTokenRequestAsync". That solved the issue. 
Thanks Again.
