### ISSUE TITLE
Support for WebAuthn and/or PassKeys

### ISSUE THREAD

**Issue by jimmyvdberg** [DuendeSoftware/Support#779]
**Which version of Duende IdentityServer are you using?**
Duende Enterprise Edition, 6.1.7

**Which version of .NET are you using?**
.NET 6.0

**Describe the question**
Do you have any documentation about passkey and/or WebAuthn support? Or do you have something planned to implement this?
Or is it expected that we should implement it ourselves using ASP.NET Identity?

**Additional context**
I did found this implementation from Rock Solid Knowledge. https://fido.identityserver.com/

**Comment by brockallen** [comment]
Hi @jimmyvdberg. The UI and any/all user workflows for authentication are deliberately not part of the IdentityServer engine. They are designed as an extensibility point so that they can be customized and controlled to work exactly as a customer's requirements mandate. So as such, anything related to the user's credentials (including using FIDO/WebAuthn) is not something on our roadmap to provide. I'd look to Microsoft and ASP.NET to provide this (e.g. in their ASP.NET Identity layer).

**Comment by jimmyvdberg** [comment]
Thanks @brockallen for the clear explanation. Makes sense.
