### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by SamPaquin** [DuendeSoftware/Support#781]
**Which version of Duende IdentityServer are you using?**
2.0.2

**Which version of .NET are you using?**
4.8.4084.0

**Describe the bug**
Proxies aren't working. It may be and most likely is something in our code, but we are having trouble determining where to make the change.

**To Reproduce**
You probably won't be able to reproduce the issue, as the code base isn't public.

**Expected behavior**
Ideally, the website would be proxying correctly.

**Log output/exception with stacktrace**
'Request could not be proxied.\n\nThe added or subtracted value results in an un-representable DateTime. (Parameter 'value')\n\n   at System.DateTime.ThrowDateArithmetic(Int32 param)\r\n   at Duende.AccessTokenManagement.DistributedClientCredentialsTokenCache.SetAsync(String clientName, ClientCredentialsToken clientCredentialsToken, TokenRequestParameters requestParameters, CancellationToken cancellationToken)\r\n   at Duende.AccessTokenManagement.ClientCredentialsTokenManagementService.<>c__DisplayClas…ions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)\r\n   at AspNetCore.Proxy.HttpExtensions.ExecuteHttpProxyOperationAsync(HttpContext context, HttpProxy httpProxy)'

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
This is a somewhat misleading error message coming from the Microsoft distributed cache that access token management relies on. The call to the cache is failing because the expiration time is under-flowing.

Access tokens are stored in distributed cache with an absolute expiration time the same as the expiration time of the token itself, less a small, configurable buffer (this makes it so that  we tokens are acquired proactively, a little before they expire):

```
var cacheExpiration = clientCredentialsToken.Expiration.AddSeconds(-_options.CacheLifetimeBuffer);
```

This calculation can under flow if  the expiration of the token is too low, for example, if your token somehow didn't have an expiration set, you'd probably get the default = DateTime.MinValue, and then subtracting the buffer would definitely under flow. It could also happen if your CacheLifetimeBuffer is configured to a really unreasonably large value. Normally the buffer should be just minutes or seconds - it is just the amount of time before the token expires that you want to proactively go get a new token to ensure that you never use an expired token.

**Comment by AndersAbel** [comment]
@SamPaquin did Joe's suggestion help you resolve? Do you have any update on this?

**Comment by SamPaquin** [comment]
Hey Anders –  The token endpoint was giving us back a 401 and we were misreading it. Thanks for your help! Sam Paquin From: Anders AbelSent: Wednesday, July 26, 2023 6:22 AMTo: DuendeSoftware/SupportCc: SamPaquin; MentionSubject: Re: [DuendeSoftware/Support] Proxy Issue (Issue ***@***.*** did Joe's suggestion help you resolve? Do you have any update on this?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
