### ISSUE TITLE
Two identical responses from the Authorize-Endpoint caused by User clicking accept consent button multiple times

### ISSUE THREAD

**Issue by stephmueller** [DuendeSoftware/Support#800]
**Which version of Duende IdentityServer are you using?**
6.3.0

**Which version of .NET are you using?**
.NET 6

**Describe the (bug) / question**

tldr; Does sending back 2 times the exact same response to the client_redirect_uri inside the same second from the Authorize-Endpoint violate the oicd/oauth2.0 protocol or is this a valid possible scenario?

 Description:
In our setup we have an external identity provider which federates the authentication to our own identity provider. Our own identity provider is based on the Duende Identity Server framework. In our login-flow we use nearly 1:1 the provided templates/ implementation examples from Duende which are specifically the Login View/Controller, 2FA View/Controller and the Consent-Screen View.

We discovered in some rare cases (slow connection?!), that the Enduser could potentially hit the Accept Consent Button twice or multiple times and a second request is then sent back to the redirect_uri of the first identity provider (which is not under our control). The first identity provider does not accept that and sends back to the client that it is not authorized.

What is your advice? Should a second response/callback with the exact same parameters be avoided at all costs? Or should the first Identity Provider (which is not based on Duende) be able to handle is?

**To Reproduce**

Starting the Client-App in a Browser, where inside the Browser-Dev-Tools the 'Network conditions' are throttled down to a slow connection. Having a consent screen during the login process and hit multiple times the Accept-consent button.

**Comment by josephdecock** [comment]
I recommend that you add javascript to these pages that will disable the button after it is clicked. The login and consent pages are completely under your control, so feel free to change them in any way. We don't include javascript like that in the stock versions, just because in many cases it wouldn't be necessary (you have to be federating in the way that you are, and you have to have a slow network connection and impatient users), so our judgement has been to keep the stock consent screen simple, but if you're having that problem, there's no harm in customizing the pages.

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
