### ISSUE TITLE
Mixing [AllowAnonymous] with [Authorize] doesn't always yield a context User

### ISSUE THREAD

**Issue by fictus** [DuendeSoftware/Support#804]
Hello. In one of our client webapps we recently added a public View as to allow non-authenticated users to view this page. We are using the [AllowAnonymous] attribute to accomplish this.

The issue is that we want to dynamically assign a different "_Layout" depending if the user is logged in or not. But when we check to see if the context user is Authenticated we don't get consistent results. sometimes the page will contain a context User but most of the time it will not.

We found that if we FIRST navigate to the Home View and then from there to the public View then we always have a context User, but when we try to access the public View say from a direct href link then most of the time the context User is not available.

What is the correct way to set up a public View inside a client app so that we can see if the user is Authenticated or not?

Version of Duende IdentityServer we are using is: 6.3.3
Version of .NET core: 6.0

Thank you

**Comment by josephdecock** [comment]
If you're not getting a user in the context, that probably means that client application is not sending its session cookie as part of the request. Normally, the authentication middleware reads the incoming session cookie, and uses that create the user. And the most common way for that to fail is for the cookie to not be sent by the browser. The first thing I would check, if you're getting these failures when you're coming from an external site, is if the auth cookie isn't being sent because it is configured as SameSite=strict, and you're navigating across sites. In general, I would debug this using the browser dev tools, and try to make sure that the calls to your endpoint at the client app are in fact sending a session cookie. If they're not, then the dev tools will often log an explanation.

**Comment by fictus** [comment]
I might in fact have SameSite=strict. I will follow your suggestion and post my progress here.

Thank you.

**Comment by josephdecock** [comment]
Sounds good! Let us know how it goes.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
