### ISSUE TITLE
Dynamic Identity Provider

### ISSUE THREAD

**Issue by AnBz03** [DuendeSoftware/Support#806]
**duende identity server 6**

**7**

**the dynamic identity provider**

when you restrict an identity provider for a specific client it doesn't work (it's saved on the database correctly but on the UI it still displayed)

**for example if you disable an identity provider A for the Client 1 all the data will be stored correctly on the data base but when you login to the client 1 the option of login with an identity Provider A still existe*

I think the issue is here on the quick start provided by you

```
            if (client.IdentityProviderRestrictions != null && client.IdentityProviderRestrictions.Any())
            {
             providers = providers.Where(provider =>client.IdentityProviderRestrictions.Contains(provider.AuthenticationScheme)).ToList();
            }
the condition on where is wrong is should be :
(
!provider =>client.IdentityProviderRestrictions.Contains(provider.AuthenticationScheme)
)
```

**Comment by josephdecock** [comment]
The semantics of `IdentityProviderRestrictions` are, "These identity providers are the only ones that you can use. You are 'restricted' to only using them." I get why you might think that from the name that the semantic is "You are 'restricted' from using these providers, and may not use them", but our intention is for the former rather than the latter, and changing it now would be a breaking change.
