### ISSUE TITLE
Error unprotecting key with kid

### ISSUE THREAD

**Issue by rwb196884** [DuendeSoftware/Support#812]
Any idea what this is about? (The stack trace points at you ;p )

```
Error 2023-08-02 09:11:44
[Error] @ 02 Aug 09:11:44: Error unprotecting key with kid 25B3761F2BFFDBF5D7D7E381CBA1BDE7.
The key {310caacf-0262-420f-b173-3a1dbbc19a0d} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetAllKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435
ConnectionId    : 0HMSJ5V6IUF2P
kid             : 25B3761F2BFFDBF5D7D7E381CBA1BDE7
ParentId        : 0000000000000000
RequestId       : 0HMSJ5V6IUF2P:0000000F
RequestPath     : /.well-known/openid-configuration
SpanId          : 9a06f1d2d2c23ad5
TraceId         : a8bfc6d01e244c47ee4cf579d0f0085c
```

**Comment by josephdecock** [comment]
This error indicates that IdentityServer is failing to read one of its signing keys due to a data protection failure.

IdentityServer needs cryptographic keys, called signing keys, to sign tokens such as JWT access tokens and id tokens. These keys are critical secrets for IdentityServer because a valid signature provides integrity and non-repudiation guarantees that allow client applications and APIs to trust those tokens. 

You can manually configure signing keys, but by default IdentityServer will manage signing keys for you. The signing keys that IdentityServer generates are protected at rest using ASP.NET's data protection feature. Data protection is a separate cryptographic tool built into ASP.NET that signs and encrypts data. ASP.NET data protection has its own cryptographic keys, called data protection keys, that are  managed separately from the signing keys that IdentityServer uses. The data protection keys can cause problems if you have a signing key stored in your signing key store, but try to decrypt it without the data protection key that encrypted it.

There are several ways that this can occur:

1. In load balanced environments, every instance of IdentityServer needs to be configured to share data protection keys. Microsoft has extensive docs [here](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview) describing how to configure storage and protection of data protection keys.
2. Signing keys could be generated in a (local) development environment and then accidentally included into the build output. If your automatically managed keys are stored on disk, which is the default, you should exclude the ~/keys directory from source control and make sure keys are not included in your builds. Note that if you are using our Entity Framework based implementation of the operational data stores, then the keys will instead be stored in the database.
3. Data protection creates keys isolated by application name. If you don't specify a name, the content root path of the application will be used. But, beginning in .NET 6.0 Microsoft changed how they handle the path, which can cause data protection keys to break. Their docs on the problem are [here](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview#setapplicationname), including a work-around where you de-normalize the path. Then, in .NET 7.0, this change was reverted. The solution is always to specify an explicit application name, and if you have old keys that were generated without an explicit application name, you need to set your application name to match the default behavior that produced the keys you want to be able to read.
4. If your IdentityServer is hosted by IIS, special configuration is needed for data protection. In most default deployments, IIS lacks the permissions required to persist data protection keys, and falls back to using an ephemeral key generated every time the site starts up. Microsoft's docs on this issue are [here](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-7.0#data-protection).

**Comment by rwb196884** [comment]
Can it just be turned off? 'Seucirty' that stops things from working is useless.

**Comment by josephdecock** [comment]
Unfortunately no, you are going to need to configure data protection -  if that's something that almost all asp.net applications already need to do - identity server isn't imposing that on you.

While technically you _can_ turn off automatic key management and disable data protection in the persisted grants store and other places where identity server uses data protection, that will significantly increase the attack surface of your identity server implementation and won't actually remove your dependency on asp.net data protection. Asp.net depends on data protection to secure any value that it round trips to the browser. Notably your asp.net authentication cookies (among other things) are data protected, so if you have data protection problem, you will be unable to authenticate many of the requests to your systems. Really just by using asp.net at all, you have this dependency on data protection, and without it being configured, your users will probably will have lots of issues.

**Comment by rwb196884** [comment]
So if it can't be turned off then is there a way to make it work? Or at least stop spamming error messages?

**Comment by josephdecock** [comment]
Please follow the troubleshooting steps from my first response. 

To expand on that a bit:

1. If you're load-balanced, you need to configure each node to share a data protection key. This means that you have to decide where to store your data protection keys and how to protect them. If you're using azure or aws, there are plugins to the data protection system that make it easy to use those platform's key vaults. You can also store data protection keys on a shared disk or in a database, and protect the keys with a certificate. You would then need to store and handle the certificate that protects the data protection keys with the same sensitivity as you would a TLS certificate or similar. See my link under item 1 above to microsoft's docs on this.
2. If you have the keys directory in your source control/in your build output, you need to remove that from the deployed artifacts and add the keys directory to .gitignore. 
3. If you recently upgraded .NET versions, and didn't set an application name in the data protection system, .NET made changes to the default behavior of data protection that cause different versions of .NET to use different data protection keys. See the link under item 3 above for more info and work-arounds.
4. If you're hosted in IIS, then there are special considerations specific to that platform. You have to give IIS more permissions in order for it to store and retrieve data protection keys. Again, see my link under item 4 from my original answer for specifics.

**Comment by josephdecock** [comment]
@rwb196884 just wanted to check in with you about this issue, since we haven't heard from you in a while. Did you get your data protection configuration sorted out?

**Comment by rwb196884** [comment]
Thanks for checking; just am trying to do too many things at once.
No progress on this.
I've set up an Azure storage blob and am doing
``
    builder.Services.AddDataProtection()
        .SetApplicationName(trimmedContentRootPath)
        //.PersistKeysToAzureBlobStorage(new Uri(aspNetCoreDataProtectionOptions.BlobUriWithSasToken))
        .PersistKeysToAzureBlobStorage(aspNetCoreDataProtectionOptions.ConnectionString, aspNetCoreDataProtectionOptions.ContainerName, aspNetCoreDataProtectionOptions.BlobName)
        .ProtectKeysWithAzureKeyVault(new Uri(aspNetCoreDataProtectionOptions.KeyIdentifier), new DefaultAzureCredential())
        ;
```
with config
```
  "AspNetCoreDataProtection": {
    "ConnectionString": "DefaultEndpointsProtocol=https;AccountName=x;AccountKey=x=;EndpointSuffix=core.windows.net",
    "ContainerName": "identity-data-protection",
    "BlobName": "identity-data-protection-blob",
    "BlobUriWithSasToken": "SECRET--Does-not-work",
    "KeyIdentifier": "https://x-key-vault.vault.azure.net/keys/identity-data-protection/x"
  }
```

Tha SAS token thing simply does not work -- this thing seems to be pretty broken by MS

But I'm still getting spammed with these error messages.

**Comment by josephdecock** [comment]
Okay, sorry to hear that. Since the next step is to work with azure, and there's not more to do that is IdentityServer specific, is it ok if we close this issue? We can always reopen if necessary.

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.

**Comment by rwb196884** [comment]
Have you ever witnessed this working?

**Comment by AndersAbel** [comment]
Yes we have. As Joe writes above, Asp.Net Core Data Protection is an integral part of the Asp.Net Core system. Any Asp.Net Core application (except maybe the most simple static web site) requires working data protection.

As this is a general Asp.Net Core concept/issue and not directly related to IdentityServer it needs to be solved with the hosting solution used. When hosted on Azure, the next step to get this working would be to contact Azure's support.

**Comment by rwb196884** [comment]
![image](https://github.com/DuendeSoftware/Support/assets/12090617/e30826f5-28eb-4d3e-8a19-5b3434c902a4)

**Comment by rwb196884** [comment]
Turns out it can be disabled. https://medium.com/swlh/how-to-disable-data-protection-in-asp-net-core-cdf7cad28509
