### ISSUE TITLE
BFF.Yarp forward access tokens with limited access per route

### ISSUE THREAD

**Issue by agerchev** [DuendeSoftware/Support#817]
**Which version of Duende BFF are you using?**
2.1.1
**Which version of .NET are you using?**
7.0
**Question**

Hello, 

What is the proper way (if any) to configure BFF.Yarp so that it can issue and forward access tokens with more limited access for specific route - with different audience and specific scopes for example. I cannot see that kind of logic in AccessTokenTransformProvider. Am i missing something ?

**Comment by josephdecock** [comment]
Customizing access tokens on a per-route basis is not something that we support in the BFF.Yarp package. However, in the most recent release of the BFF, we added a new abstraction to our simple http forwarder that allows you to specify how to retrieve an access token on a per-route basis. This new abstraction is the IAccessTokenRetriever. We discuss it in our docs [here](https://docs.duendesoftware.com/identityserver/v6/bff/extensibility/tokens/#per-route-customized-token-retrieval), and have a sample using it to perform impersonation [here](https://docs.duendesoftware.com/identityserver/v6/samples/bff/#token-exchange-using-the-iaccesstokenretriever). If you're able to use the simple http forwarder instead of the full yarp, that might be a good option for you. Otherwise, we can look into allowing the use of the access token retriever from yarp routes in a future release.

**Comment by agerchev** [comment]
I am not sure whether right now we can use the simple http forwarder. 
I was thinking that we can reimplement the AccessTokenTransformProvider so that instead of calling transformContext.HttpContext.GetManagedAccessToken(tokenType, optional) directly, i can call the IAccessTokenRetriever in a similar way like simple http forwarder implementation. I suppose this is your view for future changes or I am missing something ? 
(I am asking so that we can be more aligned with your future releases)

One more question, in the sample with ImpersonationAccessTokenRetriever you are calling RequestTokenExchangeTokenAsync directly, and the docs says ` If retrieving the token is an expensive operation, you may need to cache it. It is up to your retriever code to perform caching.`. Is it possible (and suitable ) to use the IClientCredentialsTokenManagementService and just supply the additional parameters for the token exchange. I have to change the DistributedClientCredentialsTokenCache implementation too, because cache keys are based on scope + resource.

**Comment by josephdecock** [comment]
> ... call the IAccessTokenRetriever in a similar way like simple http forwarder implementation. I suppose this is your view for future changes...
 
Yes, that's what I'm thinking of. 

> Is it possible (and suitable ) to use the IClientCredentialsTokenManagementService and just supply the additional parameters for the token exchange. I have to change the DistributedClientCredentialsTokenCache implementation too, because cache keys are based on scope + resource.

This sounds reasonable, assuming that you have client credentials tokens to manage here, as opposed to tokens for a particular user.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by agerchev** [comment]
Yes, you can close it. Thank you !
