### ISSUE TITLE
 IdentityServer4 v 2.1.0 => Duende.IdentityServer 6.3.2 - 404 error at /connect/token

### ISSUE THREAD

**Issue by eb-datatel** [DuendeSoftware/Support#821]
**Which version of Duende IdentityServer are you using?**
6.3.2

**Which version of .NET are you using?**
6.0

**Describe the bug**
404 error when connecting to "/connect/token"

Upgrading from IdentityServer4 v 2.1.0 => Duende.IdentityServer 6.3.2
The only feature being used is Scopes. The required schema and data migrations steps were performed.
The project runs, but gives a connection error for the IdentityServer endpoints.
Other endpoints not associated with Identity work.
Nothing shows in the logs.
Running a trace on the database shows queries succesfully executed against the Persistence and Configuration tables.

**To Reproduce**
Run project
send POST to  ".../connect/token"

**Expected Behavior**
Either a session is started, or an error in the console log.

**Log output/exception with stacktrace**
{StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Date: Mon, 07 Aug 2023 23:18:51 GMT
  Server: Kestrel
  Content-Length: 0
}}
```
data
```

**Additional context**

**Comment by josephdecock** [comment]
Do all of the endpoints fail? Are you able to retrieve the discovery document (/.well-known/openid-configuration)? Do you get anything from IdentityServer in the logs on startup?

**Comment by eb-datatel** [comment]
> Do all of the endpoints fail?
Yes, except a non-sso test controller still works
> Are you able to retrieve the discovery document (/.well-known/openid-configuration)?
No, there's a 404
> Do you get anything from IdentityServer in the logs on startup?
Nothing.
There is database activity in a database server trace.

**Comment by josephdecock** [comment]
This sounds like an issue with the pipeline and/or with the requests not making it to the IdentityServer middleware. 

Do you have a call to UseIdentityServer, adding the identity server middleware to the pipeline? Can you show some of your code where you are setting up the pipeline? Alternatively, can you compare you startup code with one of our [samples](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/Basics/IdentityServer)?

**Comment by eb-datatel** [comment]
Can I send the source code directly to you?

**Comment by eb-datatel** [comment]
I added the missing call to UseIdentityServer() now I’m getting a licensing warning in the log (as expected) When I hit the config endpoint I get a DB error on Keys I used this to disable Key Management                services.AddIdentityServer(options => {                        options.KeyManagement.Enabled = false;                    }) Now, that problem has stopped, and there’s a new problem. Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Created'.Invalid column name 'LastAccessed'.Invalid column name 'NonEditable'.Invalid column name 'Updated'. Can you provide me a SQL schema for what’s needed, or an option to turn off the Dynamic Providers (this seems to be part of)? I had been using the SQL scripts that were provided, rather than EF Migrations, because it was more convenient for me to control the data migration.So I don’t want to go back to EF Migration now.  Sent from Mail for Windows From: Joe DeCockSent: Thursday, August 10, 2023 12:13 PMTo: DuendeSoftware/SupportCc: eb-datatel; AuthorSubject: Re: [DuendeSoftware/Support] IdentityServer4 v 2.1.0 => Duende.IdentityServer 6.3.2 - 404 error at /connect/token (Issue #821) This sounds like an issue with the pipeline and/or with the requests not making it to the IdentityServer middleware.Do you have a call to UseIdentityServer, adding the identity server middleware to the pipeline? Can you show some of your code where you are setting up the pipeline? Alternatively, can you compare you startup code with one of our samples?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by josephdecock** [comment]
Hey do you mind fixing your last message? GitHub choked on your formatting.

**Comment by eb-datatel** [comment]
> Hey do you mind fixing your last message? GitHub choked on your formatting.

Of course

**Comment by josephdecock** [comment]
We don't officially publish sql updates scripts because our EF store is deliberately abstracted from particular databases. It can support anything with an EF provider, and the different databases need different sql scripts (they have syntax differences, as well as differences in their type systems).

We generally recommend that you use EF migrations to generate the sql scripts that are appropriate for your environment. If you don't want to use EF migrations to manage the application of database changes, you can still use EF migrations to generate the script as a starting point, and then put the script into whatever db change management system you like. 

The migrations that you're looking at in our repo are what we use to build a development database using microsoft sql server. They're aren't part of our official releases, we just use them for internal development. Those migrations are actually generated by entity framework, and we rebuild our database all the time from scratch. In practice, we think most folks should generate the migrations themselves. That way, the output is an update script, rather than creating a new database. Also, the sql that it generates will be appropriate for the database you're actually using. That said, if our scripts are useful to you when you're managing your database, there's no harm in looking at them (we just don't support those scripts).
