### ISSUE TITLE
[Question] Expired ClientSecret cleanup

### ISSUE THREAD

**Issue by bigred8982** [DuendeSoftware/Support#830]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
.net6.0

**Describe the question**
What is the recommended approach to cleaning up expired client secrets?

**Additional Context**

I noticed that IdentityServer will cleanup expired grants via the `TokenCleanupHost` calling `tokenCleanupService.CleanupGrantsAsync()`. I couldn't find any equivalent for expired secrets.

I see tho obvious approaches:
* Override `ITokenCleanupService` and piggy back off of the grants cleanup method
* Create a custom cleanup service and run it as another hosted service

Do you recommend one of the above over the other, or have a different recommendation? Perhaps I completely overlooked some existing code in IdentityServer?

**Comment by josephdecock** [comment]
IdentityServer doesn't automate client secret management so it's really up to you to decide how to clean up client secrets and if that is needed at all. I probably wouldn't put that cleanup into the token cleanup service, since it really is very unrelated and probably doesn't need to run nearly as often.

**Comment by josephdecock** [comment]
I'll go ahead and close this, but feel free to follow up or re-open if necessary.
