### ISSUE TITLE
Protected persisted grants should get migrated to new key material

### ISSUE THREAD

**Issue by f-waffenschmidt** [DuendeSoftware/Support#831]
**Which version of Duende IdentityServer are you using?**
6.3.0

**Which version of .NET are you using?**
.NET 6

**Describe the bug**

I am using the PAT sample like described as a reference token. Since reference tokens get encrypted by default (I know they can be disabled) there is the chance that a reference token which issued with a longer validation time as the data protection key will be invalidated automatically. As far as I understand the data protection, keys get introduced 14 days before expiration and will remain in the system 14 days after expiration. Because the reference token is bound to this period of time, tokens with a longer validity gets invalidated by missing key introduction.

**To Reproduce**
 - Configure data protection as default (90 days key expiration)
 - Issue a reference token valid for longer than 150 days. 
 - Set date on computer to the future + 91 days
 - Try to validate the reference token

**Expected behavior**
My expectation is, that the key which was used to encrypt the reference token payload, will be used to decrypt the content and encrypt the content with the new introduced key.

**Log output/exception with stacktrace**

**Additional context**

This is not a bug report. It is more a question whether it makes sense to implement a key management for data protection. I am very sure it is not the best practice to keep tokens alive forever by setting the Key-Lifetime to lets say 5000 days. This would affect the system for sessions and other protection scenarios. But for personal access tokens, I would assume, that max. 90 days (limited by data protection might be to less.

**Comment by josephdecock** [comment]
> As far as I understand the data protection, keys get introduced 14 days before expiration and will remain in the system 14 days after expiration.

This is actually not the case. Data protection keys that are expired are _**retained indefinitely**_, because the data that was protected with them in the past might still need to be read. Expiration of a data protection key just means that it will no longer be used to protect data. It doesn't mean that the protected data is somehow invalidated. Only revoked keys will no longer be used to unprotect data, and revocation should only be done if a key has been compromised.

In fact, deleting keys is such a destructive act, and so counter to the design of the data protection system, that the data protection  API doesn't actually include a mechanism to do so.

For more details on data protection key management, I recommend Microsoft's docs: https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-management?view=aspnetcore-7.0#key-expiration-and-rolling

In your reproduction steps experimenting with the system clock, what was the outcome? Can you provide the IdentityServer logs?

Can you confirm that there's no other problem with validation of your reference token? In other words, if you do just the first two steps:
- Configure data protection as default (90 days key expiration)
- Issue a reference token valid for longer than 150 days.
Is the reference token valid at this point (without yet having changed the clock) in your test setup?

**Comment by f-waffenschmidt** [comment]
Hi @josephdecock,

thanks for clarification. I was using the wrong implementation for keymanagement xml repository. The documented  dataprotection (in my case redis) works fine and creates new entries a view hours before expiration. 

Thanks
