### ISSUE TITLE
IDX10501: Signature validation failed. Unable to match key:

### ISSUE THREAD

**Issue by lnodaba** [DuendeSoftware/Support#837]
**Which version of Duende BFF are you using?**

2.1.1

**Which version of .NET are you using?**

7

**Describe the bug**

Sometimes randomly I get the bellow error on login:

![image](https://github.com/DuendeSoftware/Support/assets/38653825/8017fff1-17dd-40b5-b841-6ed248904d52)

I'm using your quickstart project as a base.

Looks like Identity Server generates the keys and stores them:
![image](https://github.com/DuendeSoftware/Support/assets/38653825/07970868-977b-49ba-8771-167c556f3c50)

Now the question how can we make the BFF to use those keys, they both are able to access the same db.

I see this article: https://docs.duendesoftware.com/identityserver/v5/reference/stores/signing_key_store/#serializedkey

But it doesn't mention how can I make that to be picked up here:

![image](https://github.com/DuendeSoftware/Support/assets/38653825/59bc062c-2e78-4ba2-b4a6-21b7bc64c870)

Probably could write a delegate for this
`  public delegate IEnumerable<SecurityKey> IssuerSigningKeyResolver(string token, SecurityToken securityToken, string kid, TokenValidationParameters validationParameters);`

But how can I instanciate `SerializedKey` to `SecurityKey`?

**Comment by josephdecock** [comment]
The BFF is designed to not need to retrieve identity server's signing keys from the database. The signing keys contain the private key material, and are themselves data protected. The public key material is made available to the BFF (and all other OAuth clients) through the discovery endpoints, which should be handled automatically. 

Can you share the full stack trace of the error, and when exactly does it occur?

**Comment by lnodaba** [comment]
@josephdecock the when is not clear to us, the application is being deployed to AppContainers in Azure, and sorry it's just a picture of the stack trace:

![image](https://github.com/DuendeSoftware/Support/assets/38653825/8532ea86-1e29-4e41-9791-31ce9274e6e6)
![image](https://github.com/DuendeSoftware/Support/assets/38653825/8af5cbd7-9f93-40ad-b846-489bafce7e97)

**Comment by josephdecock** [comment]
In your first message, the key id (kid) that it couldn't match starts '8438...', but in this one, I see 'EA0F...". Normally I would expect keys to not change very often, and so this has me suspicious that you might actually have a data protection problem. If IdentityServer is load balanced and the load balanced nodes aren't sharing data protection keys, then each node can only read the signing keys that it creates. When IdentityServer fails to read the other node's key, it will create its own. 

If that's happening, you should be getting errors or warnings in the IdentityServer logs related to data protection. Do you have anything there?

**Comment by poplevente** [comment]
@josephdecock thanks, but we don't use load balancing at the moment, but we might in the future, so thanks for pointing that out. we only use container apps as @lnodaba mentioned. i think the two images were two different sessions, that's why the kid is different. any other ideas why this might happen? it's really rare and random.

**Comment by josephdecock** [comment]
kid's don't change on a per-session basis. 

When the BFF validates the id_token, here's what happens: An id_token is a jwt. That jwt contains a header which includes the key id (the kid) that was used to sign the token. IdentityServer publishes the public key material for its signing keys at /.well-known/openid-configuration/jwks. That key material includes a kid for each key. The OIDC handler in the BFF will occasionally make requests to the jwks endpoint and cache the results. So, when it is presented with a token, it will find the key that it needs based on the kid of the token. It then does some cryptographic math to validate the token's signature.

What the exception means is, the token's kid isn't one that the OIDC handler knows about.

I suspect that your containerized instance of IdentityServer is getting a new DataProtection key every time that the container is restarted. Then, it fails to read any of the existing signing keys, because they are all protected with data protection keys that were created and destroyed in the past, by past instances of the container. Since it can't read any of the keys, it creates a new one, and starts signing tokens with that key. But the BFF doesn't know that this has occurred. It has a cache (as I mentioned) of the public keys as they were before the restart. The BFF's cache is pretty long lived - by default it is 24 hours, unless the BFF's vm is also restarted.

You can confirm this theory by checking to see how many keys are in the Keys table and comparing that to the keys that you see in the jwks endpoint. If I'm right, you probably have a bunch of keys in the table that you can't read anymore, and 1 key in your jwks endpoint.

If that's the case, then you need to configure data protection. Since you're already in azure, an easy way to do that is to persist the keys to azure blob storage and protect the keys with azure key vault. But, there's a great many options for where to persist your data protection keys and how to protect them. Microsoft describe this in their docs [here](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-7.0#protectkeyswithazurekeyvault).

**Comment by lnodaba** [comment]
@josephdecock this all makes so much sense, indeed we have a bunch of keys.

And yeah we added data protections to the bff project only, you say we need to add that to the identity server too?

**Comment by josephdecock** [comment]
Yes, IdentityServer depends [heavily on](https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/) data protection to protect sensitive data at rest.

**Comment by poplevente** [comment]
@josephdecock thanks for the suggestions, very helpful. we think that will be it. let us change it and we will get back with a confirmation if this worked.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by poplevente** [comment]
Hi @josephdecock, sorry for the late answer. yes, seems that the changes helped and we don't see the issue anymore. You can close the issue. And thanks again for your support.
