### ISSUE TITLE
FrontChannelLogoutUri configuration and signout GET vs POST

### ISSUE THREAD

**Issue by carnahanliam** [DuendeSoftware/Support#845]
**Which version of Duende IdentityServer are you using?**

6.3.3

**Which version of .NET are you using?**

.NET 7.0

**Describe the bug**

I'm trying to signout users from clients using front-channel logout and I think I'm implementing it correctly but there are still a few things I'm unclear on. 

At the level of the client I'm setting the FrontChannelLogoutUri using the RemoteSignOutPath property of the OpenIdConnectOptions. The [aspnetcore source code](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L46) makes it seem like this property defaults to "/signout-oidc" although the [Duende docs](https://docs.duendesoftware.com/identityserver/v6/ui/login/dynamicproviders#callback-paths) make it seem like the default value is "/signout". Am I misinterpreting the documentation here?

Another question I have about signout in general is whether users should be prompted at level of the client application to POST logout requests. In the Duende docs it is [mentioned](https://docs.duendesoftware.com/identityserver/v6/ui/logout/session_cleanup/#prompting-the-user-to-logout) that you should prompt the user to logout, which requires a POST, otherwise an attacker could hotlink to your logout page. When looking at the MvcBasic and IdentityServer sample projects [here](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/Basics), I can see that in Logout at the IdentityServer there are checks in place to determine if a user should be shown a prompt or automatically signed out. When signout is initiated in the MvcBasic project, it is only handled with a GET request; is this just for the sake of simplicity, and this is where the docs are suggesting a prompt for POST should be added? Or does the redirect from client to the end session endpoint and then to Logout at the IdentityServer mitigate the hotlinking risk?

**Comment by josephdecock** [comment]
> The [aspnetcore source code](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L46) makes it seem like this property defaults to "/signout-oidc" although the [Duende docs](https://docs.duendesoftware.com/identityserver/v6/ui/login/dynamicproviders#callback-paths) make it seem like the default value is "/signout".

/signout-oidc is the default for the OpenIdConnect handler. If you have more than one scheme using that handler, you would change the callback paths so that the right scheme would handler each request.

Our documentation that you're linking to there is showing how to deal with our dynamic providers feature, which is for federating with a large number of providers. When you do that, we distinguish each of the providers and create callback paths automatically. In that case, the callback paths would be ~/federation/one-of-your-dynamic-schemes/signout, ~/federation/another-of-your-dynamic-schemes/signout, etc.


> Another question I have about signout in general is whether users should be prompted at level of the client application to POST logout requests. In the Duende docs it is [mentioned](https://docs.duendesoftware.com/identityserver/v6/ui/logout/session_cleanup/#prompting-the-user-to-logout) that you should prompt the user to logout, which requires a POST, otherwise an attacker could hotlink to your logout page. When looking at the MvcBasic and IdentityServer sample projects [here](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/Basics), I can see that in Logout at the IdentityServer there are checks in place to determine if a user should be shown a prompt or automatically signed out. When signout is initiated in the MvcBasic project, it is only handled with a GET request; is this just for the sake of simplicity, and this is where the docs are suggesting a prompt for POST should be added? Or does the redirect from client to the end session endpoint and then to Logout at the IdentityServer mitigate the hotlinking risk?

Its not the redirect that prevents the hotlinking risk, it is the id_token_hint parameter. This parameter contains the original id_token that started the session at the client application. The spec requires that if it is sent, the id token's sub and sid match the session at identity server. Since an attacker wouldn't have the id token, this allows you to logout without prompting the user.

If you enable the SaveTokens option in .net, it will persist the id token until you log out, and send it back as the id_token_hint.

**Comment by carnahanliam** [comment]
So in this example hotlinking to the IdentityServer logout url will cause the user to be prompted to logout, preventing this attack; but could a hotlink to the MvcBasic client logout url still trigger a logout without prompting the user? (And it would be up to the client to handle preventing this?)

Also, in logout at the MvcBasic client there is only one authentication scheme passed to Signout(), which is "oidc". Is it not necessary to also pass in "Cookies" if you're using that scheme too?

**Comment by carnahanliam** [comment]
Sorry yes you can close it now. Thank you!
