### ISSUE TITLE
Roles in Blazor Client Site AuthenticationState using the BffAuthenticationStateProvider sample code

### ISSUE THREAD

**Issue by colmryan3rdi** [DuendeSoftware/Support#855]
Struggling a little bit with the sample BffAuthenticationStateProvider and the integration around aspnet identity. So far managed to get all of the process working from client to server to identity server, and the bff authentication is working fine, get claims etc., and I have server side authentication working on API call back with AspnetIdentity. But what I don't have client side in the state provider is the set of roles associated with the aspnet user and I am wondering how to add those in there. Would say, an approach extending the DefaultUserService by the way to go, adding the roles as claims and extending the client side authentication provider to add those in? It would be great to see how this could work in the wasm samples. I'd like to have a UI presented based on roles using the Role parameter in Authorized view.

**Comment by josephdecock** [comment]
My very general recommendation is to not centralize roles at identity server, because it is common to have different roles in different applications. Typically, I would have roles managed on a per-application basis. 

For example, when application 1's BFF does an OIDC login, it receieves a token that says "Joe" logged in, and then it looks up what roles I have in that application and adds role claims to the subject before issuing the auth cookie. Then application 2 can do the same thing, but look up the roles I have in that application separately, and result in different roles at that application.

If the roles of your users _really_ are global across all applications, then I think the approach you're describing sounds reasonable.

**Comment by colmryan3rdi** [comment]
Thanks for the response Joseph. In my scenario I've set up identity server and the client's back end server to share an AspnetIdentityStore (the back end redirects to identity server as the oidc provider and 've shared DBContext for the two, I know this might not make ultimate sense to do it this way, but the logic was I would be requiring more detailed profile info to be available on the back end server and I didn't want to send all that data along as claims, and I wanted a separation between the back end and the login provider), I can access the role information in the back end server and use IUserService to do this with the BFF provider. Therefore I can customise the claims on the back end before forwarding to the client.  What I haven't figured out yet is how the client side AuthenticationState gets roles from the ClaimsPrincipal for the AuthorisedView. I hope I'm not missing anything obvious here or I am not architecting this in an obtuse manner.

**Comment by josephdecock** [comment]
In our sample, we have an [authentication state provider](https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/BFF/BlazorWasm/Client/BFF/BffAuthenticationStateProvider.cs) that polls the /bff/user endpoint to retrieve the user's claims. The [/bff/user](https://docs.duendesoftware.com/identityserver/v6/bff/session/management/user/) endpoint retrieves the claims that are in the BFF's session. Are you getting the role claims into that session? You could check with the [diagnostics endpoint](https://docs.duendesoftware.com/identityserver/v6/bff/session/management/diagnostics/).

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by colmryan3rdi** [comment]
Hi Joseph, sorry for the delay in replying. Not seeing the roles in the UAT @ the diagnostic endpoint. Can I configure IdentityServer to add these or will it have to be done manually?

**Comment by josephdecock** [comment]
There isn't a configuration flag that enables this. If you want to add the roles, you'll have to add them. If you were doing this in identity server, you would add the claims to the userinfo endpoint by extending the ProfileService. See [here](https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/) for docs and [here](https://docs.duendesoftware.com/identityserver/v6/samples/ui/#custom-profile-service) for a sample. Since you have a different architecture, you can add the roles to the bff's session however you like. Ultimately, the bff's endpoints operate on the claims in the session, and you can customize that however you like.

**Comment by AndersAbel** [comment]
Are there any more open questions on this issue or can we go ahead and close it?

**Comment by colmryan3rdi** [comment]
Closed for me. Manually adding roles to claims worked. To me though, this feels like an incomplete integration with aspnet identity if the framework is not doing this automatically via the configuration.
