### ISSUE TITLE
Hooking into Signin Events

### ISSUE THREAD

**Issue by dclayton77** [DuendeSoftware/Support#856]
I have moved to the BFF framework and I have a React application that is working great with IdentityServer.  I was previously using ReduxOidc where I would use the UserManager to hook into login/logout events.

Since moving to BFF, I have been unable to use the UserManager successfully and I am not sure if this is the correct approach anymore.

What I am looking to do is hook into the signin event after the signin-oidc redirects to the home page of the application.  I would like to be able to run code at this point.  Is there a preferred way of doing this when using the BFF framework?

**Comment by josephdecock** [comment]
It sounds like the UserManager is hooking into events that aren't happening anymore, because the OIDC flow isn't happening inside of the react app anymore.

You can make a call to [/bff/user](https://docs.duendesoftware.com/identityserver/v6/bff/session/management/user/) to determine if the user is logged in and if so, perform you startup logic. You should also save the claims that you get from that endpoint, which includes both profile information, and management info, like the url that you use to log out - see the docs I linked above for more info.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
