### ISSUE TITLE
Identity Server 6.0 and multiple angular client apps

### ISSUE THREAD

**Issue by vrrenga123** [DuendeSoftware/Support#863]
**IdentityServer  6.0**

**.NET Core 6.0**

**Identity Server 6.0 and multiple angular client apps**

I'm developing SSO application using Identity Server 6.0 and other client angular applications will use it to authenticate a user by using oidc-client. Given that I have 2 client apps (Identity Server clients) - ClientA and ClientB. Now single user User1 logs on into ClientA web app. He enters user/password and tokens are issued for User1/ClientA combination. Then User1 logs on into ClientB application. There is no login screen from SSO site, which is fine, as cookies are used by Identity Server to recognize the same session. 	

Before the session expires in two minutes in Client A and Client B, a countdown will start before 2 mins of expiration and be displayed  in the confirmation dialog box. If user click on Yes button in the confirmation dialog box, the signinSilent method will refresh the token, returning a new expiration time, and displaying the confirmation dialog box based on the new expiration time in next time.   

If the user calls an API before the expiration period, the confirmation dialog box won't show up; instead, the signinSilent method will be called (before 2 mins expiration) silently, refreshing the token in background 

In that case, I ran into the following issue: If client A refreshed silently, a new token would be produced for client A with a new expiration time. However, Client B, the second application, is inactive and Client B displays a confirmation dialog box. If Client B receives no answer from the user, Client B will immediately sign out automatically, and Client A will also be forced signed out as a result. 

What is the suggested approach for Client B to remain active given that Client A is still active with the new token and new expiration time?

The flow could be something like this

the user logs in Client A, receives a JWT access token with a 10-minute expiration time.

After 3 mins Client B login, receives a JWT access token with a 10-minute expiration time.

As user actively worked on Client A,  before expiry time (2 mins before), silently refreshed the token and get new token with token expiry time is 10 mins

Client B will immediately sign out automatically (implemented in code) as it was in idle for 10 mins, and Client A will also be forced signed out as a result.

My expectation is client B should not sign out as Client A is in still alive

**Comment by josephdecock** [comment]
The scenario that you're describing is a common problem and it comes from the fact that there are several different applications, each with their own notion of session. What makes that even more challenging is that most of the sessions exist (traditionally) only in the browsers of your users - things like cookies and session data aren't accessible to your code on the server side that might try to coordinate them. IdentityServer's solution to this problem is our Server Side Sessions feature. This moves the IdentityServer session data into the back end where you can monitor it for inactivity etc.

Our docs on the server side session feature start [here](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/), and of particular interest is the sub page on inactivity timeouts [here](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/inactivity_timeout/). Note that in your oidc-client.js based architecture, you don't have a backchannel to your client applications. So, instead of sending backchannel logout notifications (as that document describes), they would be notified of the session ending through oidc session management (the check session iframe, implemented by that library).

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
