### ISSUE TITLE
When do you override the default scheme name in AddOpenIdConnect()?

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#867]
I'm using Identity Server 6 and .NET 6.

I'm playing around with the [IdentityServerAspNetIdentity](https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/Quickstarts/5_AspNetIdentity/src/IdentityServerAspNetIdentity/Pages/Account/Login/Index.cshtml.cs#L165) sample.

I've modified [HostingExtensions.cs](https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/Quickstarts/5_AspNetIdentity/src/IdentityServerAspNetIdentity/HostingExtensions.cs#L40) slightly to include OIDC:
```
builder.Services.AddAuthentication()
            .AddOpenIdConnect(options =>
...
```
I looked at the implementation and can see it uses `"OpenIdConnect"` as the default for the authentication scheme.

**In what situation would you need to override the default value with something other than OpenIdConnect?**

I had a look in [BuildModelAsync()](https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/Quickstarts/5_AspNetIdentity/src/IdentityServerAspNetIdentity/Pages/Account/Login/Index.cshtml.cs#L165) and can see there are 7 schemes registered by default.

![image](https://github.com/DuendeSoftware/Support/assets/13111539/3b347e46-c81a-4c98-b4a7-3ca7a0ad8611)

All of them have `null` for the `DisplayName` except `OpenIdConnect` which has `OpenIdConnect` for the `Name` and `DisplayName`.

**Why do all the schemes have a `null` `DisplayName` except the scheme supplied to `AddOpenIdConnect()`?**

**Why does having a non `null` `DisplayName` make it a provider instead of just a scheme?**

**Comment by josephdecock** [comment]
> **In what situation would you need to override the default value with something other than OpenIdConnect?**

Authentication handlers can be used multiple times with distinct configurations. For example, you might federate with both Azure AD and Okta. Each of those federations would use the open id connect handler but be configured distinctly. We give those distinct configurations separate scheme names to differentiate them. The named and configured instance of the handler is called a scheme.

> **Why do all the schemes have a `null` `DisplayName` except the scheme supplied to `AddOpenIdConnect()`?**

The default schemes are created by Asp.NET Identity and by IdentityServer and are Cookie authentication schemes used in various situations. This always us to completely separate sessions depending on things like, if they originated externally, if the user has performed MFA, etc. When you create a cookie authentication handler, it doesn't set a display name by default. I think that makes sense, because you wouldn't normally ask the user which authentication cookie they want to use. Back end logic is making that decision for the user. 

On the other hand, external identity providers that you federate with using OIDC often do require that we prompt the user to make a choice (you might have a button to log in with Okta and another to log in with Azure AD). So for those schemes, there is a display name. You could set the display name yourself, but if you don't, the handler creates a default.

> **Why does having a non `null` `DisplayName` make it a provider instead of just a scheme?**

The quickstart UI shows the user buttons to log in with external identity providers, and relies on the behavior I'm describing above to make the distinction of which of the authentication schemes should be used to create those buttons.
