### ISSUE TITLE
Passing response_mode to challenge/redirect for external providers

### ISSUE THREAD

**Issue by GeertVerthe** [DuendeSoftware/Support#868]
**Which version of Duende IdentityServer are you using?**
6.3.3

**Which version of .NET are you using?**
Dotnetcore 7

**Describe the bug**

i have some external providers configured (they actually come from a store). I noticed using Azure Active Directory the code returned through GET is causing a long url causing a 404 error.

I now want to change the response_mode to form_post instead of the default 'query' upon redirecting to the login url of Azure but it looks i cannot do that.

I tried adding the response_mode as Parameter in the AuthenticationProperties in the Challenge method but this does not work as I expected.

**Expected behavior**

I would expect some kind of property on the OidcProvider class that sets the response_mode upon redirecting to the external provider

**Comment by josephdecock** [comment]
Issues with url length when you're federating with Azure AD usually happen because the state parameter grows as the user is redirected from one federated IdentityProvider to another. Often Microsoft's OIDC providers federate with each other, so you end up with multiple hops of federation, each one trying to persist state in the url. Our usual solution to that problem is to [store the state in a server side store](https://docs.duendesoftware.com/identityserver/v6/ui/login/external/#state-url-length-and-isecuredataformat), rather than changing the protocol parameters. I think that approach will be a more robust solution for you, because you don't have control over the protocol parameters that Azure AD is using on its end, so you want to minimize the parameters that you do control (the state that you pass to it).
