### ISSUE TITLE
What does await HttpContext.SignOutAsync() do with cookies?

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#875]
I'm using Identity Server 6, .NET Core 6 and Google Chrome 116.0.5845.112 (Official Build) (64-bit).

I'm making this call in my `Callback` method after I've authenticated with Okta:

`await HttpContext.SignOutAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);`

The response contains five `Set-Cookie` headers:

![image](https://github.com/DuendeSoftware/Support/assets/13111539/ced66242-adfa-49ae-9a78-33151d9be607)

However, when I look in the Cookies tab, it only shows two response cookies:

1. `idsrv.session`
2. `.AspNetCore.Identity.Application`

The other three are not displayed:

- idsrv.external
- idsrv.externalC1
- idsrv.externalC2

![image](https://github.com/DuendeSoftware/Support/assets/13111539/6067d229-5614-43f1-ab73-93d78acc7e80)

Those three are, however, displayed in the request cookies, and they match with the Cookie request header.

**Why are only two of the five response cookies displayed in the Cookies tab?**

**Why is the expiry for the `.AspNetCore.Identity.Application` cookie set to 1970-01-01 but the `Set-Cookie` header for `.AspNetCore.Identity.Application` has no `Expires` attribute?**

I tried commenting out 
`await HttpContext.SignOutAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);` and found this:

![SetCookie](https://github.com/DuendeSoftware/Support/assets/13111539/970641b0-b9f6-4043-a1b2-d6894a78358f)

The two `Set-Cookie` headers match the cookies in the response in the Cookies tab:

![Cookies](https://github.com/DuendeSoftware/Support/assets/13111539/35da5635-ff2a-42f3-af58-8e9dfb4601b6)

However, the `Expires/Max-Age` for `.AspNetCore.Identity.Application` is set to `Session`, but when I do make the call to `HttpContext.SignOutAsync()`, the `Expires/Max-Age` value is 1970-01-01, but both have the same value in the `Set-Cookie` header, ie. no `Expires` attribute is set.

**What determines the value for `Expires/Max-Age` for `.AspNetCore.Identity.Application` in  the Cookies tab?**

Even though `.AspNetCore.Identity.Application` is set with an expiry in the past, in the very next request, it is sent in the request from the browser to Identity Server:

![image](https://github.com/DuendeSoftware/Support/assets/13111539/3b927f66-d448-457c-9e11-dd595ab8f71f)

**Why is the `.AspNetCore.Identity.Application` cookie being sent after it's been set to expire?**

**Comment by josephdecock** [comment]
When you sign out of an auth cookie scheme, it tells the browser to destroy the cookies for that scheme by including a Set-Cookie header with the expire time of 1970-01-01 and an empty value. This is the normal way that web servers ask browsers to delete cookies (there is no Delete-Cookie http header).

Some of the odd things that you're seeing seem like it could be a bug in chrome's dev tools. Sometimes the cookie information in the dev tools is not 100% accurate. When I see odd things, I always double check the actual headers in the http requests and responses.

**Comment by josephdecock** [comment]
Another great resource for learning about ASP.NET's authentication handlers and OIDC is our youtube channel. Check it out: https://www.youtube.com/@duendesoftware!

**Comment by DavidKlempfner** [comment]
>  I always double check the actual headers in the http requests and responses.
In this case I'm not sure what the source of truth is for `.AspNetCore.Identity.Application`, from the Cookies tab, it looks as though await `HttpContext.SignOutAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);` is doing its job and setting  `.AspNetCore.Identity.Application` to expire at 1970-01-01, however the Headers don't show the expires attribute, AND the cookie is being sent with the very next request, so maybe it's not being deleted after all?

What is the point in calling `HttpContext.SignOutAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);`?
I've tried commenting it out, and everything still works just like before.

**Comment by josephdecock** [comment]
The .AspNetCore.Identity.Application cookie is the authentication cookie used by ASP.NET Identity (and by identity server, since you've enabled our ASP.NET Identity integration. This scheme name is also referred to with the constant `Microsoft.AspNetCore.Identity.IdentityConstants.ApplicationScheme`.

Separately, there is the external authentication scheme, with the name "idsrv.external", and the constant in code 'IdentityServerConstants.ExternalCookieAuthenticationScheme'. This cookie is used during federation as a temporary staging area to represent the identity that was presented to you by the external identity provider. There should almost always be an explicit mapping between identities provided externally and your own representation of the user (even if the user authenticated externally, you still have them in your user store, and you map between the two). Typically you don't want to allow just anyone from the external provider to be a user in your system. You usually need some level of control over that, and if they are a new user, there will be some sort of onboarding or provisioning for that user. While that process is ongoing, you represent the user in the external identity's cookie. Then, when it has finished, you can sign in the corresponding user from your user store into your authentication cookie (which in this case is the `IdentityConstants.ApplicationScheme = ".AspNetCore.Identity.Application"` cookie), and sign out from the external authentication cookie.

The point of having a separate scheme for external identities is that you will never accidentally or implicitly use that identity - the only way to use it is to explicitly sign in to that external scheme and then use the result. This gives more control when you are federating. We describe this whole multiple cookies issue in more detail [here](https://docs.duendesoftware.com/identityserver/v6/ui/login/external/).

So, when you call `HttpContext.SignOutAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);`, that deletes the external cookie, but not the asp.net identity cookie, hence you see it on the next request.

**Comment by DavidKlempfner** [comment]
Thanks for your reply. Very good explanation.
So calling `HttpContext.SignOutAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme)` is more about getting rid of something we no longer need, it's not something that "has to be done because otherwise things won't work".

**Comment by josephdecock** [comment]
> So calling HttpContext.SignOutAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme) is more about getting rid of something we no longer need, it's not something that "has to be done because otherwise things won't work".

That's right, and also you want to make sure that if you sign out of the main auth cookie, you don't have any lingering state from the session.
