### ISSUE TITLE
Question on server-side sessions

### ISSUE THREAD

**Issue by baouchemaya** [DuendeSoftware/Support#877]
Hi, 

could you please explain when to use server-side sessions on IdentityServer (with BFF) and when to use them on BFF (managed by BFF) ?

thank you in advance

**Comment by josephdecock** [comment]
When you use an external identity provider like IdentityServer, the logical session of a user interacting with their computer becomes distributed. There is a session at IdentityServer, which allows for single sign on and single sign out, and there are separate sessions at each client application (including your BFF), which allow the user to interact continuously with those applications.

By default, those sessions are stored in cookies associated with each application. Session data in a cookie makes sessions very difficult to manage, because you only have the session data when you're presented the cookie in an incoming HTTP request. Server side sessions move the session data from the cookie into a server side data store. By moving the session data server side, you're able to perform server side management of the sessions. For example, an administration could see currently logged in users and end their sessions.

With the logical session distributed across IdentityServer and your Client Application, you may have need for server side session data at either or both of them.

With IdentityServer server side sessions, you can perform session management that applies to the user's single sign on session. For example, you could forcibly log out a user from IdentityServer, and then next time they use an application that issues an OIDC challenge to log in, they would have to enter their credentials again.

This doesn't end the session of the client applications though. The user would be able to continue using the application they've already logged into as long as that client application session remains active.

When sessions at IdentityServer end for whatever reason, IdentityServer can send logout notifications to the client applications. Those notifications can be sent either in the front or back channel, that is, they can be sent to the application through the web browser, or as a direct server to server http request. 

Receiving front channel notifications is built in to ASP.NET, but it is only applicable when the logged out user is interacting with the site and is the one who caused the logout - they have to be sent through the appropriate user's browser. Back channel notifications can be sent any time without needing the right user's browser, so they are appropriate for server side session management. However, since a back channel notification is not relying on the user's browser, the receiving application has to have some other mechanism for managing the sessions at the client application - such as a server side session at the client application, which is exactly what the BFF's server side sessions allow for.

You could use back channel logout notifications even without server side sessions at IdentityServer, but in order to receive them at the BFF, you need the BFF to have server side sessions.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by baouchemaya** [comment]
thanks for the explanation, you can close it
