### ISSUE TITLE
Cookies not removed when server-side session is expired

### ISSUE THREAD

**Issue by baouchemaya** [DuendeSoftware/Support#879]
Hi,

I have a BFF that works with a custom store for server-side sessions storage. When the session is expired,  my implementation of `public Task DeleteUserSessionsAsync(UserSessionsFilter filter, CancellationToken cancellationToken = default)` is runned (the session is deleted in my custom store) but the cookies are still in the browser storage. 

My app redirects to login page when user is not authentified, so it navigates to /bff/login and sees that the cookies are still there. Then, it tries to retrieve session via ` public Task<UserSession?> GetUserSessionAsync(string key, CancellationToken cancellationToken = default)` but does not find session with the given key in the store. Which is the normal behavior, as the session was previously removed from the custom store. Here is a screenshot of the error I get :

![image](https://github.com/DuendeSoftware/Support/assets/118121801/de94c0fb-6c69-4879-94e4-628f4b47e34f)

My question is : how are the cookies removed from client-side after server-side session has expired ? 

Thanks!

**Comment by josephdecock** [comment]
Cookies are not normally removed when the server side session expires - the cookie data is in the browser outside our control at that point. The system is designed to expect that when a cookie is presented but the corresponding session is not found, the request is treated as anonymous.

Both our In memory and entity framework based implementations of the store return null if the session doesn't exist. I would verify that your implementation can do so as well, and in general can tolerate a missing session.

The other thing you could try is replacing your custom store with our in memory implementation (just for testing purposes).

**Comment by baouchemaya** [comment]
hi, 

first, thank you for you answer ! 

I've managed to fix the NullReferenceException, you were right, I was not handling the missing session properly. But now comes another question.

Is it the normal behaviour that when the session has expired and then been cleaned-up from the store (no corresponding session existing in the store), the login workflow is launched "implicitly" (it does not stop in my login route breaking point) and user is logged-in again without going back to the login form and creating a new session in the store ?

**Comment by baouchemaya** [comment]
@josephdecock do you have any clue, please ?

**Comment by josephdecock** [comment]
It sounds like you are clearing the session at the bff but not at IdentityServer. When you have an external identity provider (like IdentityServer) the logical session (me sitting at my computer, using applications and logging in with IdentityServer) is distributed among several physical sessions - IdentityServer and each application each have their own notion of session, with their own session cookies, and potentially their own server side sessions. If you only delete the application session, then the next time the client starts an OIDC flow (usually because you went to some route that requires authorization), IdentityServer will use _its_ session to immediately return tokens. 

We discuss this in a lot more detail in this chapter of the docs on IdentityServer's server side sessions: https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/ (along with its child pages).

And again, I just want to highlight that there is a session at both the BFF and IdentityServer, and either, both, or neither can be server side sessions.

**Comment by baouchemaya** [comment]
thank you for the clear explanation and patience ! 

I have implemented server-side sessions for Identity Server also (having already server-side sessions for BFF). In my solution, they are both stored in the same collection (custom store). Is it the right way to handle sessions for BFF & Identity Server (in the same storage) ? 

But this leads to another behavior I try to resolve :  when both sessions expire, I cannot logout (it is normal). Otherwise, the logout goes well.

I have a logout button on my UI that is initialized with the logout_url from the claims. But as I logout, my `PostLogoutRedirectUri `is `null`, so the signout workflow does complete properly and do not redirect to the login page. Any recommendation about that, please ? 

Should I handle this on frontend side or is there something to do on IdentityServer ? In my controller, I do have this line :  ` var logoutRequest = await _interactionService.GetLogoutContextAsync(logoutId);` Should I create a new LogoutContext in the case that `logoutRequest.PostLogoutRedirectUri` is `null `? Do you have any clue ? 

Thank you in advance

**Comment by josephdecock** [comment]
> I have implemented server-side sessions for Identity Server also (having already server-side sessions for BFF). In my solution, they are both stored in the same collection (custom store). Is it the right way to handle sessions for BFF & Identity Server (in the same storage) ?

Usually I would store the sessions separately to avoid confusion. You could in theory store them together if you session store had a discriminator to make sure you got the right session, but our default implementation of the store doesn't do that. I think Anders is addressing this topic at more length in your other issue - https://github.com/DuendeSoftware/Support/issues/914.

> I have a logout button on my UI that is initialized with the logout_url from the claims. But as I logout, my `PostLogoutRedirectUri `is `null`, so the signout workflow does complete properly and do not redirect to the login page. Any recommendation about that, please?
 
> Should I create a new LogoutContext in the case that logoutRequest.PostLogoutRedirectUri is null? 

There's a subtle security issue here. What's happening is that, without a session at the BFF, there's no longer a saved id token to send back as the logout id hint. Normally, that hint is used to authenticate the end session request. Without it, you have to prompt the user to confirm that they actually intended to logout, otherwise an attacker can put malicious links into a page that will destroy sessions. If the user does confirm that they want to logout, then your IdentityServer can safely log out and safely redirect back to your client application. 

You also need to be careful that the redirect url parameter is not blindly trusted, otherwise you create an open redirector vulnerability. You can either validate the redirect url using the `IRedirectUriValidator.IsRedirectUriValidAsync(string requestedUri, Client client);` method, using the client_id parameter to load the client. or you could have your code in the logout controller specify the redirect uri without using input parameters at all.

But these issues are why IdentityServer has the behavior that it does by default. If you don't send an id token, we prompt for logout, and then don't redirect anywhere.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?
