### ISSUE TITLE
Invalidating user session across browsers

### ISSUE THREAD

**Issue by sc1ent** [DuendeSoftware/Support#892]
**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
6.0

**Describe the bug**
This is a question rather than a bug.

This is my current configuration with Identity Server:
- Identity Server is configured to issue reference access tokens.
- I am using the oidc-client-js library to monitor sessions on the frontend.
- I am using this extension in my other backends that rely on Identity Server for authentication and authorization https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection

Below is the scenario I would like to implement:
User A is logged into an active session in one browser session. Meanwhile, the password is reset for User A from a different browser session (this is done anonymously using the common "forgot password" feature found in most sites). When that reset password succeeds, I'd like to revoke the reference token for that active session (or any active sessions) for User A, but also notify that browser session that it should re-validate it's access token (via the introspection endpoint I imagine).

I have found that I can revoke the tokens for a specific user using the `IPersistedGrantService`. However, I'm not understanding from my reading how to then notify active sessions in the browser that their tokens may no longer be valid.

I've been reading about frontchannel logout thinking that may be the answer, but I have not tried implementing a PoC to prove that out.

Hopefully my session invalidation need makes sense. I'm looking for some help to see if I'm on the right track (with frontchannel logout) or if I'm venturing down the wrong path. I know you have tons of samples, so pointing me to one would be great too.

Thanks

 The template was for a bug, so I think I provided enough context. If not, please let me know.

**Comment by AndersAbel** [comment]
To invalidate all existing sessions on password change, the first step is exactly as you describe - revoke all persisted grants for that user. When using reference access tokens that will immediately cause all API calls from any service to fail. 

Just for comparison, if self-contained access tokens in the JWT format are used, those will not be revoked (as they cannot be revoked). However such tokens should be short lived and when the clients requests a new token using their refresh tokens that will fail because of the refresh tokens being revoked.

To prevent the clients from re-establishing sessions through single sign on, the IdentityServer session also needs to be terminated. To be able to terminate sessions from somewhere else than the browser holding the session IdentityServer server side sessions must be used. With server side sessions the change password event can revoke any existing sessions with IdentityServer in the same way as the persisted grants are revoked.

Once all tokens are revoked, API access is not possible. With the IdentityServer session terminated there is now no way for the clients to get new tokens through single sign on. There should now be a simple way to inform the clients that they should terminate their local sessions. Unfortunately it is not that simple. Application sessions are usually represented by a cookie in the user's browser. The only way to remove cookies is to make the browser perform a request to the server so that the server can respond with a `set-cookie` header to clear the cookie. This is how front channel logout works - it is a clever scheme to make the user's browser make requests to all involved client applications so that each of them can remove their cookies. With your example that is not a viable way forward though - the sessions are not in the browser that performed the password reset.

One way to get the sessions terminated, although not immediately, is to have the access token being short lived (5 minutes). That will force the clients to use their refresh tokens every 5 minutes and if that fails, the client would log out. If you have clients that do not use access tokens for API calls you would still have to set them up to do the token refresh every 5 minutes. This is fairly simple to implement, but has a delay of up to 5 minutes (or whatever AT life time you choose) before the client session are terminated.

To propagate the session termination immediately to all clients, there is a mechanism for back channel logout. With that, IdentityServer sends a back channel message to each client application to terminate a specific session. That only works if the clients store their sessions server side and has support for back channel logout. We have a [sample](https://docs.duendesoftware.com/identityserver/v6/samples/basics/#mvc-client-with-back-channel-logout-notifications) for how to add that to MVC applications.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?
