### ISSUE TITLE
What is the difference between the authentication schemes?

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#893]
I'm using Identity Server 6 and .NET 6.

I can't figure out how to know which authentication scheme to use when, and what the difference is between them.

I'm using the [5_AspNetIdentity Quickstart guide](https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/Quickstarts/5_AspNetIdentity/src/IdentityServerAspNetIdentity/HostingExtensions.cs) and have modified it to use Okta:

Here is the HostingExtensions.cs code:
```
builder.Services.AddAuthentication()
            .AddOpenIdConnect(options =>
            {
                //options.SignInScheme = "Identity.Application";
                //options.SignInScheme = "Identity.External";
                options.SignInScheme = "Identity.TwoFactorRememberMe";
                //options.SignInScheme = "Identity.TwoFactorUserId";
                //options.SignInScheme = "idsrv";
                //options.SignInScheme = "idsrv.external";
                //options.SignInScheme = "OpenIdConnect";

                options.SignOutScheme = IdentityServerConstants.SignoutScheme;
                options.Authority = "https://mrisaas.oktapreview.com";
                options.ClientId = "clientId";
                options.ClientSecret = "secretHere";
                options.ResponseType = OidcConstants.TokenRequest.Code;
                options.SaveTokens = true;
                options.CallbackPath = "/signin-idsrv";
                options.SignedOutCallbackPath = "/signout-callback-idsrv";
                options.RemoteSignOutPath = "/signout-idsrv";
                options.MapInboundClaims = false;
                ...
});
```

Here is the Callback.cshtml.cs code:
```
public async Task<IActionResult> OnGet()
    {
        // read external identity from the temporary cookie
        //var result = await HttpContext.AuthenticateAsync("Identity.Application");
        //var result = await HttpContext.AuthenticateAsync("Identity.External");
        var result = await HttpContext.AuthenticateAsync("Identity.TwoFactorRememberMe");
        //var result = await HttpContext.AuthenticateAsync("Identity.TwoFactorUserId");
        //var result = await HttpContext.AuthenticateAsync("idsrv"); //IdentityServerConstants.DefaultCookieAuthenticationScheme
        //var result = await HttpContext.AuthenticateAsync("idsrv.external");  //IdentityServerConstants.ExternalCookieAuthenticationScheme
        //var result = await HttpContext.AuthenticateAsync("OpenIdConnect");
        if (result?.Succeeded != true)
        {
            throw new Exception("External authentication error");
        }
        ...
}
```

I have tried all of the commented out `var result` lines of code, and made sure the corresponding  `options.SignInScheme` was used as well.
I noticed all of them resulted in `result?.Succeeded` being `true` (except `OpenIdConnect`).

They all had the same cookies in the Callback's response:

- AspNetCore.Identity.Application
- idsrv.session
- idsrv (expires=Thu, 01 Jan 1970)

And they all had one cookie in the request, which was the name of the auth scheme used.

I understand that an authentication scheme is a piece of code that handles authentication, bu**t where can I find the implementation for each authentication scheme?**

**Are there use cases for when to use each one?**

In the example above, each combination seemed to work fine (`result.Succeeded` was `true`), **is there some difference in functionality between them that I just didn't notice?**

**Why did they all work except `OpenIdConnect` which resulted in `InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'`?**

**Comment by AndersAbel** [comment]
All of those schemes except `OpenIdConnect` are different instances of the cookie handler. So all of them work exactly the same. Having multiple cookie schemes in an application is useful if you need them for different purposes. They usually have different configuration (such as life times). When using Asp.Net Identity (which it looks like from the code), the right value of the `SignInScheme` in the open id connect configuration is `Identity.External`. That is the scheme that is intended to be used for external logins with the callback. But as you have seen, it's possible to use any cookie scheme, as long as you use the same in the callback.

Using the "Identity.Application" scheme however has severe security implications as that scheme is used to hold the main session. The idea with the external callback is to isolate the external identity from the main application session. The callback is the place where the external identity is mapped to an application main identity. Mixing up the cookie schemes breaks that isolation.

The names of the Identity.* schemes are self explanatory. The `idsrv` and `idsrv.external` are the IdentityServer defaults. If Asp.Net Identity is used they are replaced by `Identity.Application` and `Identity.External`.

`OpenIdConnect` is not a cookie based scheme and does not have the capability to maintain sessions. The reason you get "Unable to get configuration..." is because the discovery document was not available. The location of the discovery document is based on the configured authority and would be  `https://mrisaas.oktapreview.com/.well-known/openid-configuration` in your example.

**Comment by DavidKlempfner** [comment]
> They usually have different configuration (such as life times)
Is this by default? Or do you have to configure that yourself?

> Having multiple cookie schemes in an application is useful if you need them for different purposes

Are there any examples on GitHub that use more than one scheme? I think that'd help me understand better, why there are multiple schemes.

**Comment by josephdecock** [comment]
You do generally need to configure the cookie auth schemes yourself. 

One example of multiple schemes is [our quickstart tutorial](https://docs.duendesoftware.com/identityserver/v6/quickstarts/2_interactive/), where we show how to do external authentication and use the external authentication cookie. The external authentication cookie in this case is the cookie that identity server registers specifically for this purpose.

**Comment by DavidKlempfner** [comment]
> where can I find the implementation for each authentication scheme?

https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/IdentityServiceCollectionExtensions.cs#L59
