### ISSUE TITLE
AddDataProtection Custom Persistence

### ISSUE THREAD

**Issue by billcunnien** [DuendeSoftware/Support#895]
Duende 6.2.3
.NET 6

Using identity server, how do I implement my own data protection persistence? I assume you have come across this before and provided an answer somewhere. My goal is to provide a mechanism for our load balanced servers to store these keys in a database via our API.

Thanks,
Bill

**Comment by billcunnien** [comment]
I added the following in HostingExtensions:

        builder.Services.AddSingleton<IXmlRepository, MyXmlRepository>();
        builder.Services
            .AddDataProtection()
            .SetApplicationName("MyIdentityServer");

The MyXmlRepository implements the GetAllElements and StoreElement methods (which are utilizing our internal API to handle the actual database calls).

Will this work?

**Comment by billcunnien** [comment]
I have implemented a similar repository as the FileSystemXmlRepository and used that as a test. It does not read/write anything to the expected folder. So, since it wasn't doing anything, and the IS was functioning properly, I decided to remove AddDataProtection. The system appears to function exactly as it has before. Is DataProtection not required? If it is, why would the system be working when it is not even being added? More confused than ever.

**Comment by billcunnien** [comment]
The custom XML repository is now reading/writing to a folder - and I was able to properly register the custom repository. 

        public static IDataProtectionBuilder PersistKeysToCustom(this IDataProtectionBuilder builder)
        {
            if (builder == null) { throw new ArgumentNullException(nameof(builder)); }

            builder.Services.AddSingleton<IConfigureOptions<KeyManagementOptions>>(services =>
            {
                return new ConfigureOptions<KeyManagementOptions>(options =>
                {
                    options.XmlRepository = new CustomXmlRepository(builder.Services.BuildServiceProvider().GetService<IMediator>());
                });
            });

            return builder;
        }

My next step will be to actually connect it to the API and have it read/write to a database. 

I am getting the following error: 

No XML encryptor configured. Key {809cf694-b800-4c7d-8057-18e36e44a388} may be persisted to storage in unencrypted form. 

I am thinking that this is a result of not having the API wired up, yet, to read/write these values. Am I correct in thinking this? If so, then this result leads me to think that AddDataProtection is very important to the IS.

**Comment by billcunnien** [comment]
It is quite unusual to not get a reply for this long. I have decided to scrap all of my changes and just implement a local use of the file system on one of the server, then sync that folder to the rest of the server array. Still not 100% sure this will work properly, but seemed like a decent approach - only that one server will manage keys and the rest will have auto key generation disabled. Hope to still hear back from support regarding some of my questions above. In addition, none of the MS docs are clear about how these keys are actually being generated (what is the trigger; e.g. app pool recycle, IIS restart, key expiration?, etc.) and how does each server stay up-to-date with the keys. If you can pass that knowledge on, I would appreciate it.

**Comment by josephdecock** [comment]
Hi @billcunnien, sorry for the delay in our response. 

For most common data protection scenarios, persistence isn't something that you need to implement from scratch. Asp.Net ships with implementations of the xml repository that persist to the file system, a database, or azure blob storage, and other cloud vendors, like AWS, provide implementations for their systems as well.

Microsoft has great documentation on data protection [here](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview) that shows how to use those implementations.

We also have recently updated our documentation [here](https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/) describing how identity server uses data protection and common configurations for data protection in IdentityServer implementations. 

So our usual recommendation is to not implement the xml repository in the first place. If you do have specialized needs that lead you to do that, Microsoft's docs and support are the better place to go for support for that specifically.

Your current plan of syncing the file system will probably cause you problems, because data protection reads and writes keys as it rotates them. All the nodes need to read and write to a shared location. You also need to protect the keys at rest in some way - perhaps with a certificate - because otherwise access to that shared location gives complete control over your secrets.

**Comment by josephdecock** [comment]
You might also find [this doc](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-management?view=aspnetcore-7.0#key-expiration-and-rolling) from microsoft helpful on key management. It describes how the keys are created and rotated.

**Comment by billcunnien** [comment]
The recent update to the documentation was missed by me. I appreciate that link. Also, the MS doc was very enlightening. I do not understand why you are recommending "to not implement the xml repository". It is a valid option and, from my perspective, the easiest to manage (we have no Azure storage and no accessible Redis).

I am unclear why a syncing of a folder on a server would be problematic. This primary server would be responsible for key management and all other servers would only pull the keys from the local folder (which is synced). Since keys are generated with a 2 day activation, essentially that is the amount of time needed to sync the folders (although, we are likely talking about milliseconds in latency).  What is the downside?

If we went with a shared network folder, then the servers ought to be configured the same way - only one being the key boss. Not sure if there is much difference in risk here between these scenarios.

Thanks!
Bill

**Comment by josephdecock** [comment]
I agree that the xml repository is a valid option. I would however avoid implementing it to reduce the complexity of the solution, since there already are built in implementations that [persist to the filesystem](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-7.0#persistkeystofilesystem) or a [database](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-7.0#persistkeystodbcontext). Neither of those require redis or cloud resources, but if they don't do what you need, then of course the xml repository interfaces are there for you to fulfill the contract however you like.

The reason that I expect that your syncing strategy may have difficulties is that it isn't clear to me how you can keep the secondary nodes from trying to create keys. If the secondary node did create a key, it would then have a key that no other nodes did, and data it protected could only be unprotected by it. On the other hand, if you do prevent secondary nodes from creating keys, how do those nodes operate without a key when they need one? Maybe if you arrange to start up the whole system in the correct order (primary "key boss" starts first, wait for it to create keys and sync, then secondary nodes start), you could make this work, at least at first, but I don't know what happens later on when a secondary node wants to create a new key (when it would rotate them), but can't. 

Using a file share and `PersistKeysToFileSystem`, there's no need to have primary and secondary nodes. Whichever node sees that a key is needed first will create it, and the other nodes will immediately be able to read it. And if two nodes somehow concurrently create keys, both would be available to all nodes.

**Comment by billcunnien** [comment]
The PersistKeysToFileSystem is the out-of-the-box implementation of IXmlRepository. I was confused by what you meant. Sorry about that. We are using this built-in implementation; however, we will need to explore the UNC folder option some more. Currently, we will sync the primary folder to all secondary servers (each secondary server will have automatic key generation disabled (DisableAutomaticKeyGeneration)). If a network file share will work, I would prefer that, but we may not have that option in our load balanced environment.

**Comment by josephdecock** [comment]
Okay, sounds like you have a path forward. Ultimately, IdentityServer takes DataProtection as a dependency, and how you fulfill that dependency might be specific to your environment. From IdentityServer's perspective, the only real requirement is that we can protect and unprotect data. For now, I think we can close this issue, and if your syncing and/or UNC explorations don't work out, we can always reopen it, ok?

**Comment by billcunnien** [comment]
Thanks!
