### ISSUE TITLE
Sql script for azure database

### ISSUE THREAD

**Issue by kjeqvist** [DuendeSoftware/Support#898]
Hi, do you have any sql script for creating the Identity Server database in Azure?

B R
Kjell Lindqvist

**Comment by josephdecock** [comment]
We actually don't provide the sql scripts directly, because we abstract IdentityServer from the specifics of the data store in order to make it possible to use IdentityServer with any database.

There are store interfaces in IdentityServer that allow data access to be totally customized. We provide in memory and entity framework based implementations of those stores. The EF based implementations can be used with any database with an EF provider, and those different databases have different syntax and semantics. If you're using that implementation of the store, you can use EF migrations to generate a script that is appropriate for your database. Our quickstart tutorial shows how to use those tools [here](https://docs.duendesoftware.com/identityserver/v6/quickstarts/4_ef/).

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?
