### ISSUE TITLE
Azure AD OIDC and IdentityServer OIDC interoperability

### ISSUE THREAD

**Issue by Exagram** [DuendeSoftware/Support#9]
**Which version of Duende IdentityServer are you using?**

4 (Target)

**Which version of .NET are you using?**

6.0.101

**Describe the bug**

I have a Web App and Mobile App that uses Azure AD OIDC for both authentication and authorization to a Web API (Library: [MSAL](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-overview)).

This works great in prod but in dev/uat I am unable to impersonate Azure AD users for testing.
- What if I switch away from Azure AD as a login portal/STS and switch over to a dev/uat `IdentityServer` which I can control?
- If so I can keep existing app authentication logic in-place and simply reconfigure my settings to point to dev/uat `IdentityServer`
- Is `IdentityServer4` interoperable with...
  - Web App [UseOpenIdConnectAuthentication]?(https://github.com/c4net/katanaproject/blob/master/src/Microsoft.Owin.Security.OpenIdConnect/OpenIdConnectAuthenticationExtensions.cs)
    - If not replace with [AddOpenIdConnect](https://identityserver4.readthedocs.io/en/latest/quickstarts/3_aspnetcore_and_apis.html)?
    - Note: My WebForms Web App is .NET Framework 4.8 and cannot use the `AddOpenIdConnect` .NET Core method. Does `IdentityServer4` support the old `UseOpenIdConnectAuthentication` .NET Framework 4.8 method?
  - Web API [AddMicrosoftIdentityWebApi](https://github.com/AzureAD/microsoft-identity-web/blob/e974a25d1dbf9f3136076795061a4aa37c0ad259/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs)?
    - If not replace with [AddJwtBearer](https://identityserver4.readthedocs.io/en/latest/topics/apis.html)?
  - Mobile App [msal-react](https://www.npmjs.com/package/@azure/msal-react)
    - If not replace with [oidc-client](https://www.npmjs.com/package/oidc-client)?
    - The library isn't maintained. Is there an alternative?

**To Reproduce**

N/A

**Expected behavior**

N/A

**Log output/exception with stacktrace**

N/A

**Additional context**

N/A

**Comment by brockallen** [comment]
This repo is for supporting Duende IdentityServer, which is the successor of IdentityServer4. IdentityServer4 is no longer supported, other than for security vulnerabilities, and even that end in November 2022.

Having said all of that, Duende IdentityServer supports a [variety of protocols](https://docs.duendesoftware.com/identityserver/v6/overview/specs/), and yes all your client apps can use the proper protocol libraries to connect. Unfortunately not all platforms (e.g. AAD) support all the same levels of the specs. So you might find that there are differences, which is why you are using vendor specific libraries in your apps today to connect to AAD.

As for your AAD scenario, a better idea might be the [federation gateway design](https://docs.duendesoftware.com/identityserver/v6/ui/federation/). That way your apps are shielded from these details and then you can, in one place, do what you need to with respect to the end-user authentication. 

As for your SPA client, the [BFF approach](https://docs.duendesoftware.com/identityserver/v6/bff/overview/) is recommended.

**Comment by Exagram** [comment]
Thanks @brockallen your two suggestions look promising!
