### ISSUE TITLE
load and chain dynamically multiple oidc settings

### ISSUE THREAD

**Issue by odyyudah** [DuendeSoftware/Support#901]
**Which version of Duende BFF are you using?**
.Version 2.1.1

**Which version of .NET are you using?**
.NET 7

**Describe the issue**
We have 30 oidc settings in our IDP, each and other oidc is different only in its scope setting.
Looking at the Blazor Wasm .NET6 sample, the difference of each 30 oidc scope setting is only at https://github.com/DuendeSoftware/Samples/blob/f1cec320717a5c231e3b30c04482a349f27ff25a/IdentityServer/v6/BFF/BlazorWasm/Server/Program.cs#L32

Now we end up created 30 blazor wasm app for each oidc scope setting, and let user open each blazor wasm URL of which they want to login into.
How to load and chain dynamically those 30 oidc setting into one BlazorWasm/Server/Program.cs so we only have one blazor wasm app for all those oidc settings? User would choose one from https://github.com/DuendeSoftware/BFF/blob/main/samples/Blazor6/Client/Pages/Index.razor

Thank you.

**Comment by josephdecock** [comment]
Sorry, I'm a little bit confused by what you're trying to accomplish. Can you back up and describe your goal? 

If you want your IdentityServer to allow login with many different OIDC providers, that sounds like federation, which we describe in our docs [here](https://docs.duendesoftware.com/identityserver/v6/ui/federation/).

**Comment by josephdecock** [comment]
Typically you would not have multiple client configurations for a single application. This is a very unusual/probably wrong thing to do. I think you mentioned in your first post that the only different in these client configurations was the allowed scopes? If that's the case, then you should just have 1 client configuration with all the scopes as allowed scopes, and then dynamically choose which scopes you want when you start the handshake.

**Comment by josephdecock** [comment]
A simplified approach might actually make sense here. Since you say you're learning the BFF, I would start out by just requesting all the scopes that the BFF might need.

It still seems odd to me that you would want your users to pick different scopes like this, since scopes authorize the application itself, not the end user.

But, if you really wanted to do it, you would need to pass the selected ui as a custom parameter to the bff login endpoint, and then [customize that endpoint](https://docs.duendesoftware.com/identityserver/v6/bff/extensibility/management/login/) to accept your new parameter. The default login endpoint normally calls SignInAsync for you. Your custom version could do that too, but you'd need to get the sign in call to know about the new parameter.

You could pass that parameter into the sign in process by creating an AuthentiationProperties object, adding your custom parameter to it, and passing that in to the call to sign in. 

Then FINALLY, you could add an event handler to the oidc authentication scheme for the OnRedirectToIdentityProvider event. In that event's context, you can get at the outgoing message and manipulate its parameters to include different scopes, based on what are in the authentication properties (which are also in the event context).

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?
