### ISSUE TITLE
Recommendation to perform QA API tests

### ISSUE THREAD

**Issue by molinch** [DuendeSoftware/Support#902]
We use Duende.Bff in our application and now start automating API tests.
Without it we would get an access token and then call APIs with it.

With Duende.Bff we need the session cookie to pass BFF auth. Thus, we use a headless browser which through /bff/login logs into Azure.
While it works it is not the most elegant nor the fastest option.

Do you have any idea or suggestion that could improve the use case of API testing?

**Comment by josephdecock** [comment]
One option is to treat your test harness as an IdentityServer client application, and have it perform the necessary flows to get an access token. If your APIs don't need user-centric access tokens, you could make the test harness a client credentials client, and it would be able to get tokens without a headless browser at all. If your apis do need user-centric access tokens, you might be able to simulate that, again without needing a headless browser, by using the resource owner password flow. This would allow your automation to get user-centric tokens without a browser. Do be aware that the resource owner password flow is not generally recommended in production due to security and usability limitations (it can't do MFA or Single Sign On, and it teaches users to expect to be phished), so I would make sure this test client only exists in your test environments.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?
