### ISSUE TITLE
AddInMemoryApiScopes() vs AddInMemoryApiResources() vs AddInMemoryIdentityResources()

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#905]
I'm using IDS6 and ASP.NET 6 with Identity.

I'm trying to understand what the following do and how they relate to `AllowedScopes` in the `Client` object:

- `AddInMemoryApiScopes()`
- `AddInMemoryApiResources()`
- `AddInMemoryIdentityResources()`

Here's my setup:

Client app calls IDS using:

`https://localhost:44349/connect/authorize
?client_id=pt-web
&response_type=code
&scope=**openid+ptpro+test1**
&redirect_uri=https%3A%2F%2F127.0.0.1%3A44300%2Fauthentication%2Fcallback
&state=%7B%22ReturnUrl%22%3A%22%2F%22%7D`

In Startup.cs, I'm calling the following:
```
.AddInMemoryClients(_configuration.GetSection("IdentityServer:Clients"))
.AddInMemoryApiScopes(_configuration.GetSection("IdentityServer:ApiScopes"))
.AddInMemoryApiResources(_configuration.GetSection("IdentityServer:ApiResources"))
.AddInMemoryIdentityResources(_configuration.GetSection("IdentityServer:IdentityResources"));
```
With the following from appsettings.json:

```
"IdentityServer": {
    "Clients": [
      {
        "Enabled": true,
        "ClientId": "pt-web",
        "ClientName": "Property Tree",
        "ClientSecrets": [ { "Value": "encryptedSecretHere" } ],
        "RedirectUris": [ "https://127.0.0.1:44300/authentication/callback" ],
        "PostLogoutRedirectUris": [ "https://127.0.0.1:44300/" ],
        "AllowedCorsOrigins": [ "https://127.0.0.1:44300" ],
        "FrontChannelLogoutUri": "https://127.0.0.1:44300/Authentication/ExternalLogout",
        "AllowedGrantTypes": [ "authorization_code", "client_credentials" ],
        "AllowedScopes": [ "openid", "ptpro", "test1" ],
        "RequireConsent": false,
        "AllowOfflineAccess": true,
        "AlwaysIncludeUserClaimsInIdToken": true,
        "AllowAccessTokensViaBrowser": true,
        "IdentityTokenLifetime": 36000,
        "AccessTokenLifetime": 36000,
        "AuthorizationCodeLifetime": 3000,
        "RefreshTokenUsage": "ReUse",
        "UpdateAccessTokenClaimsOnRefresh": true,
        "RefreshTokenExpiration": "Sliding",
        "IncludeJwtId": true,
        "AlwaysSendClientClaims": true,
        "RequirePkce": false
      }
    ],
    "ApiResources": [
      {
        "Name": "test1",
        "DisplayName": "Test1",
        "Scopes": [
          {
            "Name": "test1",
            "DisplayName": "Test1"
          }
        ],
        "UserClaims": [ "email" ]
      }
    ],
    "ApiScopes": [
      {
        "Name": "ptpro",
        "UserClaims": [ "source_ip" ]
      },
      {
        "Name": "test1",
        "UserClaims": [ "email" ]
      }
    ],
    "IdentityResources": [
      {
        "Name": "openid",
        "Required": true,
        "UserClaims": [
          "sub",
          "preferred_username"
        ]
      }
    ]
  }
```

It seems as though if a scope is to be allowed, it must be in `AllowedScopes` when setting up the `Client` object, AND also in `AddInMemoryApiScopes()`.

This appears redundant. Is there something extra that `AddInMemoryApiScopes()` does that `AllowedScopes` doesn't?

What is `AddInMemoryApiResources()` used for?

In this [article](https://www.scottbrady91.com/identity-server/getting-started-with-identityserver-4) I can see it's used for declaring the scopes to determine what you can do in an API, but couldn't those scopes be defined in `AddInMemoryApiScopes()`?

Why doesn't the `openid` scope also have to appear in `ApiScopes` like `ptpro` and `test1`?
I just found out through playing around with different combinations, that anything in `ApiScopes` can be listed in `ApiResources`, and anything in `ApiResources` MUST be in `ApiScopes`, but anything in `IdentityResources` must NOT be in `ApiScopes` or `ApiResources`.
Why is this?

This might be answered once the above are answered, but if there is `AddInMemoryApiResources()` and `AddInMemoryApiScopes()`, why is there only `AddInMemoryIdentityResources()` and no `AddInMemoryIdentityScopes()`?

I've created CustomProfileService and have put a breakpoint in `GetProfileDataAsync()`:

**AccessToken:**
![AccessToken](https://github.com/DuendeSoftware/Support/assets/13111539/777e9683-6229-48a0-9672-eaab54268f94)

**IdentityToken:**
![IdentityToken](https://github.com/DuendeSoftware/Support/assets/13111539/2b9ed2a4-44b6-4724-a9ec-e54acc3d4cc1)

From the above, is it true to say that any `UserClaims` from `ApiScopes` will be in the `AccessToken`, and any `UserClaims` from `IdentityResources` will be in the `IdentityToken`?

If all the `UserClaims` from `ApiScopes` go in the `AccessToken`, what is the point of `AddInMemoryApiResources()`?

**Comment by josephdecock** [comment]
OIDC is built on top of OAuth, and it reused the Oauth concept of scopes and somewhat overloaded it. So, you can ask for a scope with an OIDC semantic, like profile, to mean that you want access to the user's profile information, but you can ask for a scope with an oauth semantic, like api1, to mean that you are asking for permission to call api1. 

[ApiScope](https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/api_scopes/) and [IdentityResource](https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/identity/) are the types that IdentityServer uses to model each of these kinds of scopes. The distinct models aid in organization and make explicit that certain kinds of configuration errors are not allowed. Scopes and identity resources are configuration objects that hold lots of metadata about these scopes, including display names and claims that are associated with a request that includes that scope. openid and profile are two built in examples of IdentityResources. These are scopes that are defined in the OIDC spec, that we model as an IdentityResource because they represent identity data, not api access.

[ApiResource](https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/api_resources/) is the type that IdentityServer uses to model the APIs that exist that IdentityServer is aware of. You can use it as a logical grouping from scopes, and it enables other advanced features, such as the introspection and the JWT audience. In simple scenarios, you can get started without it. See the linked documentation for more details on how to make good use of it.



[Client](https://docs.duendesoftware.com/identityserver/v6/fundamentals/clients/) configuration includes a declaration of the scopes that the client is allowed to request. Those allowed scopes have to have a corresponding ApiScope or IdentityResource declaration - it isn't enough to just mention the scope by name, because scopes are large objects with additional metadata.


> anything in ApiScopes can be listed in ApiResources, and anything in ApiResources MUST be in ApiScopes, but anything in IdentityResources must NOT be in ApiScopes or ApiResources.
Why is this?

An ApiResource is our representation of an api, and the scopes that are associated with that api have to be api scopes - it isn't sensible to associate an identity resource with an API. Identity resources exist to get profile data and other claims in the userinfo endpoint, and they aren't applicable to other APIs.

> why is there only AddInMemoryIdentityResources() and no AddInMemoryIdentityScopes()?

There is no IdentityScope abstraction.

> From the above, is it true to say that any UserClaims from ApiScopes will be in the AccessToken, and any UserClaims from IdentityResources will be in the IdentityToken?

This is partly correct. The UserClaims are the names of claims that are requested when that scope is requested, and they are grouped in the way that you suggest - UserClaims in ApiScopes are requests for claims in the AccessToken, while IdentityResource UserClaims are requests for claims in the IdentityToken. Usually however, the IdentityToken only includes the sub claim, and additional identity resources are requested separately at the userinfo endpoint, which also takes the requested user claims from the requested IdentityResource scopes.
