### ISSUE TITLE
How can you add compatibility to a simple "API token" authentication?

### ISSUE THREAD

**Issue by oriolqc** [DuendeSoftware/Support#909]
Hi,

We have developed a SaaS.

We use Duende Identity Server 6 as our Identity & Authentication Server.

In the back-end, the different micro-services (.net core 6) authenticate users by using the token that Identity Server issues.

Now we would like to add a new feature: we would like that our users can access our API.

OAuth doesn't seem the option, as it would require the automated processes to use an interactive login with our Identity Server (or are we missing something?).

Another option would be to let users generate an API token, so that automated processes could connect to the API and authenticate with those tokens.

Regarding to this second scenario: is it possible to do it with Identity Server? Should add a second authentication scheme (such as authenticate with JWT tokens) and create a second authentication mechanism completely apart from Identity Server? We actually don't know if it's actually possible or it has sense.

Can anyone help us guiding on how should we do it?

Thanks a lot,

**Comment by AndersAbel** [comment]
When using IdentityServer to protect your APIs, the recommended architecture is to make all your API authentication use IdentityServer-issued tokens. This simplifies your API and centralizes the logic/rules of token issuance into IdentityServer.

If I understand your requirements right, you want your users to be able to access your API without the user being present. This means that a backend/background process must be able to retrieve access tokens without any user interaction, or the user being present.

Saas solutions have two options on how to approach this.

The first one is to use [refresh tokens](https://docs.duendesoftware.com/identityserver/v6/tokens/refresh/) to let the application continue to use the API on behalf of a specific user, even after the user's session expire. This ties the API requests to a specific user.

In some cases, it might be inappropriate to tie the API access to a specific user though. If the Saas service works with organisations or tenants with multiple users the API access is usually intended to be made on behalf of the organisation, rather than on behalf of a specific user within the organisation. In that case it could be more appropriate to use [dynamic client registration](https://docs.duendesoftware.com/identityserver/v6/configuration/dcr/) to let an authenticated user create a dedicated client that is allowed to use client credentials to request access tokens.

**Comment by AndersAbel** [comment]
To get a more simple experience that looks more like API keys, it is also possible to use reference tokens as personal access tokens (PAT). This will let the user get a token that is long lived, but that can be revoked if required. We do have a sample at https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/PAT that shows how this could work.

**Comment by oriolqc** [comment]
Hi,

Exactly, we want a background process to access our API without user intervention.

In our case it's perfect to authenticate the process on behalf of a specific user, as this will grant the process the exact permissions the user has.

However, I've checked the documentation and I have some doubts:
- Do we need a client secret to get a refresh token?
- How long can it last a refresh token? For example, we access Pipedrive API with a process and I think the security token it has never expired over years.
- The refresh token will be tied to Identity Server "memory state" doesn't it? Should we persist then the data in a DB? (should we follow this: https://docs.duendesoftware.com/identityserver/v6/data/ef/?).

Thanks

**Comment by AndersAbel** [comment]
1. No, you do not need to have a client secret to use refresh tokens. If you distribute the refresh tokens to end users it doesn't make sense to have a shared client secret for them. To use client secrets in such a scenario it would be necessary to use dynamic client registration to create a client for each customer/user.
2. The refresh token lifetime is configurable. There is also a sliding expiration mechanism that allows unlimited lifetime, but only if it is regularly used.
3. Yes, the refresh token (and the reference token used as PAT) are stored in the persisted grants store. Even though the default is to use an in memory storage, that is only recommended for development. For any real deployment a persisted store, such as our EF based stores should be used.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?

**Comment by oriolqc** [comment]
Hi, I think it's pretty clear. We will follow the PAT example and I think it's what we need. Thanks!
