### ISSUE TITLE
Best Practice

### ISSUE THREAD

**Issue by MertGuney** [DuendeSoftware/Support#933]
Which version of Duende IdentityServer are you using?

6.3.5

Which version of .NET are you using?

Net7.0

Hello,

We strive to make the best improvements in our company, which is why we choose to use your service. We have a few questions to ask you about best practices.

Our applications have their own login pages (ReactJS - Flutter) so we currently prefer password grant type but we realized that it is no longer supported and we also know that this method is not secure.

NOTE: We also get invalid_grant error when we try to refresh the token with password grant type

1- What are the most suitable grant types for our mobile and Js applications?

2- Currently our Auth Server application is an Api application, should we switch to MVC? How can we continue without switching?

3- Can we use BFF pattern in our mobile application?

4- Can we continue without setting up centralized membership?

**Comment by AndersAbel** [comment]
1. For web sites and interactive applications on computers/phones/tablets, the recommendation is to use Authorization Code flow with PKCE enabled.

2. You can host IdentityServer in any Asp.Net core project. Our recommendation is to have a separate IdentityServer host project that do not contain other code. Keeping the amount of code running in a security sensitive process reduces the risk for mistakes that can be exploited. The IdentityServer core library need to be able to redirect to UI pages for login and consent. Our default in our templates are to implement those as razor pages in the IdentityServer project, because it's simple. But it's possible to use MVC or  something else. It is up to the hosting implementation to do what work best in your setup.

3. No. The BFF pattern is meant to solve the problem that a web browser is not a good platform to implement an OpenID Connect client library or to hold tokens. A mobile app on the other hand is a good platform both for being an OIDC client and handling the tokens. One way to describe the BFF is that it is a reverse proxy for cookie-to-token translation. That is only relevant for web applications and not for mobile apps. (It is probably technically possible to the BFF pattern, but it would be awkward).

4. What do you mean by "centralized membership"? If the question is about user storage, then the answer is that IdentityServer makes no assumptions on how the user storage works. IdentityServer just needs an implementation of `IProfileService` that can return information about a user.

**Comment by MertGuney** [comment]
Thank you for the valuable information

4. I was referring to the sso feature.

So what problems can be caused by continuing to use the password grant type

also why we get an invalid_grant error when we send a refresh token request

client information:

![Screenshot 2023-10-05 140544](https://github.com/DuendeSoftware/Support/assets/52934069/f24f8b0a-eb6f-451a-8093-498390bba5a6)

**Comment by MertGuney** [comment]
How can I adjust the time settings? It saves the wrong time when saving to the database

**Comment by AndersAbel** [comment]
The time is based on the system time. All data is saved using UTC time and not the local time zone. Are the times correct as UTC times?

**Comment by MertGuney** [comment]
We use UTC+3 timezone and our servers are in Turkey so we use dd/aa/yyyy format. Could this be the problem?

**Comment by AndersAbel** [comment]
The times as stored in the database use a proper date time format that is independent of any UI culture for formatting. What the date is displayed like doesn't matter.

The time should still be UTC times. Are the times right in the database considering that they are in UTC?

**Comment by AndersAbel** [comment]
Do you have any more questions or can we go ahead and close this issue?
