### ISSUE TITLE
Identity Server 4 question

### ISSUE THREAD

**Issue by cmn4titans** [DuendeSoftware/Support#947]
Hello,
 
I am working with Identity server 4. I am having trouble getting the bearer token after yo login from this page.

Just wondering if there is an example or if someone could give me a direction.

![identityserverlogin](https://github.com/DuendeSoftware/Support/assets/147832791/f635ed74-0635-42f2-8966-61ed65bd3d36)

Thank you,

Charles

**Comment by leastprivilege** [comment]
IdentityServer4 is out of development since October 2020. Also IdentityServer4 only supports .NET Core 3.1. This version of .NET is out of Microsoft support since December 2022. From this point you will not get updates or security patches from Microsoft anymore. I would recommend upgrading to a supported version of .NET and IdentityServer as soon as possible.

This forum is for support for Duende IdentityServer.
